My Project: kernel/asmfunc.h File Reference
asmfunc.h File Reference
#include <stdint.h>
Functions
void IoOut32 (uint16_t addr, uint32_t data)
uint32_t IoIn32 (uint16_t addr)
uint16_t GetCS (void)
void LoadIDT (uint16_t limit, uint64_t offset)
void LoadGDT (uint16_t limit, uint64_t offset)
void SetCSSS (uint16_t cs, uint16_t ss)
void SetDSAll (uint16_t value)
void SetCR3 (uint64_t value)
uint64_t GetCR3 ()
void SwitchContext (void *next_ctx, void *current_ctx)
Function Documentation
GetCR3()
uint64_t GetCR3 ()
Referenced by Task::InitContext().
GetCS()
uint16_t GetCS (void)
IoIn32()
uint32_t IoIn32 (uint16_t addr)
Referenced by pci::ReadData(), and acpi::WaitMilliseconds().
IoOut32()
void IoOut32 (uint16_t addr, uint32_t data)
Referenced by pci::WriteAddress(), and pci::WriteData().
LoadGDT()
void LoadGDT (uint16_t limit, uint64_t offset)
Referenced by SetupSegments().
LoadIDT()
void LoadIDT (uint16_t limit, uint64_t offset)
Referenced by InitializeInterrupt().
SetCR3()
void SetCR3 (uint64_t value)
Referenced by SetupIdentityPageTable().
SetCSSS()
void SetCSSS (uint16_t cs, uint16_t ss)
Referenced by InitializeSegmentation().
SetDSAll()
void SetDSAll (uint16_t value)
Referenced by InitializeSegmentation().
SwitchContext()
void SwitchContext (void * next_ctx, void * current_ctx)
Referenced by TaskManager::SwitchTask().