My Project: usb::EndpointID Class Reference
usb::EndpointID Class Reference
#include <endpoint.hpp>
Public Member Functions
constexpr EndpointID ()
constexpr EndpointID (const EndpointID &ep_id)
constexpr EndpointID (int addr)
constexpr EndpointID (int ep_num, bool dir_in)
EndpointID & operator= (const EndpointID &rhs)
int Address () const
int Number () const
bool IsIn () const
Private Attributes
int addr_
Detailed Description
Definition at line 19 of file endpoint.hpp.
Constructor & Destructor Documentation
EndpointID() [1/4]
constexpr usb::EndpointID::EndpointID () inline constexpr
Definition at line 21 of file endpoint.hpp.
EndpointID() [2/4]
constexpr usb::EndpointID::EndpointID (const EndpointID & ep_id) inline constexpr
Definition at line 22 of file endpoint.hpp.
References addr_.
EndpointID() [3/4]
constexpr usb::EndpointID::EndpointID (int addr) inline explicit constexpr
Definition at line 23 of file endpoint.hpp.
EndpointID() [4/4]
constexpr usb::EndpointID::EndpointID (int ep_num, bool dir_in) inline constexpr
エンドポイント番号と入出力方向から ID を構成する．
ep_num は 0..15 の整数． dir_in は Control エンドポイントでは常に true にしなければならない．
Definition at line 30 of file endpoint.hpp.
References dir_in.
Member Function Documentation
Address()
int usb::EndpointID::Address () const inline
エンドポイントアドレス（0..31）
Definition at line 38 of file endpoint.hpp.
References addr_.
Referenced by usb::xhci::Device::ControlIn(), usb::xhci::Device::ControlOut(), usb::xhci::DeviceContextIndex::DeviceContextIndex(), usb::xhci::Device::InterruptOut(), anonymous_namespace{device.cpp}::Log(), and usb::Device::OnInterruptCompleted().
IsIn()
bool usb::EndpointID::IsIn () const inline
入出力方向．Control エンドポイントは true
Definition at line 44 of file endpoint.hpp.
References addr_.
Referenced by usb::HIDBaseDriver::OnInterruptCompleted(), and usb::HIDBaseDriver::SetEndpoint().
Number()
int usb::EndpointID::Number () const inline
エンドポイント番号（0..15）
Definition at line 41 of file endpoint.hpp.
References addr_.
Referenced by usb::xhci::Device::ControlIn(), usb::xhci::Device::ControlOut(), and usb::Device::OnInterruptCompleted().
operator=()
EndpointID& usb::EndpointID::operator= (const EndpointID & rhs) inline
Definition at line 32 of file endpoint.hpp.
References addr_.
Member Data Documentation
addr_
int usb::EndpointID::addr_ private
Definition at line 47 of file endpoint.hpp.
Referenced by Address(), EndpointID(), IsIn(), Number(), and operator=().
The documentation for this class was generated from the following file:
kernel/usb/endpoint.hpp