My Project: usb::ClassDriver Class Reference
usb::ClassDriver Class Reference abstract
#include <base.hpp>
Public Member Functions
ClassDriver (Device *dev)
virtual ~ClassDriver ()
virtual Error Initialize ()=0
virtual Error SetEndpoint (const EndpointConfig &config)=0
virtual Error OnEndpointsConfigured ()=0
virtual Error OnControlCompleted (EndpointID ep_id, SetupData setup_data, const void *buf, int len)=0
virtual Error OnInterruptCompleted (EndpointID ep_id, const void *buf, int len)=0
Device * ParentDevice () const
Private Attributes
Device * dev_
Detailed Description
Definition at line 16 of file base.hpp.
Constructor & Destructor Documentation
ClassDriver()
usb::ClassDriver::ClassDriver (Device * dev)
Definition at line 4 of file base.cpp.
~ClassDriver()
usb::ClassDriver::~ClassDriver () virtual
Definition at line 7 of file base.cpp.
Member Function Documentation
Initialize()
virtual Error usb::ClassDriver::Initialize () pure virtual
Implemented in usb::HIDBaseDriver.
OnControlCompleted()
virtual Error usb::ClassDriver::OnControlCompleted (EndpointID ep_id, SetupData setup_data, const void * buf, int len) pure virtual
Implemented in usb::HIDBaseDriver.
OnEndpointsConfigured()
virtual Error usb::ClassDriver::OnEndpointsConfigured () pure virtual
Implemented in usb::HIDBaseDriver.
OnInterruptCompleted()
virtual Error usb::ClassDriver::OnInterruptCompleted (EndpointID ep_id, const void * buf, int len) pure virtual
Implemented in usb::HIDBaseDriver.
ParentDevice()
Device* usb::ClassDriver::ParentDevice () const inline
このクラスドライバを保持する USB デバイスを返す．
Definition at line 29 of file base.hpp.
References dev_.
Referenced by usb::HIDBaseDriver::OnControlCompleted(), usb::HIDBaseDriver::OnEndpointsConfigured(), and usb::HIDBaseDriver::OnInterruptCompleted().
SetEndpoint()
virtual Error usb::ClassDriver::SetEndpoint (const EndpointConfig & config) pure virtual
Implemented in usb::HIDBaseDriver.
Member Data Documentation
dev_
Device* usb::ClassDriver::dev_ private
Definition at line 32 of file base.hpp.
Referenced by ParentDevice().
The documentation for this class was generated from the following files:
kernel/usb/classdriver/base.hpp
kernel/usb/classdriver/base.cpp