My Project: MemMapRegister< T > Class Template Reference
MemMapRegister< T > Class Template Reference
#include <register.hpp>
Public Member Functions
T Read () const
void Write (const T &value)
Private Attributes
volatile T value_
Static Private Attributes
static const size_t len_ = ArrayLength<decltype(T::data)>::value
Detailed Description
template<typename T>
class MemMapRegister< T >
MemMapRegister is a wrapper for a memory mapped register.
MemMapRegister forces user program to read/write the underlying register with specific bit width. The bit width will be deduced from the type of T::data. T is the template parameter. T::data should be an array.
Definition at line 28 of file register.hpp.
Member Function Documentation
Read()
template<typename T > T MemMapRegister< T >::Read () const inline
Definition at line 30 of file register.hpp.
Referenced by usb::xhci::ExtendedRegisterList::Iterator::operator++(), anonymous_namespace{xhci.cpp}::RegisterCommandRing(), and anonymous_namespace{xhci.cpp}::RequestHCOwnership().
Write()
template<typename T > void MemMapRegister< T >::Write (const T & value) inline
Definition at line 38 of file register.hpp.
Referenced by anonymous_namespace{xhci.cpp}::RegisterCommandRing().
Member Data Documentation
len_
template<typename T > const size_t MemMapRegister< T >::len_ = ArrayLength<decltype(T::data)>::value static private
Definition at line 46 of file register.hpp.
Referenced by MemMapRegister< usb::xhci::CRCR_Bitmap >::Read(), and MemMapRegister< usb::xhci::CRCR_Bitmap >::Write().
value_
template<typename T > volatile T MemMapRegister< T >::value_ private
Definition at line 45 of file register.hpp.
Referenced by MemMapRegister< usb::xhci::CRCR_Bitmap >::Read(), and MemMapRegister< usb::xhci::CRCR_Bitmap >::Write().
The documentation for this class was generated from the following file:
kernel/register.hpp