My Project: usb::xhci::Port Class Reference
usb::xhci::Port Class Reference
#include <port.hpp>
Public Member Functions
Port (uint8_t port_num, PortRegisterSet &port_reg_set)
uint8_t Number () const
bool IsConnected () const
bool IsEnabled () const
bool IsConnectStatusChanged () const
bool IsPortResetChanged () const
int Speed () const
Error Reset ()
Device * Initialize ()
void ClearConnectStatusChanged () const
void ClearPortResetChange () const
Private Attributes
const uint8_t port_num_
PortRegisterSet & port_reg_set_
Detailed Description
Definition at line 27 of file port.hpp.
Constructor & Destructor Documentation
Port()
usb::xhci::Port::Port (uint8_t port_num, PortRegisterSet & port_reg_set) inline
Definition at line 29 of file port.hpp.
Member Function Documentation
ClearConnectStatusChanged()
void usb::xhci::Port::ClearConnectStatusChanged () const inline
Definition at line 42 of file port.hpp.
References CLEAR_STATUS_BIT, and connect_status_change.
ClearPortResetChange()
void usb::xhci::Port::ClearPortResetChange () const inline
Definition at line 45 of file port.hpp.
References CLEAR_STATUS_BIT, and port_reset_change.
Referenced by anonymous_namespace{xhci.cpp}::EnableSlot().
Initialize()
Device * usb::xhci::Port::Initialize ()
Definition at line 40 of file port.cpp.
IsConnected()
bool usb::xhci::Port::IsConnected () const
Definition at line 11 of file port.cpp.
References port_reg_set_, and usb::xhci::PortRegisterSet::PORTSC.
Referenced by anonymous_namespace{xhci.cpp}::ResetPort().
IsConnectStatusChanged()
bool usb::xhci::Port::IsConnectStatusChanged () const
Definition at line 19 of file port.cpp.
References port_reg_set_, and usb::xhci::PortRegisterSet::PORTSC.
IsEnabled()
bool usb::xhci::Port::IsEnabled () const
Definition at line 15 of file port.cpp.
References port_reg_set_, and usb::xhci::PortRegisterSet::PORTSC.
Referenced by anonymous_namespace{xhci.cpp}::EnableSlot().
IsPortResetChanged()
bool usb::xhci::Port::IsPortResetChanged () const
Definition at line 23 of file port.cpp.
References port_reg_set_, and usb::xhci::PortRegisterSet::PORTSC.
Referenced by anonymous_namespace{xhci.cpp}::EnableSlot().
Number()
uint8_t usb::xhci::Port::Number () const
Definition at line 7 of file port.cpp.
References port_num_.
Referenced by usb::xhci::ConfigurePort(), anonymous_namespace{xhci.cpp}::EnableSlot(), anonymous_namespace{xhci.cpp}::InitializeSlotContext(), and anonymous_namespace{xhci.cpp}::ResetPort().
Reset()
Error usb::xhci::Port::Reset ()
Definition at line 31 of file port.cpp.
References Error::kSuccess, MAKE_ERROR, port_reg_set_, and usb::xhci::PortRegisterSet::PORTSC.
Referenced by anonymous_namespace{xhci.cpp}::ResetPort().
Speed()
int usb::xhci::Port::Speed () const
Definition at line 27 of file port.cpp.
References port_reg_set_, and usb::xhci::PortRegisterSet::PORTSC.
Referenced by usb::xhci::ConfigureEndpoints(), and anonymous_namespace{xhci.cpp}::InitializeSlotContext().
Member Data Documentation
port_num_
const uint8_t usb::xhci::Port::port_num_ private
Definition at line 50 of file port.hpp.
Referenced by Number().
port_reg_set_
PortRegisterSet& usb::xhci::Port::port_reg_set_ private
Definition at line 51 of file port.hpp.
Referenced by IsConnected(), IsConnectStatusChanged(), IsEnabled(), IsPortResetChanged(), Reset(), and Speed().
The documentation for this class was generated from the following files:
kernel/usb/xhci/port.hpp
kernel/usb/xhci/port.cpp