My Project: PixelWriter Class Reference
PixelWriter Class Reference abstract
#include <graphics.hpp>
Public Member Functions
virtual ~PixelWriter ()=default
virtual void Write (Vector2D< int > pos, const PixelColor &c)=0
virtual int Width () const =0
virtual int Height () const =0
Detailed Description
Definition at line 88 of file graphics.hpp.
Constructor & Destructor Documentation
~PixelWriter()
virtual PixelWriter::~PixelWriter () virtual default
Member Function Documentation
Height()
virtual int PixelWriter::Height () const pure virtual
Implemented in FrameBufferWriter, and Window::WindowWriter.
Referenced by DrawDesktop(), and DrawWindow().
Width()
virtual int PixelWriter::Width () const pure virtual
Implemented in FrameBufferWriter, and Window::WindowWriter.
Referenced by DrawDesktop(), and DrawWindow().
Write()
virtual void PixelWriter::Write (Vector2D< int > pos, const PixelColor & c) pure virtual
Implemented in BGRResv8BitPerColorPixelWriter, RGBResv8BitPerColorPixelWriter, and Window::WindowWriter.
Referenced by DrawMouseCursor(), DrawRectangle(), DrawWindow(), FillRectangle(), Window::Write(), and WriteAscii().
The documentation for this class was generated from the following file:
kernel/graphics.hpp