My Project: FrameBuffer Class Reference
FrameBuffer Class Reference
#include <frame_buffer.hpp>
Public Member Functions
Error Initialize (const FrameBufferConfig &config)
Error Copy (Vector2D< int > dst_pos, const FrameBuffer &src, const Rectangle< int > &src_area)
void Move (Vector2D< int > dst_pos, const Rectangle< int > &src)
FrameBufferWriter & Writer ()
const FrameBufferConfig & Config () const
Private Attributes
FrameBufferConfig config_
std::vector< uint8_t > buffer_ {}
std::unique_ptr< FrameBufferWriter > writer_ {}
Detailed Description
Definition at line 10 of file frame_buffer.hpp.
Member Function Documentation
Config()
const FrameBufferConfig& FrameBuffer::Config () const inline
Definition at line 17 of file frame_buffer.hpp.
References config_.
Referenced by LayerManager::SetWriter().
Copy()
Error FrameBuffer::Copy (Vector2D< int > dst_pos, const FrameBuffer & src, const Rectangle< int > & src_area)
Definition at line 58 of file frame_buffer.cpp.
References anonymous_namespace{frame_buffer.cpp}::BytesPerPixel(), anonymous_namespace{frame_buffer.cpp}::BytesPerScanLine(), config_, anonymous_namespace{frame_buffer.cpp}::FrameAddrAt(), anonymous_namespace{frame_buffer.cpp}::FrameBufferSize(), Error::kSuccess, Error::kUnknownPixelFormat, MAKE_ERROR, FrameBufferConfig::pixel_format, Rectangle< T >::pos, and Rectangle< T >::size.
Referenced by LayerManager::Draw(), and Window::DrawTo().
Initialize()
Error FrameBuffer::Initialize (const FrameBufferConfig & config)
Definition at line 26 of file frame_buffer.cpp.
References buffer_, anonymous_namespace{frame_buffer.cpp}::BytesPerPixel(), config_, FrameBufferConfig::frame_buffer, FrameBufferConfig::horizontal_resolution, kPixelBGRResv8BitPerColor, kPixelRGBResv8BitPerColor, Error::kSuccess, Error::kUnknownPixelFormat, MAKE_ERROR, FrameBufferConfig::pixel_format, FrameBufferConfig::pixels_per_scan_line, FrameBufferConfig::vertical_resolution, and writer_.
Referenced by InitializeLayer(), and LayerManager::SetWriter().
Move()
void FrameBuffer::Move (Vector2D< int > dst_pos, const Rectangle< int > & src)
Definition at line 87 of file frame_buffer.cpp.
References anonymous_namespace{frame_buffer.cpp}::BytesPerPixel(), anonymous_namespace{frame_buffer.cpp}::BytesPerScanLine(), config_, anonymous_namespace{frame_buffer.cpp}::FrameAddrAt(), FrameBufferConfig::pixel_format, Rectangle< T >::pos, Rectangle< T >::size, Vector2D< T >::x, and Vector2D< T >::y.
Referenced by Window::Move().
Writer()
FrameBufferWriter& FrameBuffer::Writer () inline
Definition at line 16 of file frame_buffer.hpp.
References writer_.
Referenced by Window::DrawTo(), and Window::Write().
Member Data Documentation
buffer_
std::vector<uint8_t> FrameBuffer::buffer_ {} private
Definition at line 21 of file frame_buffer.hpp.
Referenced by Initialize().
config_
FrameBufferConfig FrameBuffer::config_ private
Definition at line 20 of file frame_buffer.hpp.
Referenced by Config(), Copy(), Initialize(), and Move().
writer_
std::unique_ptr<FrameBufferWriter> FrameBuffer::writer_ {} private
Definition at line 22 of file frame_buffer.hpp.
Referenced by Initialize(), and Writer().
The documentation for this class was generated from the following files:
kernel/frame_buffer.hpp
kernel/frame_buffer.cpp