My Project: Layer Class Reference
Layer Class Reference
Layerは一つの層を表す。
#include <layer.hpp>
Public Member Functions
Layer (unsigned int id=0)
指定されたIDを持つレイヤーを生成する。
unsigned int ID () const
このインスタンスのIDを返す。
Layer & SetWindow (const std::shared_ptr< Window > &window)
ウィンドウを設定する。既存のウィンドウはこのレイヤーから外れる。
std::shared_ptr< Window > GetWindow () const
設定されたウィンドウを返す。
Vector2D< int > GetPosition () const
レイヤーの原点座標を取得する。
Layer & SetDraggable (bool draggable)
trueを設定するとレイヤーがドラッグ移動可能となる。
bool IsDraggable () const
レイヤーがドラッグ移動可能ならtrueを返す。
Layer & Move (Vector2D< int > pos)
レイヤーの位置情報を指定された絶対座標へと更新する。再描画はしない。
Layer & MoveRelative (Vector2D< int > pos_diff)
レイヤーの位置情報を指定された相対座標へと更新する。再描画はしない。
void DrawTo (FrameBuffer &screen, const Rectangle< int > &area) const
指定された描画先にウィンドウの内容を描画する。
Private Attributes
unsigned int id_
Vector2D< int > pos_
std::shared_ptr< Window > window_
bool draggable_ {false}
Detailed Description
Layerは一つの層を表す。
現状では一つのウィンドウしか保持できない設計だが、 将来的には複数のウィンドウを持ち得る。
Definition at line 21 of file layer.hpp.
Constructor & Destructor Documentation
Layer()
Layer::Layer (unsigned int id = 0)
指定されたIDを持つレイヤーを生成する。
Definition at line 8 of file layer.cpp.
Member Function Documentation
DrawTo()
void Layer::DrawTo (FrameBuffer & screen, const Rectangle< int > & area) const
指定された描画先にウィンドウの内容を描画する。
Definition at line 47 of file layer.cpp.
References pos_, anonymous_namespace{layer.cpp}::screen, and window_.
GetPosition()
Vector2D< int > Layer::GetPosition () const
レイヤーの原点座標を取得する。
Definition at line 24 of file layer.cpp.
References pos_.
GetWindow()
std::shared_ptr< Window > Layer::GetWindow () const
設定されたウィンドウを返す。
Definition at line 20 of file layer.cpp.
References window_.
Referenced by LayerManager::FindLayerByPosition().
ID()
unsigned int Layer::ID () const
このインスタンスのIDを返す。
Definition at line 11 of file layer.cpp.
References id_.
Referenced by LayerManager::FindLayer(), InitializeLayer(), and InitializeMouse().
IsDraggable()
bool Layer::IsDraggable () const
レイヤーがドラッグ移動可能ならtrueを返す。
Definition at line 33 of file layer.cpp.
References draggable_.
Move()
Layer & Layer::Move (Vector2D< int > pos)
レイヤーの位置情報を指定された絶対座標へと更新する。再描画はしない。
Definition at line 37 of file layer.cpp.
References pos_.
Referenced by InitializeLayer(), InitializeMainWindow(), InitializeTaskBWindow(), and InitializeTextWindow().
MoveRelative()
Layer & Layer::MoveRelative (Vector2D< int > pos_diff)
レイヤーの位置情報を指定された相対座標へと更新する。再描画はしない。
Definition at line 42 of file layer.cpp.
References pos_.
SetDraggable()
Layer & Layer::SetDraggable (bool draggable)
trueを設定するとレイヤーがドラッグ移動可能となる。
Definition at line 28 of file layer.cpp.
References draggable_.
Referenced by InitializeMainWindow(), InitializeTaskBWindow(), and InitializeTextWindow().
SetWindow()
Layer & Layer::SetWindow (const std::shared_ptr< Window > & window)
ウィンドウを設定する。既存のウィンドウはこのレイヤーから外れる。
Definition at line 15 of file layer.cpp.
References window_.
Referenced by InitializeLayer(), InitializeMainWindow(), InitializeMouse(), InitializeTaskBWindow(), and InitializeTextWindow().
Member Data Documentation
draggable_
bool Layer::draggable_ {false} private
Definition at line 51 of file layer.hpp.
Referenced by IsDraggable(), and SetDraggable().
id_
unsigned int Layer::id_ private
Definition at line 48 of file layer.hpp.
Referenced by ID().
pos_
Vector2D<int> Layer::pos_ private
Definition at line 49 of file layer.hpp.
Referenced by DrawTo(), GetPosition(), Move(), and MoveRelative().
window_
std::shared_ptr<Window> Layer::window_ private
Definition at line 50 of file layer.hpp.
Referenced by DrawTo(), GetWindow(), and SetWindow().
The documentation for this class was generated from the following files:
kernel/layer.hpp
kernel/layer.cpp