My Project: usb::xhci::DeviceManager Class Reference
usb::xhci::DeviceManager Class Reference
#include <devmgr.hpp>
Public Member Functions
Error Initialize (size_t max_slots)
DeviceContext ** DeviceContexts () const
Device * FindByPort (uint8_t port_num, uint32_t route_string) const
Device * FindByState (enum Device::State state) const
Device * FindBySlot (uint8_t slot_id) const
Error AllocDevice (uint8_t slot_id, DoorbellRegister *dbreg)
Error LoadDCBAA (uint8_t slot_id)
Error Remove (uint8_t slot_id)
Private Attributes
DeviceContext ** device_context_pointers_
size_t max_slots_
Device ** devices_
Detailed Description
Definition at line 17 of file devmgr.hpp.
Member Function Documentation
AllocDevice()
Error usb::xhci::DeviceManager::AllocDevice (uint8_t slot_id, DoorbellRegister * dbreg)
Definition at line 70 of file devmgr.cpp.
References devices_, Error::kAlreadyAllocated, Error::kInvalidSlotID, Error::kSuccess, MAKE_ERROR, max_slots_, and slot_id.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice().
DeviceContexts()
DeviceContext ** usb::xhci::DeviceManager::DeviceContexts () const
Definition at line 28 of file devmgr.cpp.
References device_context_pointers_.
Referenced by usb::xhci::Controller::Initialize().
FindByPort()
Device * usb::xhci::DeviceManager::FindByPort (uint8_t port_num, uint32_t route_string) const
Definition at line 32 of file devmgr.cpp.
References devices_, and max_slots_.
FindBySlot()
Device * usb::xhci::DeviceManager::FindBySlot (uint8_t slot_id) const
Definition at line 54 of file devmgr.cpp.
References devices_, max_slots_, and slot_id.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), anonymous_namespace{xhci.cpp}::CompleteConfiguration(), anonymous_namespace{xhci.cpp}::InitializeDevice(), and anonymous_namespace{xhci.cpp}::OnEvent().
FindByState()
Device * usb::xhci::DeviceManager::FindByState (enum Device::State state) const
Definition at line 43 of file devmgr.cpp.
References devices_, and max_slots_.
Initialize()
Error usb::xhci::DeviceManager::Initialize (size_t max_slots)
Definition at line 6 of file devmgr.cpp.
References device_context_pointers_, devices_, usb::FreeMem(), Error::kNoEnoughMemory, Error::kSuccess, MAKE_ERROR, and max_slots_.
Referenced by usb::xhci::Controller::Initialize().
LoadDCBAA()
Error usb::xhci::DeviceManager::LoadDCBAA (uint8_t slot_id)
Definition at line 84 of file devmgr.cpp.
References device_context_pointers_, devices_, Error::kInvalidSlotID, Error::kSuccess, MAKE_ERROR, max_slots_, and slot_id.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice().
Remove()
Error usb::xhci::DeviceManager::Remove (uint8_t slot_id)
Definition at line 94 of file devmgr.cpp.
References device_context_pointers_, devices_, usb::FreeMem(), Error::kSuccess, MAKE_ERROR, and slot_id.
Member Data Documentation
device_context_pointers_
DeviceContext** usb::xhci::DeviceManager::device_context_pointers_ private
Definition at line 33 of file devmgr.hpp.
Referenced by DeviceContexts(), Initialize(), LoadDCBAA(), and Remove().
devices_
Device** usb::xhci::DeviceManager::devices_ private
Definition at line 37 of file devmgr.hpp.
Referenced by AllocDevice(), FindByPort(), FindBySlot(), FindByState(), Initialize(), LoadDCBAA(), and Remove().
max_slots_
size_t usb::xhci::DeviceManager::max_slots_ private
Definition at line 34 of file devmgr.hpp.
Referenced by AllocDevice(), FindByPort(), FindBySlot(), FindByState(), Initialize(), and LoadDCBAA().
The documentation for this class was generated from the following files:
kernel/usb/xhci/devmgr.hpp
kernel/usb/xhci/devmgr.cpp