My Project: Task Class Reference
Task Class Reference
#include <task.hpp>
Public Member Functions
Task (uint64_t id)
Task & InitContext (TaskFunc *f, int64_t data)
TaskContext & Context ()
uint64_t ID () const
Task & Sleep ()
Task & Wakeup ()
void SendMessage (const Message &msg)
std::optional< Message > ReceiveMessage ()
Static Public Attributes
static const size_t kDefaultStackBytes = 4096
Private Attributes
uint64_t id_
std::vector< uint64_t > stack_
TaskContext context_
std::deque< Message > msgs_
Detailed Description
Definition at line 27 of file task.hpp.
Constructor & Destructor Documentation
Task()
Task::Task (uint64_t id)
Definition at line 7 of file task.cpp.
Member Function Documentation
Context()
TaskContext & Task::Context ()
Definition at line 31 of file task.cpp.
References context_.
Referenced by TaskManager::SwitchTask().
ID()
uint64_t Task::ID () const
Definition at line 35 of file task.cpp.
References id_.
Referenced by KernelMainNewStack().
InitContext()
Task & Task::InitContext (TaskFunc * f, int64_t data)
Definition at line 9 of file task.cpp.
References context_, TaskContext::cr3, TaskContext::cs, data, TaskContext::fxsave_area, GetCR3(), id_, kDefaultStackBytes, kKernelCS, kKernelSS, TaskContext::rdi, TaskContext::rflags, TaskContext::rip, TaskContext::rsi, TaskContext::rsp, TaskContext::ss, and stack_.
Referenced by KernelMainNewStack().
ReceiveMessage()
std::optional< Message > Task::ReceiveMessage ()
Definition at line 54 of file task.cpp.
References msgs_.
Referenced by KernelMainNewStack().
SendMessage()
void Task::SendMessage (const Message & msg)
Definition at line 49 of file task.cpp.
References msgs_, and Wakeup().
Sleep()
Task & Task::Sleep ()
Definition at line 39 of file task.cpp.
References TaskManager::Sleep(), and task_manager.
Referenced by KernelMainNewStack().
Wakeup()
Task & Task::Wakeup ()
Definition at line 44 of file task.cpp.
References task_manager, and TaskManager::Wakeup().
Referenced by KernelMainNewStack(), and SendMessage().
Member Data Documentation
context_
TaskContext Task::context_ private
Definition at line 43 of file task.hpp.
Referenced by Context(), and InitContext().
id_
uint64_t Task::id_ private
Definition at line 41 of file task.hpp.
Referenced by ID(), and InitContext().
kDefaultStackBytes
const size_t Task::kDefaultStackBytes = 4096 static
Definition at line 29 of file task.hpp.
Referenced by InitContext().
msgs_
std::deque<Message> Task::msgs_ private
Definition at line 44 of file task.hpp.
Referenced by ReceiveMessage(), and SendMessage().
stack_
std::vector<uint64_t> Task::stack_ private
Definition at line 42 of file task.hpp.
Referenced by InitContext().
The documentation for this class was generated from the following files:
kernel/task.hpp
kernel/task.cpp