My Project: Console Class Reference
Console Class Reference
#include <console.hpp>
Public Member Functions
Console (const PixelColor &fg_color, const PixelColor &bg_color)
void PutString (const char *s)
void SetWriter (PixelWriter *writer)
void SetWindow (const std::shared_ptr< Window > &window)
void SetLayerID (unsigned int layer_id)
unsigned int LayerID () const
Static Public Attributes
static const int kRows = 25
static const int kColumns = 80
Private Member Functions
void Newline ()
void Refresh ()
Private Attributes
PixelWriter * writer_
std::shared_ptr< Window > window_
const PixelColor fg_color_
const PixelColor bg_color_
char buffer_ [kRows][kColumns+1]
int cursor_row_
int cursor_column_
unsigned int layer_id_
Detailed Description
Definition at line 7 of file console.hpp.
Constructor & Destructor Documentation
Console()
Console::Console (const PixelColor & fg_color, const PixelColor & bg_color)
Definition at line 7 of file console.cpp.
Member Function Documentation
LayerID()
unsigned int Console::LayerID () const
Definition at line 50 of file console.cpp.
References layer_id_.
Referenced by InitializeLayer().
Newline()
void Console::Newline () private
Definition at line 55 of file console.cpp.
References bg_color_, buffer_, cursor_column_, cursor_row_, fg_color_, FillRectangle(), kColumns, kRows, window_, writer_, and WriteString().
Referenced by PutString().
PutString()
void Console::PutString (const char * s)
Definition at line 12 of file console.cpp.
References buffer_, cursor_column_, cursor_row_, LayerManager::Draw(), fg_color_, kColumns, layer_id_, layer_manager, Newline(), WriteAscii(), and writer_.
Referenced by Log(), and printk().
Refresh()
void Console::Refresh () private
Definition at line 77 of file console.cpp.
References bg_color_, buffer_, fg_color_, FillRectangle(), kColumns, kRows, writer_, and WriteString().
Referenced by SetWindow(), and SetWriter().
SetLayerID()
void Console::SetLayerID (unsigned int layer_id)
Definition at line 46 of file console.cpp.
References layer_id_.
Referenced by InitializeLayer().
SetWindow()
void Console::SetWindow (const std::shared_ptr< Window > & window)
Definition at line 37 of file console.cpp.
References Refresh(), window_, and writer_.
Referenced by InitializeLayer().
SetWriter()
void Console::SetWriter (PixelWriter * writer)
Definition at line 28 of file console.cpp.
References Refresh(), window_, and writer_.
Referenced by InitializeConsole().
Member Data Documentation
bg_color_
const PixelColor Console::bg_color_ private
Definition at line 24 of file console.hpp.
Referenced by Newline(), and Refresh().
buffer_
char Console::buffer_[kRows][kColumns+1] private
Definition at line 25 of file console.hpp.
Referenced by Newline(), PutString(), and Refresh().
cursor_column_
int Console::cursor_column_ private
Definition at line 26 of file console.hpp.
Referenced by Newline(), and PutString().
cursor_row_
int Console::cursor_row_ private
Definition at line 26 of file console.hpp.
Referenced by Newline(), and PutString().
fg_color_
const PixelColor Console::fg_color_ private
Definition at line 24 of file console.hpp.
Referenced by Newline(), PutString(), and Refresh().
kColumns
const int Console::kColumns = 80 static
Definition at line 9 of file console.hpp.
Referenced by InitializeLayer(), Newline(), PutString(), and Refresh().
kRows
const int Console::kRows = 25 static
Definition at line 9 of file console.hpp.
Referenced by InitializeLayer(), Newline(), and Refresh().
layer_id_
unsigned int Console::layer_id_ private
Definition at line 27 of file console.hpp.
Referenced by LayerID(), PutString(), and SetLayerID().
window_
std::shared_ptr<Window> Console::window_ private
Definition at line 23 of file console.hpp.
Referenced by Newline(), SetWindow(), and SetWriter().
writer_
PixelWriter* Console::writer_ private
Definition at line 22 of file console.hpp.
Referenced by Newline(), PutString(), Refresh(), SetWindow(), and SetWriter().
The documentation for this class was generated from the following files:
kernel/console.hpp
kernel/console.cpp