My Project: TimerManager Class Reference
TimerManager Class Reference
#include <timer.hpp>
Public Member Functions
TimerManager ()
void AddTimer (const Timer &timer)
bool Tick ()
unsigned long CurrentTick () const
Private Attributes
volatile unsigned long tick_ {0}
std::priority_queue< Timer > timers_ {}
Detailed Description
Definition at line 30 of file timer.hpp.
Constructor & Destructor Documentation
TimerManager()
TimerManager::TimerManager ()
Definition at line 49 of file timer.cpp.
References timers_.
Member Function Documentation
AddTimer()
void TimerManager::AddTimer (const Timer & timer)
Definition at line 53 of file timer.cpp.
References timers_.
Referenced by InitializeTask(), and KernelMainNewStack().
CurrentTick()
unsigned long TimerManager::CurrentTick () const inline
Definition at line 35 of file timer.hpp.
References tick_.
Referenced by InitializeTask(), and KernelMainNewStack().
Tick()
bool TimerManager::Tick ()
Definition at line 57 of file timer.cpp.
References kTaskTimerPeriod, kTaskTimerValue, Message::kTimerTimeout, TaskManager::SendMessage(), task_manager, tick_, and timers_.
Referenced by LAPICTimerOnInterrupt().
Member Data Documentation
tick_
volatile unsigned long TimerManager::tick_ {0} private
Definition at line 38 of file timer.hpp.
Referenced by CurrentTick(), and Tick().
timers_
std::priority_queue<Timer> TimerManager::timers_ {} private
Definition at line 39 of file timer.hpp.
Referenced by AddTimer(), Tick(), and TimerManager().
The documentation for this class was generated from the following files:
kernel/timer.hpp
kernel/timer.cpp