My Project: usb::xhci::Device Class Reference
usb::xhci::Device Class Reference
#include <device.hpp>
Public Types
enum State { State::kInvalid, State::kBlank, State::kSlotAssigning, State::kSlotAssigned }
using OnTransferredCallbackType = void(Device *dev, DeviceContextIndex dci, int completion_code, int trb_transfer_length, TRB *issue_trb)
Public Member Functions
Device (uint8_t slot_id, DoorbellRegister *dbreg)
Error Initialize ()
DeviceContext * DeviceContext ()
InputContext * InputContext ()
State State () const
uint8_t SlotID () const
void SelectForSlotAssignment ()
Ring * AllocTransferRing (DeviceContextIndex index, size_t buf_size)
Error ControlIn (EndpointID ep_id, SetupData setup_data, void *buf, int len, ClassDriver *issuer) override
Error ControlOut (EndpointID ep_id, SetupData setup_data, const void *buf, int len, ClassDriver *issuer) override
Error InterruptIn (EndpointID ep_id, void *buf, int len) override
Error InterruptOut (EndpointID ep_id, void *buf, int len) override
Error OnTransferEventReceived (const TransferEventTRB &trb)
Public Member Functions inherited from usb::Device
virtual ~Device ()
Error StartInitialize ()
bool IsInitialized ()
EndpointConfig * EndpointConfigs ()
int NumEndpointConfigs ()
Error OnEndpointsConfigured ()
uint8_t * Buffer ()
Private Attributes
struct DeviceContext ctx_
struct InputContext input_ctx_
const uint8_t slot_id_
DoorbellRegister *const dbreg_
enum State state_
std::array< Ring *, 31 > transfer_rings_
ArrayMap< const void *, const SetupStageTRB *, 16 > setup_stage_map_ {}
Additional Inherited Members
Protected Member Functions inherited from usb::Device
Error OnControlCompleted (EndpointID ep_id, SetupData setup_data, const void *buf, int len)
Error OnInterruptCompleted (EndpointID ep_id, const void *buf, int len)
Detailed Description
Definition at line 20 of file device.hpp.
Member Typedef Documentation
OnTransferredCallbackType
using usb::xhci::Device::OnTransferredCallbackType = void (Device* dev, DeviceContextIndex dci, int completion_code, int trb_transfer_length, TRB* issue_trb)
Definition at line 34 of file device.hpp.
Member Enumeration Documentation
State
enum usb::xhci::Device::State strong
Enumerator
kInvalid
kBlank
kSlotAssigning
kSlotAssigned
Definition at line 22 of file device.hpp.
Constructor & Destructor Documentation
Device()
usb::xhci::Device::Device (uint8_t slot_id, DoorbellRegister * dbreg)
Definition at line 80 of file device.cpp.
References slot_id.
Member Function Documentation
AllocTransferRing()
Ring * usb::xhci::Device::AllocTransferRing (DeviceContextIndex index, size_t buf_size)
Definition at line 97 of file device.cpp.
References index, and transfer_rings_.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), and usb::xhci::ConfigureEndpoints().
ControlIn()
Error usb::xhci::Device::ControlIn (EndpointID ep_id, SetupData setup_data, void * buf, int len, ClassDriver * issuer) override virtual
Reimplemented from usb::Device.
Definition at line 107 of file device.cpp.
References usb::EndpointID::Address(), usb::Device::ControlIn(), data, dbreg_, kDebug, usb::xhci::SetupStageTRB::kInDataStage, Error::kInvalidEndpointNumber, usb::xhci::SetupStageTRB::kNoDataStage, Error::kSuccess, Error::kTransferRingNotSet, anonymous_namespace{device.cpp}::Log(), MAKE_ERROR, anonymous_namespace{device.cpp}::MakeDataStageTRB(), anonymous_namespace{device.cpp}::MakeSetupStageTRB(), usb::EndpointID::Number(), usb::xhci::Ring::Push(), usb::xhci::DoorbellRegister::Ring(), setup_stage_map_, status, and transfer_rings_.
ControlOut()
Error usb::xhci::Device::ControlOut (EndpointID ep_id, SetupData setup_data, const void * buf, int len, ClassDriver * issuer) override virtual
Reimplemented from usb::Device.
Definition at line 154 of file device.cpp.
References usb::EndpointID::Address(), usb::Device::ControlOut(), data, dbreg_, kDebug, Error::kInvalidEndpointNumber, usb::xhci::SetupStageTRB::kNoDataStage, usb::xhci::SetupStageTRB::kOutDataStage, Error::kSuccess, Error::kTransferRingNotSet, anonymous_namespace{device.cpp}::Log(), MAKE_ERROR, anonymous_namespace{device.cpp}::MakeDataStageTRB(), anonymous_namespace{device.cpp}::MakeSetupStageTRB(), usb::EndpointID::Number(), usb::xhci::Ring::Push(), usb::xhci::DoorbellRegister::Ring(), setup_stage_map_, status, and transfer_rings_.
DeviceContext()
DeviceContext* usb::xhci::Device::DeviceContext () inline
Definition at line 40 of file device.hpp.
References ctx_.
Referenced by usb::xhci::ConfigureEndpoints().
Initialize()
Error usb::xhci::Device::Initialize ()
Definition at line 84 of file device.cpp.
References kBlank, Error::kSuccess, MAKE_ERROR, and state_.
InputContext()
InputContext* usb::xhci::Device::InputContext () inline
Definition at line 41 of file device.hpp.
References input_ctx_.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), and usb::xhci::ConfigureEndpoints().
InterruptIn()
Error usb::xhci::Device::InterruptIn (EndpointID ep_id, void * buf, int len) override virtual
Reimplemented from usb::Device.
Definition at line 201 of file device.cpp.
References dbreg_, usb::Device::InterruptIn(), Error::kSuccess, Error::kTransferRingNotSet, MAKE_ERROR, usb::xhci::Ring::Push(), usb::xhci::DoorbellRegister::Ring(), usb::xhci::NormalTRB::SetPointer(), and transfer_rings_.
InterruptOut()
Error usb::xhci::Device::InterruptOut (EndpointID ep_id, void * buf, int len) override virtual
Reimplemented from usb::Device.
Definition at line 225 of file device.cpp.
References usb::EndpointID::Address(), usb::Device::InterruptOut(), kDebug, Error::kNotImplemented, anonymous_namespace{device.cpp}::Log(), and MAKE_ERROR.
OnTransferEventReceived()
Error usb::xhci::Device::OnTransferEventReceived (const TransferEventTRB & trb)
Definition at line 235 of file device.cpp.
References usb::xhci::TransferEventTRB::completion_code, usb::SetupData::data, usb::xhci::TransferEventTRB::EndpointID(), kDebug, Error::kNoCorrespondingSetupStage, Error::kNotImplemented, Error::kTransferFailed, usb::xhci::kTRBTypeToName, anonymous_namespace{device.cpp}::Log(), MAKE_ERROR, usb::Device::OnControlCompleted(), usb::Device::OnInterruptCompleted(), usb::xhci::TransferEventTRB::Pointer(), usb::SetupData::request_type, setup_stage_map_, usb::xhci::TransferEventTRB::trb_transfer_length, and usb::xhci::TRB::trb_type.
SelectForSlotAssignment()
void usb::xhci::Device::SelectForSlotAssignment ()
Definition at line 93 of file device.cpp.
References kSlotAssigning, and state_.
SlotID()
uint8_t usb::xhci::Device::SlotID () const inline
Definition at line 46 of file device.hpp.
References slot_id_.
Referenced by usb::xhci::ConfigureEndpoints().
State()
State usb::xhci::Device::State () const inline
Definition at line 45 of file device.hpp.
References state_.
Member Data Documentation
ctx_
struct DeviceContext usb::xhci::Device::ctx_ private
Definition at line 61 of file device.hpp.
Referenced by DeviceContext().
dbreg_
DoorbellRegister* const usb::xhci::Device::dbreg_ private
Definition at line 65 of file device.hpp.
Referenced by ControlIn(), ControlOut(), and InterruptIn().
input_ctx_
struct InputContext usb::xhci::Device::input_ctx_ private
Definition at line 62 of file device.hpp.
Referenced by InputContext().
setup_stage_map_
ArrayMap<const void*, const SetupStageTRB*, 16> usb::xhci::Device::setup_stage_map_ {} private
コントロール転送が完了した際に DataStageTRB や StatusStageTRB から対応する SetupStageTRB を検索するためのマップ．
Definition at line 73 of file device.hpp.
Referenced by ControlIn(), ControlOut(), and OnTransferEventReceived().
slot_id_
const uint8_t usb::xhci::Device::slot_id_ private
Definition at line 64 of file device.hpp.
Referenced by SlotID().
state_
enum State usb::xhci::Device::state_ private
Definition at line 67 of file device.hpp.
Referenced by Initialize(), SelectForSlotAssignment(), and State().
transfer_rings_
std::array<Ring*, 31> usb::xhci::Device::transfer_rings_ private
Definition at line 68 of file device.hpp.
Referenced by AllocTransferRing(), ControlIn(), ControlOut(), and InterruptIn().
The documentation for this class was generated from the following files:
kernel/usb/xhci/device.hpp
kernel/usb/xhci/device.cpp