My Project: usb::HIDBaseDriver Class Reference
usb::HIDBaseDriver Class Reference abstract
#include <hid.hpp>
Public Member Functions
HIDBaseDriver (Device *dev, int interface_index, int in_packet_size)
Error Initialize () override
Error SetEndpoint (const EndpointConfig &config) override
Error OnEndpointsConfigured () override
Error OnControlCompleted (EndpointID ep_id, SetupData setup_data, const void *buf, int len) override
Error OnInterruptCompleted (EndpointID ep_id, const void *buf, int len) override
virtual Error OnDataReceived ()=0
const std::array< uint8_t, kBufferSize > & Buffer () const
const std::array< uint8_t, kBufferSize > & PreviousBuffer () const
Public Member Functions inherited from usb::ClassDriver
ClassDriver (Device *dev)
virtual ~ClassDriver ()
Device * ParentDevice () const
Static Public Attributes
const static size_t kBufferSize = 1024
Private Attributes
EndpointID ep_interrupt_in_
EndpointID ep_interrupt_out_
const int interface_index_
int in_packet_size_
int initialize_phase_ {0}
std::array< uint8_t, kBufferSize > buf_ {}
std::array< uint8_t, kBufferSize > previous_buf_ {}
Detailed Description
Definition at line 12 of file hid.hpp.
Constructor & Destructor Documentation
HIDBaseDriver()
usb::HIDBaseDriver::HIDBaseDriver (Device * dev, int interface_index, int in_packet_size)
Definition at line 8 of file hid.cpp.
Member Function Documentation
Buffer()
const std::array<uint8_t, kBufferSize>& usb::HIDBaseDriver::Buffer () const inline
Definition at line 24 of file hid.hpp.
References buf_.
Referenced by usb::HIDKeyboardDriver::OnDataReceived(), and usb::HIDMouseDriver::OnDataReceived().
Initialize()
Error usb::HIDBaseDriver::Initialize () override virtual
Implements usb::ClassDriver.
Definition at line 14 of file hid.cpp.
References Error::kNotImplemented, and MAKE_ERROR.
OnControlCompleted()
Error usb::HIDBaseDriver::OnControlCompleted (EndpointID ep_id, SetupData setup_data, const void * buf, int len) override virtual
Implements usb::ClassDriver.
Definition at line 41 of file hid.cpp.
References buf_, ep_interrupt_in_, in_packet_size_, initialize_phase_, usb::Device::InterruptIn(), kDebug, Error::kNotImplemented, Log(), MAKE_ERROR, and usb::ClassDriver::ParentDevice().
OnDataReceived()
virtual Error usb::HIDBaseDriver::OnDataReceived () pure virtual
Implemented in usb::HIDKeyboardDriver, and usb::HIDMouseDriver.
Referenced by OnInterruptCompleted().
OnEndpointsConfigured()
Error usb::HIDBaseDriver::OnEndpointsConfigured () override virtual
Implements usb::ClassDriver.
Definition at line 27 of file hid.cpp.
References usb::SetupData::bits, usb::Device::ControlOut(), initialize_phase_, interface_index_, usb::request_type::kClass, usb::kDefaultControlPipeID, usb::request_type::kInterface, usb::request_type::kOut, usb::request::kSetProtocol, usb::ClassDriver::ParentDevice(), and usb::SetupData::request_type.
OnInterruptCompleted()
Error usb::HIDBaseDriver::OnInterruptCompleted (EndpointID ep_id, const void * buf, int len) override virtual
Implements usb::ClassDriver.
Definition at line 53 of file hid.cpp.
References buf_, ep_interrupt_in_, in_packet_size_, usb::Device::InterruptIn(), usb::EndpointID::IsIn(), Error::kNotImplemented, MAKE_ERROR, OnDataReceived(), usb::ClassDriver::ParentDevice(), and previous_buf_.
PreviousBuffer()
const std::array<uint8_t, kBufferSize>& usb::HIDBaseDriver::PreviousBuffer () const inline
Definition at line 25 of file hid.hpp.
References previous_buf_.
Referenced by usb::HIDKeyboardDriver::OnDataReceived().
SetEndpoint()
Error usb::HIDBaseDriver::SetEndpoint (const EndpointConfig & config) override virtual
Implements usb::ClassDriver.
Definition at line 18 of file hid.cpp.
References usb::EndpointConfig::ep_id, ep_interrupt_in_, ep_interrupt_out_, usb::EndpointConfig::ep_type, usb::EndpointID::IsIn(), usb::kInterrupt, Error::kSuccess, and MAKE_ERROR.
Member Data Documentation
buf_
std::array<uint8_t, kBufferSize> usb::HIDBaseDriver::buf_ {} private
Definition at line 34 of file hid.hpp.
Referenced by Buffer(), OnControlCompleted(), and OnInterruptCompleted().
ep_interrupt_in_
EndpointID usb::HIDBaseDriver::ep_interrupt_in_ private
Definition at line 28 of file hid.hpp.
Referenced by OnControlCompleted(), OnInterruptCompleted(), and SetEndpoint().
ep_interrupt_out_
EndpointID usb::HIDBaseDriver::ep_interrupt_out_ private
Definition at line 29 of file hid.hpp.
Referenced by SetEndpoint().
in_packet_size_
int usb::HIDBaseDriver::in_packet_size_ private
Definition at line 31 of file hid.hpp.
Referenced by OnControlCompleted(), and OnInterruptCompleted().
initialize_phase_
int usb::HIDBaseDriver::initialize_phase_ {0} private
Definition at line 32 of file hid.hpp.
Referenced by OnControlCompleted(), and OnEndpointsConfigured().
interface_index_
const int usb::HIDBaseDriver::interface_index_ private
Definition at line 30 of file hid.hpp.
Referenced by OnEndpointsConfigured().
kBufferSize
const static size_t usb::HIDBaseDriver::kBufferSize = 1024 static
Definition at line 23 of file hid.hpp.
previous_buf_
std::array<uint8_t, kBufferSize> usb::HIDBaseDriver::previous_buf_ {} private
Definition at line 34 of file hid.hpp.
Referenced by OnInterruptCompleted(), and PreviousBuffer().
The documentation for this class was generated from the following files:
kernel/usb/classdriver/hid.hpp
kernel/usb/classdriver/hid.cpp