My Project: Window::WindowWriter Class Reference
Window::WindowWriter Class Reference
WindowWriterはWindowと関連付けられたPixelWriterを提供する。
#include <window.hpp>
Public Member Functions
WindowWriter (Window &window)
virtual void Write (Vector2D< int > pos, const PixelColor &c) override
指定された位置に指定された色を描く
virtual int Width () const override
virtual int Height () const override
Heightは関連付けられたWindowの高さをピクセル単位で返す。
Public Member Functions inherited from PixelWriter
virtual ~PixelWriter ()=default
Private Attributes
Window & window_
Detailed Description
WindowWriterはWindowと関連付けられたPixelWriterを提供する。
Definition at line 22 of file window.hpp.
Constructor & Destructor Documentation
WindowWriter()
Window::WindowWriter::WindowWriter (Window & window) inline
Definition at line 24 of file window.hpp.
Member Function Documentation
Height()
virtual int Window::WindowWriter::Height () const inline override virtual
Heightは関連付けられたWindowの高さをピクセル単位で返す。
Implements PixelWriter.
Definition at line 32 of file window.hpp.
References Window::Height(), and window_.
Width()
virtual int Window::WindowWriter::Width () const inline override virtual
@breif Widthは関連付けられたWindowの横幅をピクセル単位で返す。
Implements PixelWriter.
Definition at line 30 of file window.hpp.
References Window::Width(), and window_.
Write()
virtual void Window::WindowWriter::Write (Vector2D< int > pos, const PixelColor & c) inline override virtual
指定された位置に指定された色を描く
Implements PixelWriter.
Definition at line 26 of file window.hpp.
References window_, and Window::Write().
Member Data Documentation
window_
Window& Window::WindowWriter::window_ private
Definition at line 35 of file window.hpp.
Referenced by Height(), Width(), and Write().
The documentation for this class was generated from the following file:
kernel/window.hpp