My Project: usb::xhci::EventRing Class Reference
usb::xhci::EventRing Class Reference
#include <ring.hpp>
Public Member Functions
Error Initialize (size_t buf_size, InterrupterRegisterSet *interrupter)
TRB * ReadDequeuePointer () const
void WriteDequeuePointer (TRB *p)
bool HasFront () const
TRB * Front () const
void Pop ()
Private Attributes
TRB * buf_
size_t buf_size_
bool cycle_bit_
EventRingSegmentTableEntry * erst_
InterrupterRegisterSet * interrupter_
Detailed Description
Definition at line 78 of file ring.hpp.
Member Function Documentation
Front()
TRB* usb::xhci::EventRing::Front () const inline
Definition at line 92 of file ring.hpp.
References ReadDequeuePointer().
Referenced by HasFront(), and usb::xhci::ProcessEvent().
HasFront()
bool usb::xhci::EventRing::HasFront () const inline
Definition at line 88 of file ring.hpp.
References usb::xhci::TRB::cycle_bit, cycle_bit_, and Front().
Referenced by usb::xhci::ProcessEvent(), and usb::xhci::ProcessEvents().
Initialize()
Error usb::xhci::EventRing::Initialize (size_t buf_size, InterrupterRegisterSet * interrupter)
Definition at line 56 of file ring.cpp.
References buf_, buf_size_, cycle_bit_, erst_, usb::xhci::InterrupterRegisterSet::ERSTBA, usb::xhci::InterrupterRegisterSet::ERSTSZ, usb::FreeMem(), interrupter_, Error::kNoEnoughMemory, Error::kSuccess, MAKE_ERROR, usb::xhci::EventRingSegmentTableEntry::ring_segment_base_address, usb::xhci::EventRingSegmentTableEntry::ring_segment_size, usb::xhci::ERSTBA_Bitmap::SetPointer(), usb::xhci::ERSTSZ_Bitmap::SetSize(), and WriteDequeuePointer().
Referenced by usb::xhci::Controller::Initialize().
Pop()
void usb::xhci::EventRing::Pop ()
Definition at line 101 of file ring.cpp.
References cycle_bit_, erst_, ReadDequeuePointer(), usb::xhci::EventRingSegmentTableEntry::ring_segment_base_address, usb::xhci::EventRingSegmentTableEntry::ring_segment_size, and WriteDequeuePointer().
Referenced by usb::xhci::ProcessEvent().
ReadDequeuePointer()
TRB* usb::xhci::EventRing::ReadDequeuePointer () const inline
Definition at line 82 of file ring.hpp.
References usb::xhci::InterrupterRegisterSet::ERDP, and interrupter_.
Referenced by Front(), and Pop().
WriteDequeuePointer()
void usb::xhci::EventRing::WriteDequeuePointer (TRB * p)
Definition at line 95 of file ring.cpp.
References usb::xhci::InterrupterRegisterSet::ERDP, and interrupter_.
Referenced by Initialize(), and Pop().
Member Data Documentation
buf_
TRB* usb::xhci::EventRing::buf_ private
Definition at line 99 of file ring.hpp.
Referenced by Initialize().
buf_size_
size_t usb::xhci::EventRing::buf_size_ private
Definition at line 100 of file ring.hpp.
Referenced by Initialize().
cycle_bit_
bool usb::xhci::EventRing::cycle_bit_ private
Definition at line 102 of file ring.hpp.
Referenced by HasFront(), Initialize(), and Pop().
erst_
EventRingSegmentTableEntry* usb::xhci::EventRing::erst_ private
Definition at line 103 of file ring.hpp.
Referenced by Initialize(), and Pop().
interrupter_
InterrupterRegisterSet* usb::xhci::EventRing::interrupter_ private
Definition at line 104 of file ring.hpp.
Referenced by Initialize(), ReadDequeuePointer(), and WriteDequeuePointer().
The documentation for this class was generated from the following files:
kernel/usb/xhci/ring.hpp
kernel/usb/xhci/ring.cpp