My Project: usb::HIDKeyboardDriver Class Reference
usb::HIDKeyboardDriver Class Reference
#include <keyboard.hpp>
Public Types
using ObserverType = void(uint8_t modifier, uint8_t keycode)
Public Member Functions
HIDKeyboardDriver (Device *dev, int interface_index)
void * operator new (size_t size)
void operator delete (void *ptr) noexcept
Error OnDataReceived () override
void SubscribeKeyPush (std::function< ObserverType > observer)
Public Member Functions inherited from usb::HIDBaseDriver
HIDBaseDriver (Device *dev, int interface_index, int in_packet_size)
Error Initialize () override
Error SetEndpoint (const EndpointConfig &config) override
Error OnEndpointsConfigured () override
Error OnControlCompleted (EndpointID ep_id, SetupData setup_data, const void *buf, int len) override
Error OnInterruptCompleted (EndpointID ep_id, const void *buf, int len) override
const std::array< uint8_t, kBufferSize > & Buffer () const
const std::array< uint8_t, kBufferSize > & PreviousBuffer () const
Public Member Functions inherited from usb::ClassDriver
ClassDriver (Device *dev)
virtual ~ClassDriver ()
Device * ParentDevice () const
Static Public Attributes
static std::function< ObserverType > default_observer
Static Public Attributes inherited from usb::HIDBaseDriver
const static size_t kBufferSize = 1024
Private Member Functions
void NotifyKeyPush (uint8_t modifier, uint8_t keycode)
Private Attributes
std::array< std::function< ObserverType >, 4 > observers_
int num_observers_ = 0
Detailed Description
Definition at line 13 of file keyboard.hpp.
Member Typedef Documentation
ObserverType
using usb::HIDKeyboardDriver::ObserverType = void (uint8_t modifier, uint8_t keycode)
Definition at line 22 of file keyboard.hpp.
Constructor & Destructor Documentation
HIDKeyboardDriver()
usb::HIDKeyboardDriver::HIDKeyboardDriver (Device * dev, int interface_index)
Definition at line 8 of file keyboard.cpp.
Member Function Documentation
NotifyKeyPush()
void usb::HIDKeyboardDriver::NotifyKeyPush (uint8_t modifier, uint8_t keycode) private
Definition at line 42 of file keyboard.cpp.
References num_observers_, and observers_.
Referenced by OnDataReceived().
OnDataReceived()
Error usb::HIDKeyboardDriver::OnDataReceived () override virtual
Implements usb::HIDBaseDriver.
Definition at line 12 of file keyboard.cpp.
References usb::HIDBaseDriver::Buffer(), Error::kSuccess, MAKE_ERROR, NotifyKeyPush(), and usb::HIDBaseDriver::PreviousBuffer().
operator delete()
void usb::HIDKeyboardDriver::operator delete (void * ptr) noexcept
Definition at line 31 of file keyboard.cpp.
References usb::FreeMem().
operator new()
void * usb::HIDKeyboardDriver::operator new (size_t size)
Definition at line 27 of file keyboard.cpp.
References usb::AllocMem().
SubscribeKeyPush()
void usb::HIDKeyboardDriver::SubscribeKeyPush (std::function< ObserverType > observer)
Definition at line 35 of file keyboard.cpp.
References num_observers_, and observers_.
Member Data Documentation
default_observer
std::function< HIDKeyboardDriver::ObserverType > usb::HIDKeyboardDriver::default_observer static
Definition at line 24 of file keyboard.hpp.
Referenced by InitializeKeyboard(), and anonymous_namespace{device.cpp}::NewClassDriver().
num_observers_
int usb::HIDKeyboardDriver::num_observers_ = 0 private
Definition at line 28 of file keyboard.hpp.
Referenced by NotifyKeyPush(), and SubscribeKeyPush().
observers_
std::array<std::function<ObserverType>, 4> usb::HIDKeyboardDriver::observers_ private
Definition at line 27 of file keyboard.hpp.
Referenced by NotifyKeyPush(), and SubscribeKeyPush().
The documentation for this class was generated from the following files:
kernel/usb/classdriver/keyboard.hpp
kernel/usb/classdriver/keyboard.cpp