My Project: Window Class Reference
Window Class Reference
Windowクラスはグラフィックの表示領域を表す。
#include <window.hpp>
Classes
class WindowWriter
WindowWriterはWindowと関連付けられたPixelWriterを提供する。
Public Member Functions
Window (int width, int height, PixelFormat shadow_format)
指定されたピクセル数の平面描画領域を作成する。
~Window ()=default
Window (const Window &rhs)=delete
Window & operator= (const Window &rhs)=delete
void DrawTo (FrameBuffer &dst, Vector2D< int > pos, const Rectangle< int > &area)
与えられたFrameBufferにこのウィンドウの表示領域を描画する。
void SetTransparentColor (std::optional< PixelColor > c)
透過色を設定する。
WindowWriter * Writer ()
このインスタンスに紐づいたWindowWriterを取得する。
const PixelColor & At (int x, int y) const
指定した位置のピクセルを返す。
void Write (Vector2D< int > pos, PixelColor c)
指定した位置にピクセルを書き込む。
int Width () const
平面描画領域の横幅をピクセル単位で表す。
int Height () const
平面描画領域の高さをピクセル単位で表す。
Vector2D< int > Size () const
平面描画領域のサイズをピクセル単位で返す。
void Move (Vector2D< int > dst_pos, const Rectangle< int > &src)
このウィンドウの平面描画領域内で、矩形領域を移動する。
Private Attributes
int width_
int height_
std::vector< std::vector< PixelColor > > data_ {}
WindowWriter writer_ {*this}
std::optional< PixelColor > transparent_color_ {std::nullopt}
FrameBuffer shadow_buffer_ {}
Detailed Description
Windowクラスはグラフィックの表示領域を表す。
タイトルやメニューがあるウィンドウだけでなく、マウスカーソルの表示領域等も対象とする。
Definition at line 18 of file window.hpp.
Constructor & Destructor Documentation
Window() [1/2]
Window::Window (int width, int height, PixelFormat shadow_format)
指定されたピクセル数の平面描画領域を作成する。
Definition at line 7 of file window.cpp.
~Window()
Window::~Window () default
Window() [2/2]
Window::Window (const Window & rhs) delete
Member Function Documentation
At()
const PixelColor & Window::At (int x, int y) const
指定した位置のピクセルを返す。
Definition at line 57 of file window.cpp.
References data_.
Referenced by DrawTo().
DrawTo()
void Window::DrawTo (FrameBuffer & dst, Vector2D< int > pos, const Rectangle< int > & area)
与えられたFrameBufferにこのウィンドウの表示領域を描画する。
Parameters
dst 描画先
position writerの左上を基準とした描画位置
Definition at line 25 of file window.cpp.
References At(), FrameBuffer::Copy(), Height(), Rectangle< T >::pos, shadow_buffer_, Size(), transparent_color_, Width(), FrameBuffer::Writer(), Vector2D< T >::x, and Vector2D< T >::y.
Height()
int Window::Height () const
平面描画領域の高さをピクセル単位で表す。
Definition at line 70 of file window.cpp.
References height_.
Referenced by DrawTo(), and Window::WindowWriter::Height().
Move()
void Window::Move (Vector2D< int > dst_pos, const Rectangle< int > & src)
このウィンドウの平面描画領域内で、矩形領域を移動する。
Parameters
dst_pos 移動先の原点
src 移動元矩形の大きさ
Definition at line 79 of file window.cpp.
References FrameBuffer::Move(), and shadow_buffer_.
operator=()
Window& Window::operator= (const Window & rhs) delete
SetTransparentColor()
void Window::SetTransparentColor (std::optional< PixelColor > c)
透過色を設定する。
Definition at line 49 of file window.cpp.
References transparent_color_.
Size()
Vector2D< int > Window::Size () const
平面描画領域のサイズをピクセル単位で返す。
Definition at line 74 of file window.cpp.
References height_, and width_.
Referenced by DrawTo().
Width()
int Window::Width () const
平面描画領域の横幅をピクセル単位で表す。
Definition at line 66 of file window.cpp.
References width_.
Referenced by DrawTo(), and Window::WindowWriter::Width().
Write()
void Window::Write (Vector2D< int > pos, PixelColor c)
指定した位置にピクセルを書き込む。
Definition at line 61 of file window.cpp.
References data_, shadow_buffer_, PixelWriter::Write(), FrameBuffer::Writer(), Vector2D< T >::x, and Vector2D< T >::y.
Referenced by Window::WindowWriter::Write().
Writer()
Window::WindowWriter * Window::Writer ()
このインスタンスに紐づいたWindowWriterを取得する。
Definition at line 53 of file window.cpp.
References writer_.
Member Data Documentation
data_
std::vector<std::vector<PixelColor> > Window::data_ {} private
Definition at line 76 of file window.hpp.
Referenced by At(), and Write().
height_
int Window::height_ private
Definition at line 75 of file window.hpp.
Referenced by Height(), and Size().
shadow_buffer_
FrameBuffer Window::shadow_buffer_ {} private
Definition at line 80 of file window.hpp.
Referenced by DrawTo(), Move(), and Write().
transparent_color_
std::optional<PixelColor> Window::transparent_color_ {std::nullopt} private
Definition at line 78 of file window.hpp.
Referenced by DrawTo(), and SetTransparentColor().
width_
int Window::width_ private
Definition at line 75 of file window.hpp.
Referenced by Size(), and Width().
writer_
WindowWriter Window::writer_ {*this} private
Definition at line 77 of file window.hpp.
Referenced by Writer().
The documentation for this class was generated from the following files:
kernel/window.hpp
kernel/window.cpp