My Project: usb::Device Class Reference
usb::Device Class Reference
#include <device.hpp>
Public Member Functions
virtual ~Device ()
virtual Error ControlIn (EndpointID ep_id, SetupData setup_data, void *buf, int len, ClassDriver *issuer)
virtual Error ControlOut (EndpointID ep_id, SetupData setup_data, const void *buf, int len, ClassDriver *issuer)
virtual Error InterruptIn (EndpointID ep_id, void *buf, int len)
virtual Error InterruptOut (EndpointID ep_id, void *buf, int len)
Error StartInitialize ()
bool IsInitialized ()
EndpointConfig * EndpointConfigs ()
int NumEndpointConfigs ()
Error OnEndpointsConfigured ()
uint8_t * Buffer ()
Protected Member Functions
Error OnControlCompleted (EndpointID ep_id, SetupData setup_data, const void *buf, int len)
Error OnInterruptCompleted (EndpointID ep_id, const void *buf, int len)
Private Member Functions
Error OnDeviceDescriptorReceived (const uint8_t *buf, int len)
Error OnConfigurationDescriptorReceived (const uint8_t *buf, int len)
Error OnSetConfigurationCompleted (uint8_t config_value)
Error InitializePhase1 (const uint8_t *buf, int len)
Error InitializePhase2 (const uint8_t *buf, int len)
Error InitializePhase3 (uint8_t config_value)
Error InitializePhase4 ()
Private Attributes
std::array< ClassDriver *, 16 > class_drivers_ {}
エンドポイントに割り当て済みのクラスドライバ．
std::array< uint8_t, 256 > buf_ {}
uint8_t num_configurations_
uint8_t config_index_
bool is_initialized_ = false
int initialize_phase_ = 0
std::array< EndpointConfig, 16 > ep_configs_
int num_ep_configs_
ArrayMap< SetupData, ClassDriver *, 4 > event_waiters_ {}
Detailed Description
Definition at line 19 of file device.hpp.
Constructor & Destructor Documentation
~Device()
usb::Device::~Device () virtual
Definition at line 104 of file device.cpp.
Member Function Documentation
Buffer()
uint8_t* usb::Device::Buffer () inline
Definition at line 35 of file device.hpp.
References buf_.
ControlIn()
Error usb::Device::ControlIn (EndpointID ep_id, SetupData setup_data, void * buf, int len, ClassDriver * issuer) virtual
Reimplemented in usb::xhci::Device.
Definition at line 107 of file device.cpp.
References event_waiters_, Error::kSuccess, and MAKE_ERROR.
Referenced by usb::xhci::Device::ControlIn(), and usb::GetDescriptor().
ControlOut()
Error usb::Device::ControlOut (EndpointID ep_id, SetupData setup_data, const void * buf, int len, ClassDriver * issuer) virtual
Reimplemented in usb::xhci::Device.
Definition at line 115 of file device.cpp.
References event_waiters_, Error::kSuccess, and MAKE_ERROR.
Referenced by usb::xhci::Device::ControlOut(), usb::HIDBaseDriver::OnEndpointsConfigured(), and usb::SetConfiguration().
EndpointConfigs()
EndpointConfig* usb::Device::EndpointConfigs () inline
Definition at line 31 of file device.hpp.
References ep_configs_.
Referenced by usb::xhci::ConfigureEndpoints().
InitializePhase1()
Error usb::Device::InitializePhase1 (const uint8_t * buf, int len) private
Definition at line 191 of file device.cpp.
References buf_, config_index_, usb::GetDescriptor(), initialize_phase_, kDebug, usb::kDefaultControlPipeID, usb::ConfigurationDescriptor::kType, anonymous_namespace{device.cpp}::Log(), and num_configurations_.
Referenced by OnControlCompleted().
InitializePhase2()
Error usb::Device::InitializePhase2 (const uint8_t * buf, int len) private
Definition at line 202 of file device.cpp.
References class_drivers_, ep_configs_, initialize_phase_, kDebug, usb::kDefaultControlPipeID, Error::kInvalidDescriptor, Error::kSuccess, anonymous_namespace{device.cpp}::Log(), MAKE_ERROR, anonymous_namespace{device.cpp}::MakeEPConfig(), anonymous_namespace{device.cpp}::NewClassDriver(), num_endpoints, num_ep_configs_, and usb::SetConfiguration().
Referenced by OnControlCompleted().
InitializePhase3()
Error usb::Device::InitializePhase3 (uint8_t config_value) private
Definition at line 248 of file device.cpp.
References class_drivers_, ep_configs_, initialize_phase_, is_initialized_, Error::kSuccess, MAKE_ERROR, and num_ep_configs_.
Referenced by OnControlCompleted().
InitializePhase4()
Error usb::Device::InitializePhase4 () private
InterruptIn()
Error usb::Device::InterruptIn (EndpointID ep_id, void * buf, int len) virtual
Reimplemented in usb::xhci::Device.
Definition at line 123 of file device.cpp.
References Error::kSuccess, and MAKE_ERROR.
Referenced by usb::xhci::Device::InterruptIn(), usb::HIDBaseDriver::OnControlCompleted(), and usb::HIDBaseDriver::OnInterruptCompleted().
InterruptOut()
Error usb::Device::InterruptOut (EndpointID ep_id, void * buf, int len) virtual
Reimplemented in usb::xhci::Device.
Definition at line 127 of file device.cpp.
References Error::kSuccess, and MAKE_ERROR.
Referenced by usb::xhci::Device::InterruptOut().
IsInitialized()
bool usb::Device::IsInitialized () inline
Definition at line 30 of file device.hpp.
References is_initialized_.
NumEndpointConfigs()
int usb::Device::NumEndpointConfigs () inline
Definition at line 32 of file device.hpp.
References num_ep_configs_.
Referenced by usb::xhci::ConfigureEndpoints().
OnConfigurationDescriptorReceived()
Error usb::Device::OnConfigurationDescriptorReceived (const uint8_t * buf, int len) private
OnControlCompleted()
Error usb::Device::OnControlCompleted (EndpointID ep_id, SetupData setup_data, const void * buf, int len) protected
Definition at line 149 of file device.cpp.
References usb::SetupData::bits, event_waiters_, initialize_phase_, InitializePhase1(), InitializePhase2(), InitializePhase3(), is_initialized_, kDebug, usb::request::kGetDescriptor, Error::kInvalidPhase, Error::kNotImplemented, Error::kNoWaiter, usb::request::kSetConfiguration, anonymous_namespace{device.cpp}::Log(), MAKE_ERROR, usb::SetupData::request, usb::SetupData::request_type, and usb::SetupData::value.
Referenced by usb::xhci::Device::OnTransferEventReceived().
OnDeviceDescriptorReceived()
Error usb::Device::OnDeviceDescriptorReceived (const uint8_t * buf, int len) private
OnEndpointsConfigured()
Error usb::Device::OnEndpointsConfigured ()
Definition at line 138 of file device.cpp.
References class_drivers_, Error::kSuccess, and MAKE_ERROR.
OnInterruptCompleted()
Error usb::Device::OnInterruptCompleted (EndpointID ep_id, const void * buf, int len) protected
Definition at line 183 of file device.cpp.
References usb::EndpointID::Address(), class_drivers_, kDebug, Error::kNoWaiter, anonymous_namespace{device.cpp}::Log(), MAKE_ERROR, and usb::EndpointID::Number().
Referenced by usb::xhci::Device::OnTransferEventReceived().
OnSetConfigurationCompleted()
Error usb::Device::OnSetConfigurationCompleted (uint8_t config_value) private
StartInitialize()
Error usb::Device::StartInitialize ()
Definition at line 131 of file device.cpp.
References buf_, usb::GetDescriptor(), initialize_phase_, is_initialized_, usb::kDefaultControlPipeID, and usb::DeviceDescriptor::kType.
Member Data Documentation
buf_
std::array<uint8_t, 256> usb::Device::buf_ {} private
Definition at line 50 of file device.hpp.
Referenced by Buffer(), InitializePhase1(), and StartInitialize().
class_drivers_
std::array<ClassDriver*, 16> usb::Device::class_drivers_ {} private
エンドポイントに割り当て済みのクラスドライバ．
添字はエンドポイント番号（0 - 15）． 添字 0 はどのクラスドライバからも使われないため，常に未使用．
Definition at line 48 of file device.hpp.
Referenced by InitializePhase2(), InitializePhase3(), OnEndpointsConfigured(), and OnInterruptCompleted().
config_index_
uint8_t usb::Device::config_index_ private
Definition at line 54 of file device.hpp.
Referenced by InitializePhase1().
ep_configs_
std::array<EndpointConfig, 16> usb::Device::ep_configs_ private
Definition at line 62 of file device.hpp.
Referenced by EndpointConfigs(), InitializePhase2(), and InitializePhase3().
event_waiters_
ArrayMap<SetupData, ClassDriver*, 4> usb::Device::event_waiters_ {} private
OnControlCompleted の中で要求の発行元を特定するためのマップ構造． ControlOut または ControlIn を発行したときに発行元が登録される．
Definition at line 72 of file device.hpp.
Referenced by ControlIn(), ControlOut(), and OnControlCompleted().
initialize_phase_
int usb::Device::initialize_phase_ = 0 private
Definition at line 61 of file device.hpp.
Referenced by InitializePhase1(), InitializePhase2(), InitializePhase3(), OnControlCompleted(), and StartInitialize().
is_initialized_
bool usb::Device::is_initialized_ = false private
Definition at line 60 of file device.hpp.
Referenced by InitializePhase3(), IsInitialized(), OnControlCompleted(), and StartInitialize().
num_configurations_
uint8_t usb::Device::num_configurations_ private
Definition at line 53 of file device.hpp.
Referenced by InitializePhase1().
num_ep_configs_
int usb::Device::num_ep_configs_ private
Definition at line 63 of file device.hpp.
Referenced by InitializePhase2(), InitializePhase3(), and NumEndpointConfigs().
The documentation for this class was generated from the following files:
kernel/usb/device.hpp
kernel/usb/device.cpp