My Project: usb::xhci::Controller Class Reference
usb::xhci::Controller Class Reference
#include <xhci.hpp>
Public Member Functions
Controller (uintptr_t mmio_base)
Error Initialize ()
Error Run ()
Ring * CommandRing ()
EventRing * PrimaryEventRing ()
DoorbellRegister * DoorbellRegisterAt (uint8_t index)
Port PortAt (uint8_t port_num)
uint8_t MaxPorts () const
DeviceManager * DeviceManager ()
Private Member Functions
InterrupterRegisterSetArray InterrupterRegisterSets () const
PortRegisterSetArray PortRegisterSets () const
DoorbellRegisterArray DoorbellRegisters () const
Private Attributes
const uintptr_t mmio_base_
CapabilityRegisters *const cap_
OperationalRegisters *const op_
const uint8_t max_ports_
class DeviceManager devmgr_
Ring cr_
EventRing er_
Static Private Attributes
static const size_t kDeviceSize = 8
Detailed Description
Definition at line 17 of file xhci.hpp.
Constructor & Destructor Documentation
Controller()
usb::xhci::Controller::Controller (uintptr_t mmio_base)
Definition at line 340 of file xhci.cpp.
Member Function Documentation
CommandRing()
Ring* usb::xhci::Controller::CommandRing () inline
Definition at line 22 of file xhci.hpp.
References cr_.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), usb::xhci::ConfigureEndpoints(), and anonymous_namespace{xhci.cpp}::EnableSlot().
DeviceManager()
DeviceManager* usb::xhci::Controller::DeviceManager () inline
Definition at line 29 of file xhci.hpp.
References devmgr_.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), anonymous_namespace{xhci.cpp}::CompleteConfiguration(), anonymous_namespace{xhci.cpp}::InitializeDevice(), and anonymous_namespace{xhci.cpp}::OnEvent().
DoorbellRegisterAt()
DoorbellRegister * usb::xhci::Controller::DoorbellRegisterAt (uint8_t index)
Definition at line 437 of file xhci.cpp.
References DoorbellRegisters(), and index.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), usb::xhci::ConfigureEndpoints(), and anonymous_namespace{xhci.cpp}::EnableSlot().
DoorbellRegisters()
DoorbellRegisterArray usb::xhci::Controller::DoorbellRegisters () const inline private
Definition at line 51 of file xhci.hpp.
References cap_, usb::xhci::CapabilityRegisters::DBOFF, and mmio_base_.
Referenced by DoorbellRegisterAt().
Initialize()
Error usb::xhci::Controller::Initialize ()
Definition at line 349 of file xhci.cpp.
References usb::AllocMem(), cap_, usb::xhci::OperationalRegisters::CONFIG, cr_, usb::xhci::OperationalRegisters::CRCR, usb::xhci::OperationalRegisters::DCBAAP, usb::xhci::DeviceManager::DeviceContexts(), devmgr_, er_, usb::xhci::CapabilityRegisters::HCCPARAMS1, usb::xhci::CapabilityRegisters::HCSPARAMS1, usb::xhci::CapabilityRegisters::HCSPARAMS2, usb::xhci::DeviceManager::Initialize(), usb::xhci::Ring::Initialize(), usb::xhci::EventRing::Initialize(), InterrupterRegisterSets(), kDebug, kDeviceSize, kInfo, Error::kSuccess, Log(), MAKE_ERROR, mmio_base_, op_, anonymous_namespace{xhci.cpp}::RegisterCommandRing(), anonymous_namespace{xhci.cpp}::RequestHCOwnership(), usb::xhci::DCBAAP_Bitmap::SetPointer(), usb::xhci::OperationalRegisters::USBCMD, and usb::xhci::OperationalRegisters::USBSTS.
Referenced by usb::xhci::Initialize().
InterrupterRegisterSets()
InterrupterRegisterSetArray usb::xhci::Controller::InterrupterRegisterSets () const inline private
Definition at line 43 of file xhci.hpp.
References cap_, mmio_base_, and usb::xhci::CapabilityRegisters::RTSOFF.
Referenced by Initialize().
MaxPorts()
uint8_t usb::xhci::Controller::MaxPorts () const inline
Definition at line 28 of file xhci.hpp.
References max_ports_.
Referenced by usb::xhci::Initialize().
PortAt()
Port usb::xhci::Controller::PortAt (uint8_t port_num) inline
Definition at line 25 of file xhci.hpp.
References PortRegisterSets().
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), usb::xhci::ConfigureEndpoints(), usb::xhci::Initialize(), and anonymous_namespace{xhci.cpp}::OnEvent().
PortRegisterSets()
PortRegisterSetArray usb::xhci::Controller::PortRegisterSets () const inline private
Definition at line 47 of file xhci.hpp.
References max_ports_, and op_.
Referenced by PortAt().
PrimaryEventRing()
EventRing* usb::xhci::Controller::PrimaryEventRing () inline
Definition at line 23 of file xhci.hpp.
References er_.
Referenced by usb::xhci::ProcessEvent(), and usb::xhci::ProcessEvents().
Run()
Error usb::xhci::Controller::Run ()
Definition at line 425 of file xhci.cpp.
References Error::kSuccess, MAKE_ERROR, op_, usb::xhci::OperationalRegisters::USBCMD, and usb::xhci::OperationalRegisters::USBSTS.
Referenced by usb::xhci::Initialize().
Member Data Documentation
cap_
CapabilityRegisters* const usb::xhci::Controller::cap_ private
Definition at line 35 of file xhci.hpp.
Referenced by DoorbellRegisters(), Initialize(), and InterrupterRegisterSets().
cr_
Ring usb::xhci::Controller::cr_ private
Definition at line 40 of file xhci.hpp.
Referenced by CommandRing(), and Initialize().
devmgr_
class DeviceManager usb::xhci::Controller::devmgr_ private
Definition at line 39 of file xhci.hpp.
Referenced by DeviceManager(), and Initialize().
er_
EventRing usb::xhci::Controller::er_ private
Definition at line 41 of file xhci.hpp.
Referenced by Initialize(), and PrimaryEventRing().
kDeviceSize
const size_t usb::xhci::Controller::kDeviceSize = 8 static private
Definition at line 32 of file xhci.hpp.
Referenced by Initialize().
max_ports_
const uint8_t usb::xhci::Controller::max_ports_ private
Definition at line 37 of file xhci.hpp.
Referenced by MaxPorts(), and PortRegisterSets().
mmio_base_
const uintptr_t usb::xhci::Controller::mmio_base_ private
Definition at line 34 of file xhci.hpp.
Referenced by DoorbellRegisters(), Initialize(), and InterrupterRegisterSets().
op_
OperationalRegisters* const usb::xhci::Controller::op_ private
Definition at line 36 of file xhci.hpp.
Referenced by Initialize(), PortRegisterSets(), and Run().
The documentation for this class was generated from the following files:
kernel/usb/xhci/xhci.hpp
kernel/usb/xhci/xhci.cpp