My Project: usb::HIDMouseDriver Class Reference
usb::HIDMouseDriver Class Reference
#include <mouse.hpp>
Public Types
using ObserverType = void(uint8_t buttons, int8_t displacement_x, int8_t displacement_y)
Public Member Functions
HIDMouseDriver (Device *dev, int interface_index)
void * operator new (size_t size)
void operator delete (void *ptr) noexcept
Error OnDataReceived () override
void SubscribeMouseMove (std::function< ObserverType > observer)
Public Member Functions inherited from usb::HIDBaseDriver
HIDBaseDriver (Device *dev, int interface_index, int in_packet_size)
Error Initialize () override
Error SetEndpoint (const EndpointConfig &config) override
Error OnEndpointsConfigured () override
Error OnControlCompleted (EndpointID ep_id, SetupData setup_data, const void *buf, int len) override
Error OnInterruptCompleted (EndpointID ep_id, const void *buf, int len) override
const std::array< uint8_t, kBufferSize > & Buffer () const
const std::array< uint8_t, kBufferSize > & PreviousBuffer () const
Public Member Functions inherited from usb::ClassDriver
ClassDriver (Device *dev)
virtual ~ClassDriver ()
Device * ParentDevice () const
Static Public Attributes
static std::function< ObserverType > default_observer
Static Public Attributes inherited from usb::HIDBaseDriver
const static size_t kBufferSize = 1024
Private Member Functions
void NotifyMouseMove (uint8_t buttons, int8_t displacement_x, int8_t displacement_y)
Private Attributes
std::array< std::function< ObserverType >, 4 > observers_
int num_observers_ = 0
Detailed Description
Definition at line 13 of file mouse.hpp.
Member Typedef Documentation
ObserverType
using usb::HIDMouseDriver::ObserverType = void (uint8_t buttons, int8_t displacement_x, int8_t displacement_y)
Definition at line 22 of file mouse.hpp.
Constructor & Destructor Documentation
HIDMouseDriver()
usb::HIDMouseDriver::HIDMouseDriver (Device * dev, int interface_index)
Definition at line 9 of file mouse.cpp.
Member Function Documentation
NotifyMouseMove()
void usb::HIDMouseDriver::NotifyMouseMove (uint8_t buttons, int8_t displacement_x, int8_t displacement_y) private
Definition at line 36 of file mouse.cpp.
References num_observers_, and observers_.
Referenced by OnDataReceived().
OnDataReceived()
Error usb::HIDMouseDriver::OnDataReceived () override virtual
Implements usb::HIDBaseDriver.
Definition at line 13 of file mouse.cpp.
References usb::HIDBaseDriver::Buffer(), kDebug, Error::kSuccess, Log(), MAKE_ERROR, and NotifyMouseMove().
operator delete()
void usb::HIDMouseDriver::operator delete (void * ptr) noexcept
Definition at line 26 of file mouse.cpp.
References usb::FreeMem().
operator new()
void * usb::HIDMouseDriver::operator new (size_t size)
Definition at line 22 of file mouse.cpp.
References usb::AllocMem().
SubscribeMouseMove()
void usb::HIDMouseDriver::SubscribeMouseMove (std::function< ObserverType > observer)
Definition at line 30 of file mouse.cpp.
References num_observers_, and observers_.
Member Data Documentation
default_observer
std::function< HIDMouseDriver::ObserverType > usb::HIDMouseDriver::default_observer static
Definition at line 24 of file mouse.hpp.
Referenced by InitializeMouse(), and anonymous_namespace{device.cpp}::NewClassDriver().
num_observers_
int usb::HIDMouseDriver::num_observers_ = 0 private
Definition at line 28 of file mouse.hpp.
Referenced by NotifyMouseMove(), and SubscribeMouseMove().
observers_
std::array<std::function<ObserverType>, 4> usb::HIDMouseDriver::observers_ private
Definition at line 27 of file mouse.hpp.
Referenced by NotifyMouseMove(), and SubscribeMouseMove().
The documentation for this class was generated from the following files:
kernel/usb/classdriver/mouse.hpp
kernel/usb/classdriver/mouse.cpp