My Project: usb::xhci::Ring Class Reference
usb::xhci::Ring Class Reference
Command/Transfer Ring を表すクラス．
#include <ring.hpp>
Public Member Functions
Ring ()=default
Ring (const Ring &)=delete
~Ring ()
Ring & operator= (const Ring &)=delete
Error Initialize (size_t buf_size)
リングのメモリ領域を割り当て，メンバを初期化する．
template<typename TRBType >
TRB * Push (const TRBType &trb)
TRB に cycle bit を設定した上でリング末尾に追加する．
TRB * Buffer () const
Private Member Functions
void CopyToLast (const std::array< uint32_t, 4 > &data)
TRB に cycle bit を設定した上でリング末尾に書き込む．
TRB * Push (const std::array< uint32_t, 4 > &data)
TRB に cycle bit を設定した上でリング末尾に追加する．
Private Attributes
TRB * buf_ = nullptr
size_t buf_size_ = 0
bool cycle_bit_
プロデューサ・サイクル・ステートを表すビット
size_t write_index_
リング上で次に書き込む位置
Detailed Description
Command/Transfer Ring を表すクラス．
Definition at line 19 of file ring.hpp.
Constructor & Destructor Documentation
Ring() [1/2]
usb::xhci::Ring::Ring () default
Ring() [2/2]
usb::xhci::Ring::Ring (const Ring &) delete
~Ring()
usb::xhci::Ring::~Ring ()
Definition at line 6 of file ring.cpp.
References buf_, and usb::FreeMem().
Member Function Documentation
Buffer()
TRB* usb::xhci::Ring::Buffer () const inline
Definition at line 38 of file ring.hpp.
References buf_.
Referenced by anonymous_namespace{xhci.cpp}::InitializeEP0Context(), and anonymous_namespace{xhci.cpp}::RegisterCommandRing().
CopyToLast()
void usb::xhci::Ring::CopyToLast (const std::array< uint32_t, 4 > & data) private
TRB に cycle bit を設定した上でリング末尾に書き込む．
write_index_ は変化させない．
Definition at line 30 of file ring.cpp.
References buf_, cycle_bit_, data, usb::xhci::TRB::data, and write_index_.
Referenced by Push().
Initialize()
Error usb::xhci::Ring::Initialize (size_t buf_size)
リングのメモリ領域を割り当て，メンバを初期化する．
Definition at line 12 of file ring.cpp.
References buf_, buf_size_, cycle_bit_, usb::FreeMem(), Error::kNoEnoughMemory, Error::kSuccess, MAKE_ERROR, and write_index_.
Referenced by usb::xhci::Controller::Initialize().
operator=()
Ring& usb::xhci::Ring::operator= (const Ring &) delete
Push() [1/2]
TRB * usb::xhci::Ring::Push (const std::array< uint32_t, 4 > & data) private
TRB に cycle bit を設定した上でリング末尾に追加する．
write_index_ をインクリメントする．その結果 write_index_ がリング末尾 に達したら LinkTRB を適切に配置して write_index_ を 0 に戻し， cycle bit を反転させる．
Returns
追加された（リング上の）TRB を指すポインタ．
Definition at line 39 of file ring.cpp.
References buf_, buf_size_, CopyToLast(), cycle_bit_, data, and write_index_.
Push() [2/2]
template<typename TRBType > TRB* usb::xhci::Ring::Push (const TRBType & trb) inline
TRB に cycle bit を設定した上でリング末尾に追加する．
Returns
追加された（リング上の）TRB を指すポインタ．
Definition at line 34 of file ring.hpp.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), usb::xhci::ConfigureEndpoints(), usb::xhci::Device::ControlIn(), usb::xhci::Device::ControlOut(), anonymous_namespace{xhci.cpp}::EnableSlot(), and usb::xhci::Device::InterruptIn().
Member Data Documentation
buf_
TRB* usb::xhci::Ring::buf_ = nullptr private
Definition at line 41 of file ring.hpp.
Referenced by Buffer(), CopyToLast(), Initialize(), Push(), and ~Ring().
buf_size_
size_t usb::xhci::Ring::buf_size_ = 0 private
Definition at line 42 of file ring.hpp.
Referenced by Initialize(), and Push().
cycle_bit_
bool usb::xhci::Ring::cycle_bit_ private
プロデューサ・サイクル・ステートを表すビット
Definition at line 45 of file ring.hpp.
Referenced by CopyToLast(), Initialize(), and Push().
write_index_
size_t usb::xhci::Ring::write_index_ private
リング上で次に書き込む位置
Definition at line 47 of file ring.hpp.
Referenced by CopyToLast(), Initialize(), and Push().
The documentation for this class was generated from the following files:
kernel/usb/xhci/ring.hpp
kernel/usb/xhci/ring.cpp