My Project: TaskManager Class Reference
TaskManager Class Reference
#include <task.hpp>
Public Member Functions
TaskManager ()
Task & NewTask ()
void SwitchTask (bool current_sleep=false)
void Sleep (Task *task)
Error Sleep (uint64_t id)
void Wakeup (Task *task)
Error Wakeup (uint64_t id)
Error SendMessage (uint64_t id, const Message &msg)
Task & CurrentTask ()
Private Attributes
std::vector< std::unique_ptr< Task > > tasks_ {}
std::deque< Task * > running_ {}
uint64_t latest_id_ {0}
Detailed Description
Definition at line 47 of file task.hpp.
Constructor & Destructor Documentation
TaskManager()
TaskManager::TaskManager ()
Definition at line 64 of file task.cpp.
References NewTask(), and running_.
Member Function Documentation
CurrentTask()
Task & TaskManager::CurrentTask ()
Definition at line 150 of file task.cpp.
References running_.
Referenced by KernelMainNewStack().
NewTask()
Task & TaskManager::NewTask ()
Definition at line 68 of file task.cpp.
References latest_id_, and tasks_.
Referenced by KernelMainNewStack(), and TaskManager().
SendMessage()
Error TaskManager::SendMessage (uint64_t id, const Message & msg)
Definition at line 139 of file task.cpp.
References Error::kNoSuchTask, Error::kSuccess, MAKE_ERROR, and tasks_.
Referenced by anonymous_namespace{interrupt.cpp}::__attribute__(), InitializeKeyboard(), and TimerManager::Tick().
Sleep() [1/2]
void TaskManager::Sleep (Task * task)
Definition at line 84 of file task.cpp.
References running_, and SwitchTask().
Referenced by KernelMainNewStack(), Task::Sleep(), and Sleep().
Sleep() [2/2]
Error TaskManager::Sleep (uint64_t id)
Definition at line 99 of file task.cpp.
References Error::kNoSuchTask, Error::kSuccess, MAKE_ERROR, Sleep(), and tasks_.
SwitchTask()
void TaskManager::SwitchTask (bool current_sleep = false)
Definition at line 73 of file task.cpp.
References Task::Context(), running_, and SwitchContext().
Referenced by LAPICTimerOnInterrupt(), and Sleep().
Wakeup() [1/2]
void TaskManager::Wakeup (Task * task)
Definition at line 110 of file task.cpp.
References running_.
Referenced by KernelMainNewStack(), Task::Wakeup(), and Wakeup().
Wakeup() [2/2]
Error TaskManager::Wakeup (uint64_t id)
Definition at line 117 of file task.cpp.
References Error::kNoSuchTask, Error::kSuccess, MAKE_ERROR, tasks_, and Wakeup().
Member Data Documentation
latest_id_
uint64_t TaskManager::latest_id_ {0} private
Definition at line 63 of file task.hpp.
Referenced by NewTask().
running_
std::deque<Task*> TaskManager::running_ {} private
Definition at line 62 of file task.hpp.
Referenced by CurrentTask(), Sleep(), SwitchTask(), TaskManager(), and Wakeup().
tasks_
std::vector<std::unique_ptr<Task> > TaskManager::tasks_ {} private
Definition at line 61 of file task.hpp.
Referenced by NewTask(), SendMessage(), Sleep(), and Wakeup().
The documentation for this class was generated from the following files:
kernel/task.hpp
kernel/task.cpp