My Project: BitmapMemoryManager Class Reference
BitmapMemoryManager Class Reference
#include <memory_manager.hpp>
Public Types
using MapLineType = unsigned long
Public Member Functions
BitmapMemoryManager ()
WithError< FrameID > Allocate (size_t num_frames)
Error Free (FrameID start_frame, size_t num_frames)
void MarkAllocated (FrameID start_frame, size_t num_frames)
void SetMemoryRange (FrameID range_begin, FrameID range_end)
Static Public Attributes
static const auto kMaxPhysicalMemoryBytes {128_GiB}
static const auto kFrameCount {kMaxPhysicalMemoryBytes / kBytesPerFrame}
static const size_t kBitsPerMapLine {8 * sizeof(MapLineType)}
Private Member Functions
bool GetBit (FrameID frame) const
void SetBit (FrameID frame, bool allocated)
Private Attributes
std::array< MapLineType, kFrameCount/kBitsPerMapLine > alloc_map_
FrameID range_begin_
FrameID range_end_
Detailed Description
Definition at line 37 of file memory_manager.hpp.
Member Typedef Documentation
MapLineType
using BitmapMemoryManager::MapLineType = unsigned long
Definition at line 42 of file memory_manager.hpp.
Constructor & Destructor Documentation
BitmapMemoryManager()
BitmapMemoryManager::BitmapMemoryManager ()
Definition at line 5 of file memory_manager.cpp.
Member Function Documentation
Allocate()
WithError< FrameID > BitmapMemoryManager::Allocate (size_t num_frames)
Definition at line 9 of file memory_manager.cpp.
References GetBit(), FrameID::ID(), Error::kNoEnoughMemory, kNullFrame, Error::kSuccess, MAKE_ERROR, MarkAllocated(), range_begin_, and range_end_.
Referenced by anonymous_namespace{memory_manager.cpp}::InitializeHeap().
Free()
Error BitmapMemoryManager::Free (FrameID start_frame, size_t num_frames)
Definition at line 36 of file memory_manager.cpp.
References FrameID::ID(), Error::kSuccess, MAKE_ERROR, and SetBit().
GetBit()
bool BitmapMemoryManager::GetBit (FrameID frame) const private
Definition at line 54 of file memory_manager.cpp.
References alloc_map_, FrameID::ID(), and kBitsPerMapLine.
Referenced by Allocate().
MarkAllocated()
void BitmapMemoryManager::MarkAllocated (FrameID start_frame, size_t num_frames)
Definition at line 43 of file memory_manager.cpp.
References FrameID::ID(), and SetBit().
Referenced by Allocate(), and InitializeMemoryManager().
SetBit()
void BitmapMemoryManager::SetBit (FrameID frame, bool allocated) private
Definition at line 61 of file memory_manager.cpp.
References alloc_map_, FrameID::ID(), and kBitsPerMapLine.
Referenced by Free(), and MarkAllocated().
SetMemoryRange()
void BitmapMemoryManager::SetMemoryRange (FrameID range_begin, FrameID range_end)
Definition at line 49 of file memory_manager.cpp.
References range_begin_, and range_end_.
Referenced by InitializeMemoryManager().
Member Data Documentation
alloc_map_
std::array<MapLineType, kFrameCount / kBitsPerMapLine> BitmapMemoryManager::alloc_map_ private
Definition at line 54 of file memory_manager.hpp.
Referenced by GetBit(), and SetBit().
kBitsPerMapLine
const size_t BitmapMemoryManager::kBitsPerMapLine {8 * sizeof(MapLineType)} static
Definition at line 43 of file memory_manager.hpp.
Referenced by GetBit(), and SetBit().
kFrameCount
const auto BitmapMemoryManager::kFrameCount {kMaxPhysicalMemoryBytes / kBytesPerFrame} static
Definition at line 40 of file memory_manager.hpp.
kMaxPhysicalMemoryBytes
const auto BitmapMemoryManager::kMaxPhysicalMemoryBytes {128_GiB} static
Definition at line 39 of file memory_manager.hpp.
range_begin_
FrameID BitmapMemoryManager::range_begin_ private
Definition at line 55 of file memory_manager.hpp.
Referenced by Allocate(), and SetMemoryRange().
range_end_
FrameID BitmapMemoryManager::range_end_ private
Definition at line 56 of file memory_manager.hpp.
Referenced by Allocate(), and SetMemoryRange().
The documentation for this class was generated from the following files:
kernel/memory_manager.hpp
kernel/memory_manager.cpp