My Project: Mouse Class Reference
Mouse Class Reference
#include <mouse.hpp>
Public Member Functions
Mouse (unsigned int layer_id)
void OnInterrupt (uint8_t buttons, int8_t displacement_x, int8_t displacement_y)
unsigned int LayerID () const
void SetPosition (Vector2D< int > position)
Vector2D< int > Position () const
Private Attributes
unsigned int layer_id_
Vector2D< int > position_ {}
unsigned int drag_layer_id_ {0}
uint8_t previous_buttons_ {0}
Detailed Description
Definition at line 11 of file mouse.hpp.
Constructor & Destructor Documentation
Mouse()
Mouse::Mouse (unsigned int layer_id)
Definition at line 52 of file mouse.cpp.
Member Function Documentation
LayerID()
unsigned int Mouse::LayerID () const inline
Definition at line 16 of file mouse.hpp.
References layer_id_.
OnInterrupt()
void Mouse::OnInterrupt (uint8_t buttons, int8_t displacement_x, int8_t displacement_y)
Definition at line 60 of file mouse.cpp.
References drag_layer_id_, ElementMax(), ElementMin(), LayerManager::FindLayerByPosition(), layer_id_, layer_manager, LayerManager::MoveRelative(), position_, previous_buttons_, ScreenSize(), and SetPosition().
Position()
Vector2D<int> Mouse::Position () const inline
Definition at line 18 of file mouse.hpp.
References position_.
SetPosition()
void Mouse::SetPosition (Vector2D< int > position)
Definition at line 55 of file mouse.cpp.
References layer_id_, layer_manager, LayerManager::Move(), and position_.
Referenced by OnInterrupt().
Member Data Documentation
drag_layer_id_
unsigned int Mouse::drag_layer_id_ {0} private
Definition at line 24 of file mouse.hpp.
Referenced by OnInterrupt().
layer_id_
unsigned int Mouse::layer_id_ private
Definition at line 21 of file mouse.hpp.
Referenced by LayerID(), OnInterrupt(), and SetPosition().
position_
Vector2D<int> Mouse::position_ {} private
Definition at line 22 of file mouse.hpp.
Referenced by OnInterrupt(), Position(), and SetPosition().
previous_buttons_
uint8_t Mouse::previous_buttons_ {0} private
Definition at line 25 of file mouse.hpp.
Referenced by OnInterrupt().
The documentation for this class was generated from the following files:
kernel/mouse.hpp
kernel/mouse.cpp