My Project: FrameID Class Reference
FrameID Class Reference
#include <memory_manager.hpp>
Public Member Functions
FrameID (size_t id)
size_t ID () const
void * Frame () const
Private Attributes
size_t id_
Detailed Description
Definition at line 25 of file memory_manager.hpp.
Constructor & Destructor Documentation
FrameID()
FrameID::FrameID (size_t id) inline explicit
Definition at line 27 of file memory_manager.hpp.
Member Function Documentation
Frame()
void* FrameID::Frame () const inline
Definition at line 29 of file memory_manager.hpp.
References id_, and kBytesPerFrame().
ID()
size_t FrameID::ID () const inline
Definition at line 28 of file memory_manager.hpp.
References id_.
Referenced by BitmapMemoryManager::Allocate(), BitmapMemoryManager::Free(), BitmapMemoryManager::GetBit(), BitmapMemoryManager::MarkAllocated(), and BitmapMemoryManager::SetBit().
Member Data Documentation
id_
size_t FrameID::id_ private
Definition at line 32 of file memory_manager.hpp.
Referenced by Frame(), and ID().
The documentation for this class was generated from the following file:
kernel/memory_manager.hpp