My Project: LayerManager Class Reference
LayerManager Class Reference
LayerManagerは複数のレイヤーを管理する。
#include <layer.hpp>
Public Member Functions
void SetWriter (FrameBuffer *screen)
Drawメソッドなどで描画する際の描画先を設定する。
Layer & NewLayer ()
新しいレイヤーを生成して参照を返す。
void Draw (const Rectangle< int > &area) const
現在表示状態にあるレイヤーを描画する。
void Draw (unsigned int id) const
指定したレイヤーに設定されているウィンドウの描画領域内を再描画する。
void Move (unsigned int id, Vector2D< int > new_position)
レイヤーの位置情報を指定された絶対座標へと更新する。再描画はしない。
void MoveRelative (unsigned int id, Vector2D< int > pos_diff)
レイヤーの位置情報を指定された相対座標へと更新する。再描画はしない。
void UpDown (unsigned int id, int new_height)
レイヤーの高さ方向の位置を指定された位置に移動する。
void Hide (unsigned int id)
レイヤーを非表示とする。
Layer * FindLayerByPosition (Vector2D< int > pos, unsigned int exclude_id) const
指定された座標にウィンドウを持つ最も上に表示されているレイヤーを探す。
Private Member Functions
Layer * FindLayer (unsigned int id)
Private Attributes
FrameBuffer * screen_ {nullptr}
FrameBuffer back_buffer_ {}
std::vector< std::unique_ptr< Layer > > layers_ {}
std::vector< Layer * > layer_stack_ {}
unsigned int latest_id_ {0}
Detailed Description
LayerManagerは複数のレイヤーを管理する。
Definition at line 55 of file layer.hpp.
Member Function Documentation
Draw() [1/2]
void LayerManager::Draw (const Rectangle< int > & area) const
現在表示状態にあるレイヤーを描画する。
Definition at line 66 of file layer.cpp.
References back_buffer_, FrameBuffer::Copy(), layer_stack_, Rectangle< T >::pos, and screen_.
Referenced by InputTextWindow(), KernelMainNewStack(), Move(), MoveRelative(), Console::PutString(), and TaskB().
Draw() [2/2]
void LayerManager::Draw (unsigned int id) const
指定したレイヤーに設定されているウィンドウの描画領域内を再描画する。
Definition at line 72 of file layer.cpp.
References back_buffer_, FrameBuffer::Copy(), layer_stack_, Rectangle< T >::pos, screen_, and Rectangle< T >::size.
FindLayer()
Layer * LayerManager::FindLayer (unsigned int id) private
Definition at line 140 of file layer.cpp.
References Layer::ID(), and layers_.
Referenced by Hide(), Move(), MoveRelative(), and UpDown().
FindLayerByPosition()
Layer * LayerManager::FindLayerByPosition (Vector2D< int > pos, unsigned int exclude_id) const
指定された座標にウィンドウを持つ最も上に表示されているレイヤーを探す。
Definition at line 151 of file layer.cpp.
References Layer::GetWindow(), layer_stack_, Vector2D< T >::x, and Vector2D< T >::y.
Referenced by Mouse::OnInterrupt().
Hide()
void LayerManager::Hide (unsigned int id)
レイヤーを非表示とする。
Definition at line 132 of file layer.cpp.
References FindLayer(), and layer_stack_.
Referenced by UpDown().
Move()
void LayerManager::Move (unsigned int id, Vector2D< int > new_position)
レイヤーの位置情報を指定された絶対座標へと更新する。再描画はしない。
Definition at line 88 of file layer.cpp.
References Draw(), and FindLayer().
Referenced by Mouse::SetPosition().
MoveRelative()
void LayerManager::MoveRelative (unsigned int id, Vector2D< int > pos_diff)
レイヤーの位置情報を指定された相対座標へと更新する。再描画はしない。
Definition at line 97 of file layer.cpp.
References Draw(), and FindLayer().
Referenced by Mouse::OnInterrupt().
NewLayer()
Layer & LayerManager::NewLayer ()
新しいレイヤーを生成して参照を返す。
新しく生成されたレイヤーの実態はLayerManager内部のコンテナで保持される。
Definition at line 61 of file layer.cpp.
References latest_id_, and layers_.
Referenced by InitializeLayer(), InitializeMainWindow(), InitializeMouse(), InitializeTaskBWindow(), and InitializeTextWindow().
SetWriter()
void LayerManager::SetWriter (FrameBuffer * screen)
Drawメソッドなどで描画する際の描画先を設定する。
Definition at line 53 of file layer.cpp.
References back_buffer_, FrameBuffer::Config(), FrameBufferConfig::frame_buffer, FrameBuffer::Initialize(), anonymous_namespace{layer.cpp}::screen, and screen_.
Referenced by InitializeLayer().
UpDown()
void LayerManager::UpDown (unsigned int id, int new_height)
レイヤーの高さ方向の位置を指定された位置に移動する。
new_heightに負の高さを指定するとレイヤーや非表示となり、 0異常を指定するとその高さとなる。 現在のレイヤー数以上の数値を指定した場合は最前面のレイヤーとなる。
Definition at line 106 of file layer.cpp.
References FindLayer(), Hide(), and layer_stack_.
Referenced by InitializeLayer(), InitializeMainWindow(), InitializeMouse(), InitializeTaskBWindow(), and InitializeTextWindow().
Member Data Documentation
back_buffer_
FrameBuffer LayerManager::back_buffer_ {} mutable private
Definition at line 90 of file layer.hpp.
Referenced by Draw(), and SetWriter().
latest_id_
unsigned int LayerManager::latest_id_ {0} private
Definition at line 93 of file layer.hpp.
Referenced by NewLayer().
layer_stack_
std::vector<Layer*> LayerManager::layer_stack_ {} private
Definition at line 92 of file layer.hpp.
Referenced by Draw(), FindLayerByPosition(), Hide(), and UpDown().
layers_
std::vector<std::unique_ptr<Layer> > LayerManager::layers_ {} private
Definition at line 91 of file layer.hpp.
Referenced by FindLayer(), and NewLayer().
screen_
FrameBuffer* LayerManager::screen_ {nullptr} private
Definition at line 89 of file layer.hpp.
Referenced by Draw(), and SetWriter().
The documentation for this class was generated from the following files:
kernel/layer.hpp
kernel/layer.cpp