My Project: kernel/font.cpp File Reference
font.cpp File Reference
#include "font.hpp"
Functions
const uint8_t * GetFont (char c)
void WriteAscii (PixelWriter &writer, Vector2D< int > pos, char c, const PixelColor &color)
void WriteString (PixelWriter &writer, Vector2D< int > pos, const char *s, const PixelColor &color)
Variables
const uint8_t _binary_hankaku_bin_start
const uint8_t _binary_hankaku_bin_end
const uint8_t _binary_hankaku_bin_size
Function Documentation
GetFont()
const uint8_t* GetFont (char c)
Definition at line 7 of file font.cpp.
References _binary_hankaku_bin_size, _binary_hankaku_bin_start, and index.
Referenced by WriteAscii().
WriteAscii()
void WriteAscii (PixelWriter & writer, Vector2D< int > pos, char c, const PixelColor & color)
Definition at line 15 of file font.cpp.
References GetFont(), and PixelWriter::Write().
Referenced by InputTextWindow(), Console::PutString(), and WriteString().
WriteString()
void WriteString (PixelWriter & writer, Vector2D< int > pos, const char * s, const PixelColor & color)
Definition at line 30 of file font.cpp.
References WriteAscii().
Referenced by DrawWindow(), KernelMainNewStack(), Console::Newline(), Console::Refresh(), and TaskB().
Variable Documentation
_binary_hankaku_bin_end
const uint8_t _binary_hankaku_bin_end
_binary_hankaku_bin_size
const uint8_t _binary_hankaku_bin_size
Referenced by GetFont().
_binary_hankaku_bin_start
const uint8_t _binary_hankaku_bin_start
Referenced by GetFont().