My Project: kernel/graphics.hpp File Reference
graphics.hpp File Reference
#include <algorithm>
#include "frame_buffer_config.hpp"
Classes
struct PixelColor
struct Vector2D< T >
struct Rectangle< T >
class PixelWriter
class FrameBufferWriter
class RGBResv8BitPerColorPixelWriter
class BGRResv8BitPerColorPixelWriter
Functions
constexpr PixelColor ToColor (uint32_t c)
bool operator== (const PixelColor &lhs, const PixelColor &rhs)
bool operator!= (const PixelColor &lhs, const PixelColor &rhs)
template<typename T >
Vector2D< T > ElementMax (const Vector2D< T > &lhs, const Vector2D< T > &rhs)
template<typename T >
Vector2D< T > ElementMin (const Vector2D< T > &lhs, const Vector2D< T > &rhs)
template<typename T , typename U >
Rectangle< T > operator& (const Rectangle< T > &lhs, const Rectangle< U > &rhs)
void DrawRectangle (PixelWriter &writer, const Vector2D< int > &pos, const Vector2D< int > &size, const PixelColor &c)
void FillRectangle (PixelWriter &writer, const Vector2D< int > &pos, const Vector2D< int > &size, const PixelColor &c)
void DrawDesktop (PixelWriter &writer)
Vector2D< int > ScreenSize ()
void InitializeGraphics (const FrameBufferConfig &screen_config)
Variables
const PixelColor kDesktopBGColor {45, 118, 237}
const PixelColor kDesktopFGColor {255, 255, 255}
FrameBufferConfig screen_config
PixelWriter * screen_writer
Function Documentation
DrawDesktop()
void DrawDesktop (PixelWriter & writer)
Definition at line 38 of file graphics.cpp.
References DrawRectangle(), FillRectangle(), PixelWriter::Height(), kDesktopBGColor, and PixelWriter::Width().
Referenced by InitializeGraphics(), and InitializeLayer().
DrawRectangle()
void DrawRectangle (PixelWriter & writer, const Vector2D< int > & pos, const Vector2D< int > & size, const PixelColor & c)
Definition at line 17 of file graphics.cpp.
References PixelWriter::Write(), Vector2D< T >::x, and Vector2D< T >::y.
Referenced by DrawDesktop().
ElementMax()
template<typename T > Vector2D<T> ElementMax (const Vector2D< T > & lhs, const Vector2D< T > & rhs)
Definition at line 60 of file graphics.hpp.
References Vector2D< T >::x, and Vector2D< T >::y.
Referenced by Mouse::OnInterrupt(), and operator&().
ElementMin()
template<typename T > Vector2D<T> ElementMin (const Vector2D< T > & lhs, const Vector2D< T > & rhs)
Definition at line 65 of file graphics.hpp.
References Vector2D< T >::x, and Vector2D< T >::y.
Referenced by Mouse::OnInterrupt(), and operator&().
FillRectangle()
void FillRectangle (PixelWriter & writer, const Vector2D< int > & pos, const Vector2D< int > & size, const PixelColor & c)
Definition at line 29 of file graphics.cpp.
References PixelWriter::Write(), Vector2D< T >::x, and Vector2D< T >::y.
Referenced by DrawDesktop(), DrawTextbox(), DrawTextCursor(), DrawWindow(), InputTextWindow(), KernelMainNewStack(), Console::Newline(), Console::Refresh(), and TaskB().
InitializeGraphics()
void InitializeGraphics (const FrameBufferConfig & screen_config)
Definition at line 73 of file graphics.cpp.
References DrawDesktop(), kPixelBGRResv8BitPerColor, kPixelRGBResv8BitPerColor, FrameBufferConfig::pixel_format, anonymous_namespace{graphics.cpp}::pixel_writer_buf, screen_config, and screen_writer.
Referenced by KernelMainNewStack().
operator!=()
bool operator!= (const PixelColor & lhs, const PixelColor & rhs) inline
Definition at line 22 of file graphics.hpp.
operator&()
template<typename T , typename U > Rectangle<T> operator& (const Rectangle< T > & lhs, const Rectangle< U > & rhs)
Definition at line 75 of file graphics.hpp.
References ElementMax(), ElementMin(), Rectangle< T >::pos, and Rectangle< T >::size.
operator==()
bool operator== (const PixelColor & lhs, const PixelColor & rhs) inline
Definition at line 18 of file graphics.hpp.
References PixelColor::b, PixelColor::g, and PixelColor::r.
ScreenSize()
Vector2D<int> ScreenSize ()
Definition at line 62 of file graphics.cpp.
References FrameBufferConfig::horizontal_resolution, screen_config, and FrameBufferConfig::vertical_resolution.
Referenced by InitializeLayer(), KernelMainNewStack(), and Mouse::OnInterrupt().
ToColor()
constexpr PixelColor ToColor (uint32_t c) constexpr
Definition at line 10 of file graphics.hpp.
Referenced by DrawTextbox(), DrawTextCursor(), DrawWindow(), and InputTextWindow().
Variable Documentation
kDesktopBGColor
const PixelColor kDesktopBGColor {45, 118, 237}
Definition at line 131 of file graphics.hpp.
Referenced by DrawDesktop(), and InitializeConsole().
kDesktopFGColor
const PixelColor kDesktopFGColor {255, 255, 255}
Definition at line 132 of file graphics.hpp.
Referenced by InitializeConsole().
screen_config
FrameBufferConfig screen_config
Definition at line 59 of file graphics.cpp.
Referenced by InitializeGraphics(), InitializeLayer(), InitializeMainWindow(), InitializeMouse(), InitializeTaskBWindow(), InitializeTextWindow(), and ScreenSize().
screen_writer
PixelWriter* screen_writer
Definition at line 60 of file graphics.cpp.
Referenced by InitializeConsole(), and InitializeGraphics().