My Project: kernel/interrupt.cpp File Reference
interrupt.cpp File Reference
#include "interrupt.hpp"
#include "asmfunc.h"
#include "segment.hpp"
#include "timer.hpp"
#include "task.hpp"
Namespaces
anonymous_namespace{interrupt.cpp}
Functions
void SetIDTEntry (InterruptDescriptor &desc, InterruptDescriptorAttribute attr, uint64_t offset, uint16_t segment_selector)
void NotifyEndOfInterrupt ()
anonymous_namespace{interrupt.cpp}::__attribute__ ((interrupt)) void IntHandlerXHCI(InterruptFrame *frame)
void InitializeInterrupt ()
Variables
std::array< InterruptDescriptor, 256 > idt
Function Documentation
InitializeInterrupt()
void InitializeInterrupt ()
Definition at line 40 of file interrupt.cpp.
References idt, kInterruptGate, kKernelCS, InterruptVector::kLAPICTimer, InterruptVector::kXHCI, LoadIDT(), MakeIDTAttr(), and SetIDTEntry().
Referenced by KernelMainNewStack().
NotifyEndOfInterrupt()
void NotifyEndOfInterrupt ()
Definition at line 21 of file interrupt.cpp.
Referenced by anonymous_namespace{interrupt.cpp}::__attribute__(), and LAPICTimerOnInterrupt().
SetIDTEntry()
void SetIDTEntry (InterruptDescriptor & desc, InterruptDescriptorAttribute attr, uint64_t offset, uint16_t segment_selector)
Definition at line 10 of file interrupt.cpp.
References attr, InterruptDescriptor::attr, InterruptDescriptor::offset_high, InterruptDescriptor::offset_low, InterruptDescriptor::offset_middle, segment_selector, and InterruptDescriptor::segment_selector.
Referenced by InitializeInterrupt().
Variable Documentation
idt
std::array<InterruptDescriptor, 256> idt
Definition at line 8 of file interrupt.cpp.
Referenced by InitializeInterrupt().