My Project: kernel/layer.cpp File Reference
layer.cpp File Reference
#include "layer.hpp"
#include <algorithm>
#include "logger.hpp"
#include "console.hpp"
Namespaces
anonymous_namespace{layer.cpp}
Functions
void InitializeLayer ()
Variables
FrameBuffer * anonymous_namespace{layer.cpp}::screen
LayerManager * layer_manager
Function Documentation
InitializeLayer()
void InitializeLayer ()
Definition at line 179 of file layer.cpp.
References console, DrawDesktop(), Layer::ID(), FrameBuffer::Initialize(), Console::kColumns, kError, Console::kRows, layer_manager, Console::LayerID(), Log(), Layer::Move(), LayerManager::NewLayer(), FrameBufferConfig::pixel_format, anonymous_namespace{layer.cpp}::screen, screen_config, ScreenSize(), Console::SetLayerID(), Console::SetWindow(), Layer::SetWindow(), LayerManager::SetWriter(), and LayerManager::UpDown().
Referenced by KernelMainNewStack().
Variable Documentation
layer_manager
LayerManager* layer_manager
Definition at line 177 of file layer.cpp.
Referenced by InitializeLayer(), InitializeMainWindow(), InitializeMouse(), InitializeTaskBWindow(), InitializeTextWindow(), InputTextWindow(), KernelMainNewStack(), Mouse::OnInterrupt(), Console::PutString(), Mouse::SetPosition(), and TaskB().