My Project: kernel/libcxx_support.cpp File Reference
libcxx_support.cpp File Reference
#include <new>
#include <cerrno>
Functions
int printk (const char *format,...)
int posix_memalign (void **, size_t, size_t)
Function Documentation
posix_memalign()
int posix_memalign (void ** , size_t , size_t)
Definition at line 13 of file libcxx_support.cpp.
printk()
int printk (const char * format, ...)
Definition at line 39 of file main.cpp.
References console, and Console::PutString().
Referenced by KernelMainNewStack(), TaskB(), and TaskIdle().