My Project: kernel/logger.cpp File Reference
logger.cpp File Reference
#include "logger.hpp"
#include <cstddef>
#include <cstdio>
#include "console.hpp"
Namespaces
anonymous_namespace{logger.cpp}
Functions
void SetLogLevel (LogLevel level)
int Log (LogLevel level, const char *format,...)
Variables
LogLevel anonymous_namespace{logger.cpp}::log_level = kWarn
Console * console
Function Documentation
Log()
int Log (LogLevel level, const char * format, ...)
Definition at line 18 of file logger.cpp.
References console, anonymous_namespace{logger.cpp}::log_level, and Console::PutString().
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), anonymous_namespace{xhci.cpp}::CompleteConfiguration(), anonymous_namespace{xhci.cpp}::EnableSlot(), usb::xhci::Controller::Initialize(), acpi::Initialize(), usb::xhci::Initialize(), anonymous_namespace{xhci.cpp}::InitializeDevice(), InitializeLayer(), InitializeMemoryManager(), InitializePCI(), acpi::RSDP::IsValid(), acpi::DescriptionHeader::IsValid(), KernelMainNewStack(), usb::HIDBaseDriver::OnControlCompleted(), usb::HIDMouseDriver::OnDataReceived(), anonymous_namespace{xhci.cpp}::OnEvent(), usb::xhci::ProcessEvents(), anonymous_namespace{xhci.cpp}::RequestHCOwnership(), anonymous_namespace{xhci.cpp}::ResetPort(), and anonymous_namespace{xhci.cpp}::SwitchEhci2Xhci().
SetLogLevel()
void SetLogLevel (LogLevel level)
Definition at line 14 of file logger.cpp.
References anonymous_namespace{logger.cpp}::log_level.
Referenced by KernelMainNewStack().
Variable Documentation
console
Console* console
Definition at line 84 of file console.cpp.
Referenced by InitializeConsole(), InitializeLayer(), Log(), and printk().