My Project: kernel/main.cpp File Reference
main.cpp File Reference
#include <cstdint>
#include <cstddef>
#include <cstdio>
#include <array>
#include <deque>
#include <limits>
#include <numeric>
#include <vector>
#include "frame_buffer_config.hpp"
#include "memory_map.hpp"
#include "graphics.hpp"
#include "mouse.hpp"
#include "font.hpp"
#include "console.hpp"
#include "pci.hpp"
#include "logger.hpp"
#include "usb/xhci/xhci.hpp"
#include "interrupt.hpp"
#include "asmfunc.h"
#include "segment.hpp"
#include "paging.hpp"
#include "memory_manager.hpp"
#include "window.hpp"
#include "layer.hpp"
#include "message.hpp"
#include "timer.hpp"
#include "acpi.hpp"
#include "keyboard.hpp"
#include "task.hpp"
Functions
int printk (const char *format,...)
void InitializeMainWindow ()
void InitializeTextWindow ()
void DrawTextCursor (bool visible)
void InputTextWindow (char c)
void InitializeTaskBWindow ()
void TaskB (uint64_t task_id, int64_t data)
void TaskIdle (uint64_t task_id, int64_t data)
void KernelMainNewStack (const FrameBufferConfig &frame_buffer_config_ref, const MemoryMap &memory_map_ref, const acpi::RSDP &acpi_table)
void __cxa_pure_virtual ()
Variables
std::shared_ptr< Window > main_window
unsigned int main_window_layer_id
std::shared_ptr< Window > text_window
unsigned int text_window_layer_id
int text_window_index
std::shared_ptr< Window > task_b_window
unsigned int task_b_window_layer_id
std::deque< Message > * main_queue
uint8_t kernel_main_stack [1024 *1024]
Detailed Description
カーネル本体のプログラムを書いたファイル
Definition in file main.cpp.
Function Documentation
__cxa_pure_virtual()
void __cxa_pure_virtual ()
Definition at line 254 of file main.cpp.
DrawTextCursor()
void DrawTextCursor (bool visible)
Definition at line 89 of file main.cpp.
References FillRectangle(), text_window, text_window_index, and ToColor().
Referenced by InputTextWindow(), and KernelMainNewStack().
InitializeMainWindow()
void InitializeMainWindow ()
Definition at line 55 of file main.cpp.
References DrawWindow(), layer_manager, main_window, main_window_layer_id, Layer::Move(), LayerManager::NewLayer(), FrameBufferConfig::pixel_format, screen_config, Layer::SetDraggable(), Layer::SetWindow(), and LayerManager::UpDown().
Referenced by KernelMainNewStack().
InitializeTaskBWindow()
void InitializeTaskBWindow ()
Definition at line 118 of file main.cpp.
References DrawWindow(), layer_manager, Layer::Move(), LayerManager::NewLayer(), FrameBufferConfig::pixel_format, screen_config, Layer::SetDraggable(), Layer::SetWindow(), task_b_window, task_b_window_layer_id, and LayerManager::UpDown().
Referenced by KernelMainNewStack().
InitializeTextWindow()
void InitializeTextWindow ()
Definition at line 70 of file main.cpp.
References DrawTextbox(), DrawWindow(), layer_manager, Layer::Move(), LayerManager::NewLayer(), FrameBufferConfig::pixel_format, screen_config, Layer::SetDraggable(), Layer::SetWindow(), text_window, text_window_layer_id, and LayerManager::UpDown().
Referenced by KernelMainNewStack().
InputTextWindow()
void InputTextWindow (char c)
Definition at line 95 of file main.cpp.
References LayerManager::Draw(), DrawTextCursor(), FillRectangle(), layer_manager, text_window, text_window_index, text_window_layer_id, ToColor(), and WriteAscii().
Referenced by KernelMainNewStack().
KernelMainNewStack()
void KernelMainNewStack (const FrameBufferConfig & frame_buffer_config_ref, const MemoryMap & memory_map_ref, const acpi::RSDP & acpi_table)
Definition at line 153 of file main.cpp.
References TimerManager::AddTimer(), TaskManager::CurrentTask(), TimerManager::CurrentTick(), LayerManager::Draw(), DrawTextCursor(), FillRectangle(), Task::ID(), Task::InitContext(), acpi::Initialize(), usb::xhci::Initialize(), InitializeConsole(), InitializeGraphics(), InitializeInterrupt(), InitializeKeyboard(), InitializeLAPICTimer(), InitializeLayer(), InitializeMainWindow(), InitializeMemoryManager(), InitializeMouse(), InitializePaging(), InitializePCI(), InitializeSegmentation(), InitializeTask(), InitializeTaskBWindow(), InitializeTextWindow(), InputTextWindow(), kError, Message::kInterruptXHCI, Message::kKeyPush, kTimerFreq, Message::kTimerTimeout, kWarn, layer_manager, Log(), main_queue, main_window, main_window_layer_id, TaskManager::NewTask(), printk(), usb::xhci::ProcessEvents(), Task::ReceiveMessage(), ScreenSize(), SetLogLevel(), Task::Sleep(), TaskManager::Sleep(), task_manager, TaskB(), TaskIdle(), text_window_layer_id, timer_manager, Task::Wakeup(), TaskManager::Wakeup(), and WriteString().
printk()
int printk (const char * format, ...)
Definition at line 39 of file main.cpp.
References console, and Console::PutString().
Referenced by KernelMainNewStack(), TaskB(), and TaskIdle().
TaskB()
void TaskB (uint64_t task_id, int64_t data)
Definition at line 131 of file main.cpp.
References data, LayerManager::Draw(), FillRectangle(), layer_manager, printk(), task_b_window, task_b_window_layer_id, and WriteString().
Referenced by KernelMainNewStack().
TaskIdle()
void TaskIdle (uint64_t task_id, int64_t data)
Definition at line 144 of file main.cpp.
References data, and printk().
Referenced by KernelMainNewStack().
Variable Documentation
kernel_main_stack
uint8_t kernel_main_stack[1024 *1024]
Definition at line 151 of file main.cpp.
main_queue
std::deque<Message>* main_queue
Definition at line 149 of file main.cpp.
Referenced by KernelMainNewStack().
main_window
std::shared_ptr<Window> main_window
Definition at line 53 of file main.cpp.
Referenced by InitializeMainWindow(), and KernelMainNewStack().
main_window_layer_id
unsigned int main_window_layer_id
Definition at line 54 of file main.cpp.
Referenced by InitializeMainWindow(), and KernelMainNewStack().
task_b_window
std::shared_ptr<Window> task_b_window
Definition at line 116 of file main.cpp.
Referenced by InitializeTaskBWindow(), and TaskB().
task_b_window_layer_id
unsigned int task_b_window_layer_id
Definition at line 117 of file main.cpp.
Referenced by InitializeTaskBWindow(), and TaskB().
text_window
std::shared_ptr<Window> text_window
Definition at line 68 of file main.cpp.
Referenced by DrawTextCursor(), InitializeTextWindow(), and InputTextWindow().
text_window_index
int text_window_index
Definition at line 87 of file main.cpp.
Referenced by DrawTextCursor(), and InputTextWindow().
text_window_layer_id
unsigned int text_window_layer_id
Definition at line 69 of file main.cpp.
Referenced by InitializeTextWindow(), InputTextWindow(), and KernelMainNewStack().