My Project: kernel/memory_manager.hpp File Reference
memory_manager.hpp File Reference
#include <array>
#include <limits>
#include "error.hpp"
#include "memory_map.hpp"
Classes
class FrameID
class BitmapMemoryManager
Namespaces
anonymous_namespace{memory_manager.hpp}
Functions
constexpr unsigned long long anonymous_namespace{memory_manager.hpp}::operator""_KiB (unsigned long long kib)
constexpr unsigned long long anonymous_namespace{memory_manager.hpp}::operator""_MiB (unsigned long long mib)
constexpr unsigned long long anonymous_namespace{memory_manager.hpp}::operator""_GiB (unsigned long long gib)
static const auto kBytesPerFrame (4_KiB)
void InitializeMemoryManager (const MemoryMap &memory_map)
Variables
static const FrameID kNullFrame {std::numeric_limits<size_t>::max()}
Function Documentation
InitializeMemoryManager()
void InitializeMemoryManager (const MemoryMap & memory_map)
Definition at line 91 of file memory_manager.cpp.
References MemoryMap::buffer, MemoryMap::descriptor_size, anonymous_namespace{memory_manager.cpp}::InitializeHeap(), kBytesPerFrame(), kError, Log(), MemoryMap::map_size, BitmapMemoryManager::MarkAllocated(), anonymous_namespace{memory_manager.cpp}::memory_manager, anonymous_namespace{memory_manager.cpp}::memory_manager_buf, and BitmapMemoryManager::SetMemoryRange().
Referenced by KernelMainNewStack().
kBytesPerFrame()
static const auto kBytesPerFrame (4_KiB) static
Referenced by FrameID::Frame(), anonymous_namespace{memory_manager.cpp}::InitializeHeap(), and InitializeMemoryManager().
Variable Documentation
kNullFrame
const FrameID kNullFrame {std::numeric_limits<size_t>::max()} static
Definition at line 35 of file memory_manager.hpp.
Referenced by BitmapMemoryManager::Allocate().