My Project: kernel/memory_manager.cpp File Reference
memory_manager.cpp File Reference
#include "memory_manager.hpp"
#include "logger.hpp"
Namespaces
anonymous_namespace{memory_manager.cpp}
Functions
Error anonymous_namespace{memory_manager.cpp}::InitializeHeap (BitmapMemoryManager &memory_manager)
void InitializeMemoryManager (const MemoryMap &memory_map)
Variables
caddr_t program_break
caddr_t program_break_end
char anonymous_namespace{memory_manager.cpp}::memory_manager_buf [sizeof(BitmapMemoryManager)]
BitmapMemoryManager * anonymous_namespace{memory_manager.cpp}::memory_manager
Function Documentation
InitializeMemoryManager()
void InitializeMemoryManager (const MemoryMap & memory_map)
Definition at line 91 of file memory_manager.cpp.
References MemoryMap::buffer, MemoryMap::descriptor_size, anonymous_namespace{memory_manager.cpp}::InitializeHeap(), kBytesPerFrame(), kError, Log(), MemoryMap::map_size, BitmapMemoryManager::MarkAllocated(), anonymous_namespace{memory_manager.cpp}::memory_manager, anonymous_namespace{memory_manager.cpp}::memory_manager_buf, and BitmapMemoryManager::SetMemoryRange().
Referenced by KernelMainNewStack().
Variable Documentation
program_break
caddr_t program_break
Definition at line 72 of file memory_manager.cpp.
Referenced by anonymous_namespace{memory_manager.cpp}::InitializeHeap().
program_break_end
caddr_t program_break_end
Definition at line 72 of file memory_manager.cpp.
Referenced by anonymous_namespace{memory_manager.cpp}::InitializeHeap().