My Project: kernel/mouse.hpp File Reference
mouse.hpp File Reference
#include "graphics.hpp"
Classes
class Mouse
Functions
void DrawMouseCursor (PixelWriter *pixel_writer, Vector2D< int > position)
void InitializeMouse ()
Variables
const int kMouseCursorWidth = 15
const int kMouseCursorHeight = 24
const PixelColor kMouseTransparentColor {0, 0, 1}
Function Documentation
DrawMouseCursor()
void DrawMouseCursor (PixelWriter * pixel_writer, Vector2D< int > position)
Definition at line 38 of file mouse.cpp.
References kMouseCursorHeight, kMouseCursorWidth, kMouseTransparentColor, anonymous_namespace{mouse.cpp}::mouse_cursor_shape, and PixelWriter::Write().
Referenced by InitializeMouse().
InitializeMouse()
void InitializeMouse ()
Definition at line 87 of file mouse.cpp.
References usb::HIDMouseDriver::default_observer, DrawMouseCursor(), Layer::ID(), kMouseCursorHeight, kMouseCursorWidth, kMouseTransparentColor, layer_manager, LayerManager::NewLayer(), FrameBufferConfig::pixel_format, screen_config, Layer::SetWindow(), and LayerManager::UpDown().
Referenced by KernelMainNewStack().
Variable Documentation
kMouseCursorHeight
const int kMouseCursorHeight = 24
Definition at line 6 of file mouse.hpp.
Referenced by DrawMouseCursor(), and InitializeMouse().
kMouseCursorWidth
const int kMouseCursorWidth = 15
Definition at line 5 of file mouse.hpp.
Referenced by DrawMouseCursor(), and InitializeMouse().
kMouseTransparentColor
const PixelColor kMouseTransparentColor {0, 0, 1}
Definition at line 7 of file mouse.hpp.
Referenced by DrawMouseCursor(), and InitializeMouse().