My Project: anonymous_namespace{frame_buffer.cpp} Namespace Reference
anonymous_namespace{frame_buffer.cpp} Namespace Reference
Functions
int BytesPerPixel (PixelFormat format)
uint8_t * FrameAddrAt (Vector2D< int > pos, const FrameBufferConfig &config)
int BytesPerScanLine (const FrameBufferConfig &config)
Vector2D< int > FrameBufferSize (const FrameBufferConfig &config)
Function Documentation
BytesPerPixel()
int anonymous_namespace{frame_buffer.cpp}::BytesPerPixel (PixelFormat format)
Definition at line 4 of file frame_buffer.cpp.
References kPixelBGRResv8BitPerColor, and kPixelRGBResv8BitPerColor.
Referenced by BytesPerScanLine(), FrameBuffer::Copy(), FrameAddrAt(), FrameBuffer::Initialize(), and FrameBuffer::Move().
BytesPerScanLine()
int anonymous_namespace{frame_buffer.cpp}::BytesPerScanLine (const FrameBufferConfig & config)
Definition at line 16 of file frame_buffer.cpp.
References BytesPerPixel(), FrameBufferConfig::pixel_format, and FrameBufferConfig::pixels_per_scan_line.
Referenced by FrameBuffer::Copy(), and FrameBuffer::Move().
FrameAddrAt()
uint8_t* anonymous_namespace{frame_buffer.cpp}::FrameAddrAt (Vector2D< int > pos, const FrameBufferConfig & config)
Definition at line 11 of file frame_buffer.cpp.
References BytesPerPixel(), FrameBufferConfig::frame_buffer, FrameBufferConfig::pixel_format, FrameBufferConfig::pixels_per_scan_line, Vector2D< T >::x, and Vector2D< T >::y.
Referenced by FrameBuffer::Copy(), and FrameBuffer::Move().
FrameBufferSize()
Vector2D<int> anonymous_namespace{frame_buffer.cpp}::FrameBufferSize (const FrameBufferConfig & config)
Definition at line 20 of file frame_buffer.cpp.
References FrameBufferConfig::horizontal_resolution, and FrameBufferConfig::vertical_resolution.
Referenced by FrameBuffer::Copy().