My Project: anonymous_namespace{device.cpp} Namespace Reference
anonymous_namespace{device.cpp} Namespace Reference
Classes
class ConfigurationDescriptorReader
Functions
usb::EndpointConfig MakeEPConfig (const usb::EndpointDescriptor &ep_desc)
usb::ClassDriver * NewClassDriver (usb::Device *dev, const usb::InterfaceDescriptor &if_desc)
void Log (LogLevel level, const usb::InterfaceDescriptor &if_desc)
void Log (LogLevel level, const usb::EndpointConfig &conf)
void Log (LogLevel level, const usb::HIDDescriptor &hid_desc)
SetupStageTRB MakeSetupStageTRB (usb::SetupData setup_data, int transfer_type)
DataStageTRB MakeDataStageTRB (const void *buf, int len, bool dir_in)
void Log (LogLevel level, const DataStageTRB &trb)
void Log (LogLevel level, const SetupStageTRB &trb)
void Log (LogLevel level, const TransferEventTRB &trb)
Variables
class anonymous_namespace{device.cpp}::ConfigurationDescriptorReader __attribute__
Function Documentation
Log() [1/6]
void anonymous_namespace{device.cpp}::Log (LogLevel level, const DataStageTRB & trb)
Definition at line 30 of file device.cpp.
References usb::xhci::DataStageTRB::data, usb::xhci::DataStageTRB::data_buffer_pointer, usb::xhci::DataStageTRB::direction, Log(), and usb::xhci::DataStageTRB::trb_transfer_length.
Log() [2/6]
void anonymous_namespace{device.cpp}::Log (LogLevel level, const SetupStageTRB & trb)
Definition at line 39 of file device.cpp.
References usb::xhci::SetupStageTRB::index, usb::xhci::SetupStageTRB::length, Log(), usb::xhci::SetupStageTRB::request, usb::xhci::SetupStageTRB::request_type, and usb::xhci::SetupStageTRB::value.
Log() [3/6]
void anonymous_namespace{device.cpp}::Log (LogLevel level, const TransferEventTRB & trb)
Definition at line 49 of file device.cpp.
References usb::EndpointID::Address(), usb::xhci::TransferEventTRB::completion_code, usb::xhci::TransferEventTRB::EndpointID(), usb::xhci::TransferEventTRB::event_data, usb::xhci::kTRBCompletionCodeToName, usb::xhci::kTRBTypeToName, usb::xhci::TransferEventTRB::Pointer(), usb::xhci::TransferEventTRB::slot_id, usb::xhci::TransferEventTRB::trb_transfer_length, and usb::xhci::TRB::trb_type.
Referenced by usb::xhci::Device::ControlIn(), usb::xhci::Device::ControlOut(), usb::Device::InitializePhase1(), usb::Device::InitializePhase2(), usb::xhci::Device::InterruptOut(), Log(), usb::Device::OnControlCompleted(), usb::Device::OnInterruptCompleted(), and usb::xhci::Device::OnTransferEventReceived().
Log() [4/6]
void anonymous_namespace{device.cpp}::Log (LogLevel level, const usb::EndpointConfig & conf)
Definition at line 83 of file device.cpp.
References usb::EndpointID::Address(), usb::EndpointConfig::ep_id, usb::EndpointConfig::ep_type, usb::EndpointConfig::interval, Log(), and usb::EndpointConfig::max_packet_size.
Log() [5/6]
void anonymous_namespace{device.cpp}::Log (LogLevel level, const usb::HIDDescriptor & hid_desc)
Definition at line 90 of file device.cpp.
References usb::HIDDescriptor::ClassDescriptor::descriptor_length, usb::HIDDescriptor::ClassDescriptor::descriptor_type, usb::HIDDescriptor::GetClassDescriptor(), usb::HIDDescriptor::hid_release, Log(), and usb::HIDDescriptor::num_descriptors.
Log() [6/6]
void anonymous_namespace{device.cpp}::Log (LogLevel level, const usb::InterfaceDescriptor & if_desc)
Definition at line 76 of file device.cpp.
References usb::InterfaceDescriptor::interface_class, usb::InterfaceDescriptor::interface_protocol, usb::InterfaceDescriptor::interface_sub_class, and Log().
MakeDataStageTRB()
DataStageTRB anonymous_namespace{device.cpp}::MakeDataStageTRB (const void * buf, int len, bool dir_in)
Definition at line 21 of file device.cpp.
References data, and dir_in.
Referenced by usb::xhci::Device::ControlIn(), and usb::xhci::Device::ControlOut().
MakeEPConfig()
usb::EndpointConfig anonymous_namespace{device.cpp}::MakeEPConfig (const usb::EndpointDescriptor & ep_desc)
Definition at line 44 of file device.cpp.
References usb::EndpointDescriptor::attributes, usb::EndpointDescriptor::dir_in, usb::EndpointDescriptor::endpoint_address, usb::EndpointConfig::ep_id, usb::EndpointConfig::ep_type, usb::EndpointConfig::interval, usb::EndpointDescriptor::interval, usb::EndpointConfig::max_packet_size, usb::EndpointDescriptor::max_packet_size, usb::EndpointDescriptor::number, and usb::EndpointDescriptor::transfer_type.
Referenced by usb::Device::InitializePhase2().
MakeSetupStageTRB()
SetupStageTRB anonymous_namespace{device.cpp}::MakeSetupStageTRB (usb::SetupData setup_data, int transfer_type)
Definition at line 10 of file device.cpp.
References usb::SetupData::data, usb::SetupData::index, usb::SetupData::length, usb::SetupData::request, usb::xhci::SetupStageTRB::request_type, usb::SetupData::request_type, transfer_type, and usb::SetupData::value.
Referenced by usb::xhci::Device::ControlIn(), and usb::xhci::Device::ControlOut().
NewClassDriver()
usb::ClassDriver* anonymous_namespace{device.cpp}::NewClassDriver (usb::Device * dev, const usb::InterfaceDescriptor & if_desc)
Definition at line 56 of file device.cpp.
References usb::HIDKeyboardDriver::default_observer, usb::HIDMouseDriver::default_observer, usb::InterfaceDescriptor::interface_class, usb::InterfaceDescriptor::interface_number, usb::InterfaceDescriptor::interface_protocol, and usb::InterfaceDescriptor::interface_sub_class.
Referenced by usb::Device::InitializePhase2().
Variable Documentation
__attribute__
class anonymous_namespace{device.cpp}::ConfigurationDescriptorReader anonymous_namespace{device.cpp}::__attribute__