My Project: usb::xhci Namespace Reference
usb::xhci Namespace Reference
Classes
union AddressDeviceCommandTRB
struct CapabilityRegisters
union CommandCompletionEventTRB
union CONFIG_Bitmap
union ConfigureEndpointCommandTRB
class Controller
union CRCR_Bitmap
union DataStageTRB
union DBOFF_Bitmap
union DCBAAP_Bitmap
class Device
struct DeviceContext
struct DeviceContextIndex
class DeviceManager
union Doorbell_Bitmap
class DoorbellRegister
union EnableSlotCommandTRB
union EndpointContext
union ERDP_Bitmap
union ERSTBA_Bitmap
union ERSTSZ_Bitmap
class EventRing
union EventRingSegmentTableEntry
union ExtendedRegister_Bitmap
拡張レジスタの共通ヘッダ構造
class ExtendedRegisterList
union HCCPARAMS1_Bitmap
union HCCPARAMS2_Bitmap
union HCSPARAMS1_Bitmap
union HCSPARAMS2_Bitmap
union HCSPARAMS3_Bitmap
union IMAN_Bitmap
union IMOD_Bitmap
struct InputContext
struct InputControlContext
struct InterrupterRegisterSet
union LinkTRB
union NoOpCommandTRB
union NoOpTRB
union NormalTRB
struct OperationalRegisters
class Port
union PORTHLPMC_Bitmap
union PORTLI_Bitmap
union PORTPMSC_Bitmap
struct PortRegisterSet
union PORTSC_Bitmap
union PortStatusChangeEventTRB
class Ring
Command/Transfer Ring を表すクラス．
union RTSOFF_Bitmap
union SetupStageTRB
union SlotContext
union StatusStageTRB
union StopEndpointCommandTRB
union TransferEventTRB
union TRB
union USBCMD_Bitmap
union USBLEGSUP_Bitmap
union USBSTS_Bitmap
Typedefs
using PortRegisterSetArray = ArrayWrapper< PortRegisterSet >
using InterrupterRegisterSetArray = ArrayWrapper< InterrupterRegisterSet >
using DoorbellRegisterArray = ArrayWrapper< DoorbellRegister >
Functions
union usb::xhci::SlotContext __attribute__ ((packed))
template<class ToType , class FromType >
ToType * TRBDynamicCast (FromType *trb)
TRBDynamicCast casts a trb pointer to other type of TRB.
Error ConfigurePort (Controller &xhc, Port &port)
Error ConfigureEndpoints (Controller &xhc, Device &dev)
Error ProcessEvent (Controller &xhc)
イベントリングに登録されたイベントを高々1つ処理する．
void Initialize ()
void ProcessEvents ()
Variables
struct usb::xhci::DeviceContextIndex __attribute__
const int kFullSpeed = 1
const int kLowSpeed = 2
const int kHighSpeed = 3
const int kSuperSpeed = 4
const int kSuperSpeedPlus = 5
const std::array< const char *, 37 > kTRBCompletionCodeToName
const std::array< const char *, 64 > kTRBTypeToName
Controller * controller
Typedef Documentation
DoorbellRegisterArray
using usb::xhci::DoorbellRegisterArray = typedef ArrayWrapper<DoorbellRegister>
Definition at line 373 of file registers.hpp.
InterrupterRegisterSetArray
using usb::xhci::InterrupterRegisterSetArray = typedef ArrayWrapper<InterrupterRegisterSet>
Definition at line 350 of file registers.hpp.
PortRegisterSetArray
using usb::xhci::PortRegisterSetArray = typedef ArrayWrapper<PortRegisterSet>
Definition at line 273 of file registers.hpp.
Function Documentation
__attribute__()
union usb::xhci::SlotContext usb::xhci::__attribute__ ((packed))
ConfigureEndpoints()
Error usb::xhci::ConfigureEndpoints (Controller & xhc, Device & dev)
Definition at line 448 of file xhci.cpp.
References usb::xhci::Device::AllocTransferRing(), usb::xhci::Controller::CommandRing(), usb::xhci::SlotContext::context_entries, usb::xhci::Device::DeviceContext(), usb::xhci::Controller::DoorbellRegisterAt(), usb::xhci::InputContext::EnableEndpoint(), usb::xhci::InputContext::EnableSlotContext(), usb::Device::EndpointConfigs(), ep_type, usb::xhci::InputContext::input_control_context, usb::xhci::Device::InputContext(), interval, usb::kBulk, usb::kControl, kFullSpeed, usb::kInterrupt, usb::kIsochronous, kLowSpeed, Error::kSuccess, kSuperSpeedPlus, Error::kUnknownXHCISpeedID, MAKE_ERROR, anonymous_namespace{xhci.cpp}::MostSignificantBit(), usb::Device::NumEndpointConfigs(), anonymous_namespace{xhci.cpp}::port_config_phase, port_id, port_speed, usb::xhci::Controller::PortAt(), usb::xhci::Ring::Push(), usb::xhci::DoorbellRegister::Ring(), usb::xhci::SlotContext::root_hub_port_num, usb::xhci::DeviceContext::slot_context, usb::xhci::InputContext::slot_context, usb::xhci::Device::SlotID(), usb::xhci::Port::Speed(), and type.
Referenced by anonymous_namespace{xhci.cpp}::OnEvent().
ConfigurePort()
Error usb::xhci::ConfigurePort (Controller & xhc, Port & port)
Definition at line 441 of file xhci.cpp.
References Error::kSuccess, MAKE_ERROR, usb::xhci::Port::Number(), anonymous_namespace{xhci.cpp}::port_config_phase, and anonymous_namespace{xhci.cpp}::ResetPort().
Referenced by Initialize().
Initialize()
void usb::xhci::Initialize ()
Definition at line 534 of file xhci.cpp.
References pci::Device::bus, pci::ConfigureMSIFixedDestination(), ConfigurePort(), controller, pci::Device::device, pci::devices, WithError< T >::error, pci::Device::function, usb::xhci::Controller::Initialize(), kDebug, kError, pci::kFixed, kInfo, pci::kLevel, InterruptVector::kXHCI, Log(), usb::xhci::Controller::MaxPorts(), Error::Name(), pci::num_device, usb::xhci::Controller::PortAt(), pci::ReadBar(), pci::ReadVendorId(), usb::xhci::Controller::Run(), anonymous_namespace{xhci.cpp}::SwitchEhci2Xhci(), and WithError< T >::value.
Referenced by KernelMainNewStack().
ProcessEvent()
Error usb::xhci::ProcessEvent (Controller & xhc)
イベントリングに登録されたイベントを高々1つ処理する．
xhc のプライマリイベントリングの先頭のイベントを処理する． イベントが無ければ即座に Error::kSuccess を返す．
Returns
イベントを正常に処理できたら Error::kSuccess
Definition at line 513 of file xhci.cpp.
References usb::xhci::EventRing::Front(), usb::xhci::EventRing::HasFront(), Error::kNotImplemented, Error::kSuccess, MAKE_ERROR, anonymous_namespace{xhci.cpp}::OnEvent(), usb::xhci::EventRing::Pop(), and usb::xhci::Controller::PrimaryEventRing().
Referenced by ProcessEvents().
ProcessEvents()
void usb::xhci::ProcessEvents ()
Definition at line 597 of file xhci.cpp.
References controller, usb::xhci::EventRing::HasFront(), kError, Log(), usb::xhci::Controller::PrimaryEventRing(), and ProcessEvent().
Referenced by KernelMainNewStack().
TRBDynamicCast()
template<class ToType , class FromType > ToType* usb::xhci::TRBDynamicCast (FromType * trb)
TRBDynamicCast casts a trb pointer to other type of TRB.
Parameters
trb source pointer
Returns
casted pointer if the source TRB's type is equal to the resulting type. nullptr otherwise.
Definition at line 453 of file trb.hpp.
Variable Documentation
__attribute__
union usb::xhci::TRB usb::xhci::__attribute__
controller
Controller * usb::xhci::controller
Definition at line 532 of file xhci.cpp.
Referenced by Initialize(), and ProcessEvents().
kFullSpeed
const int usb::xhci::kFullSpeed = 1
Definition at line 10 of file speed.hpp.
Referenced by ConfigureEndpoints().
kHighSpeed
const int usb::xhci::kHighSpeed = 3
Definition at line 12 of file speed.hpp.
kLowSpeed
const int usb::xhci::kLowSpeed = 2
Definition at line 11 of file speed.hpp.
Referenced by ConfigureEndpoints().
kSuperSpeed
const int usb::xhci::kSuperSpeed = 4
Definition at line 13 of file speed.hpp.
kSuperSpeedPlus
const int usb::xhci::kSuperSpeedPlus = 5
Definition at line 14 of file speed.hpp.
Referenced by ConfigureEndpoints().
kTRBCompletionCodeToName
const std::array< const char *, 37 > usb::xhci::kTRBCompletionCodeToName
Definition at line 4 of file trb.cpp.
Referenced by anonymous_namespace{device.cpp}::Log().
kTRBTypeToName
const std::array< const char *, 64 > usb::xhci::kTRBTypeToName
Definition at line 44 of file trb.cpp.
Referenced by anonymous_namespace{device.cpp}::Log(), anonymous_namespace{xhci.cpp}::OnEvent(), and usb::xhci::Device::OnTransferEventReceived().