My Project: usb Namespace Reference
usb Namespace Reference
Namespaces
descriptor_type
request
request_type
xhci
Classes
class Allocator
標準コンテナ用のメモリアロケータ
class ArrayMap
class ClassDriver
struct ConfigurationDescriptor
class Device
struct DeviceDescriptor
struct EndpointConfig
struct EndpointDescriptor
class EndpointID
class HIDBaseDriver
struct HIDDescriptor
class HIDKeyboardDriver
class HIDMouseDriver
struct InterfaceDescriptor
struct SetupData
Enumerations
enum EndpointType { EndpointType::kControl = 0, EndpointType::kIsochronous = 1, EndpointType::kBulk = 2, EndpointType::kInterrupt = 3 }
Functions
struct usb::DeviceDescriptor __attribute__ ((packed))
template<class T >
T * DescriptorDynamicCast (uint8_t *desc_data)
template<class T >
const T * DescriptorDynamicCast (const uint8_t *desc_data)
Error GetDescriptor (Device &dev, EndpointID ep_id, uint8_t desc_type, uint8_t desc_index, void *buf, int len, bool debug)
Error SetConfiguration (Device &dev, EndpointID ep_id, uint8_t config_value, bool debug)
void * AllocMem (size_t size, unsigned int alignment, unsigned int boundary)
指定されたバイト数のメモリ領域を確保して先頭ポインタを返す．
void FreeMem (void *p)
指定されたメモリ領域を解放する．本当に解放することは保証されない．
template<class T >
T * AllocArray (size_t num_obj, unsigned int alignment, unsigned int boundary)
bool operator== (SetupData lhs, SetupData rhs)
Variables
constexpr EndpointID kDefaultControlPipeID {0, true}
uint8_t memory_pool [kMemoryPoolSize]
uintptr_t alloc_ptr = reinterpret_cast<uintptr_t>(memory_pool)
static const size_t kMemoryPoolSize = 4096 * 32
動的メモリ確保のためのメモリプールの最大容量（バイト）
Enumeration Type Documentation
EndpointType
enum usb::EndpointType strong
Enumerator
kControl
kIsochronous
kBulk
kInterrupt
Definition at line 12 of file endpoint.hpp.
Function Documentation
__attribute__()
struct usb::SetupData usb::__attribute__ ((packed))
AllocArray()
template<class T > T* usb::AllocArray (size_t num_obj, unsigned int alignment, unsigned int boundary)
Definition at line 29 of file memory.hpp.
References AllocMem().
AllocMem()
void * usb::AllocMem (size_t size, unsigned int alignment, unsigned int boundary)
指定されたバイト数のメモリ領域を確保して先頭ポインタを返す．
先頭アドレスが alignment に揃ったメモリ領域を確保する． size <= boundary ならメモリ領域が boundary を跨がないことを保証する． boundary は典型的にはページ境界を跨がないように 4096 を指定する．
Parameters
size 確保するメモリ領域のサイズ（バイト単位）
alignment メモリ領域のアライメント制約．0 なら制約しない．
boundary 確保したメモリ領域が跨いではいけない境界．0 なら制約しない．
Returns
確保できなかった場合は nullptr
Definition at line 21 of file memory.cpp.
References alloc_ptr, anonymous_namespace{memory.cpp}::Ceil(), kMemoryPoolSize, and memory_pool.
Referenced by AllocArray(), usb::xhci::Controller::Initialize(), usb::HIDKeyboardDriver::operator new(), and usb::HIDMouseDriver::operator new().
DescriptorDynamicCast() [1/2]
template<class T > const T* usb::DescriptorDynamicCast (const uint8_t * desc_data)
Definition at line 130 of file descriptor.hpp.
References kType.
DescriptorDynamicCast() [2/2]
template<class T > T* usb::DescriptorDynamicCast (uint8_t * desc_data)
Definition at line 122 of file descriptor.hpp.
References kType.
FreeMem()
void usb::FreeMem (void * p)
指定されたメモリ領域を解放する．本当に解放することは保証されない．
Definition at line 42 of file memory.cpp.
Referenced by usb::Allocator< T, Alignment, Boundary >::deallocate(), usb::xhci::DeviceManager::Initialize(), usb::xhci::Ring::Initialize(), usb::xhci::EventRing::Initialize(), usb::HIDMouseDriver::operator delete(), usb::HIDKeyboardDriver::operator delete(), usb::xhci::DeviceManager::Remove(), and usb::xhci::Ring::~Ring().
GetDescriptor()
Error usb::GetDescriptor (Device & dev, EndpointID ep_id, uint8_t desc_type, uint8_t desc_index, void * buf, int len, bool debug)
Definition at line 257 of file device.cpp.
References usb::SetupData::bits, usb::Device::ControlIn(), usb::request_type::kDevice, usb::request::kGetDescriptor, usb::request_type::kIn, usb::request_type::kStandard, and usb::SetupData::request_type.
Referenced by usb::Device::InitializePhase1(), and usb::Device::StartInitialize().
operator==()
bool usb::operator== (SetupData lhs, SetupData rhs) inline
Definition at line 84 of file setupdata.hpp.
References usb::SetupData::data, usb::SetupData::index, usb::SetupData::length, usb::SetupData::request, usb::SetupData::request_type, and usb::SetupData::value.
SetConfiguration()
Error usb::SetConfiguration (Device & dev, EndpointID ep_id, uint8_t config_value, bool debug)
Definition at line 271 of file device.cpp.
References usb::SetupData::bits, usb::Device::ControlOut(), usb::request_type::kDevice, usb::request_type::kOut, usb::request::kSetConfiguration, usb::request_type::kStandard, and usb::SetupData::request_type.
Referenced by usb::Device::InitializePhase2().
Variable Documentation
alloc_ptr
uintptr_t usb::alloc_ptr = reinterpret_cast<uintptr_t>(memory_pool)
Definition at line 19 of file memory.cpp.
Referenced by AllocMem().
kDefaultControlPipeID
constexpr EndpointID usb::kDefaultControlPipeID {0, true} constexpr
Definition at line 50 of file endpoint.hpp.
Referenced by usb::Device::InitializePhase1(), usb::Device::InitializePhase2(), usb::HIDBaseDriver::OnEndpointsConfigured(), and usb::Device::StartInitialize().
kMemoryPoolSize
const size_t usb::kMemoryPoolSize = 4096 * 32 static
動的メモリ確保のためのメモリプールの最大容量（バイト）
Definition at line 13 of file memory.hpp.
Referenced by AllocMem().
memory_pool
uint8_t usb::memory_pool[kMemoryPoolSize]
Definition at line 18 of file memory.cpp.
Referenced by AllocMem().