My Project: anonymous_namespace{timer.cpp} Namespace Reference
anonymous_namespace{timer.cpp} Namespace Reference
Variables
const uint32_t kCountMax = 0xffffffffu
volatile uint32_t & lvt_timer = *reinterpret_cast<uint32_t*>(0xfee00320)
volatile uint32_t & initial_count = *reinterpret_cast<uint32_t*>(0xfee00380)
volatile uint32_t & current_count = *reinterpret_cast<uint32_t*>(0xfee00390)
volatile uint32_t & divide_config = *reinterpret_cast<uint32_t*>(0xfee003e0)
Variable Documentation
current_count
volatile uint32_t& anonymous_namespace{timer.cpp}::current_count = *reinterpret_cast<uint32_t*>(0xfee00390)
Definition at line 11 of file timer.cpp.
Referenced by LAPICTimerElapsed().
divide_config
volatile uint32_t& anonymous_namespace{timer.cpp}::divide_config = *reinterpret_cast<uint32_t*>(0xfee003e0)
Definition at line 12 of file timer.cpp.
Referenced by InitializeLAPICTimer().
initial_count
volatile uint32_t& anonymous_namespace{timer.cpp}::initial_count = *reinterpret_cast<uint32_t*>(0xfee00380)
Definition at line 10 of file timer.cpp.
Referenced by InitializeLAPICTimer(), StartLAPICTimer(), and StopLAPICTimer().
kCountMax
const uint32_t anonymous_namespace{timer.cpp}::kCountMax = 0xffffffffu
Definition at line 8 of file timer.cpp.
Referenced by LAPICTimerElapsed(), and StartLAPICTimer().
lvt_timer
volatile uint32_t& anonymous_namespace{timer.cpp}::lvt_timer = *reinterpret_cast<uint32_t*>(0xfee00320)
Definition at line 9 of file timer.cpp.
Referenced by InitializeLAPICTimer().