My Project: anonymous_namespace{pci.cpp} Namespace Reference
anonymous_namespace{pci.cpp} Namespace Reference
Functions
uint32_t MakeAddress (uint8_t bus, uint8_t device, uint8_t function, uint8_t reg_addr)
Error AddDevice (const Device &device)
devices[num_device] に情報を書き込み num_device をインクリメントする．
Error ScanBus (uint8_t bus)
指定のバス番号の各デバイスをスキャンする． 有効なデバイスを見つけたら ScanDevice を実行する．
Error ScanFunction (uint8_t bus, uint8_t device, uint8_t function)
指定のファンクションを devices に追加する． もし PCI-PCI ブリッジなら，セカンダリバスに対し ScanBus を実行する
Error ScanDevice (uint8_t bus, uint8_t device)
指定のデバイス番号の各ファンクションをスキャンする． 有効なファンクションを見つけたら ScanFunction を実行する．
MSICapability ReadMSICapability (const Device &dev, uint8_t cap_addr)
指定された MSI ケーパビリティ構造を読み取る
void WriteMSICapability (const Device &dev, uint8_t cap_addr, const MSICapability &msi_cap)
指定された MSI ケーパビリティ構造に書き込む
Error ConfigureMSIRegister (const Device &dev, uint8_t cap_addr, uint32_t msg_addr, uint32_t msg_data, unsigned int num_vector_exponent)
指定された MSI レジスタを設定する
Error ConfigureMSIXRegister (const Device &dev, uint8_t cap_addr, uint32_t msg_addr, uint32_t msg_data, unsigned int num_vector_exponent)
指定された MSI レジスタを設定する
Function Documentation
AddDevice()
Error anonymous_namespace{pci.cpp}::AddDevice (const Device & device)
devices[num_device] に情報を書き込み num_device をインクリメントする．
Definition at line 36 of file pci.cpp.
References pci::devices, Error::kFull, Error::kSuccess, MAKE_ERROR, and pci::num_device.
Referenced by ScanFunction().
ConfigureMSIRegister()
Error anonymous_namespace{pci.cpp}::ConfigureMSIRegister (const Device & dev, uint8_t cap_addr, uint32_t msg_addr, uint32_t msg_data, unsigned int num_vector_exponent)
指定された MSI レジスタを設定する
Definition at line 161 of file pci.cpp.
References Error::kSuccess, MAKE_ERROR, msg_addr, msg_data, ReadMSICapability(), and WriteMSICapability().
Referenced by pci::ConfigureMSI().
ConfigureMSIXRegister()
Error anonymous_namespace{pci.cpp}::ConfigureMSIXRegister (const Device & dev, uint8_t cap_addr, uint32_t msg_addr, uint32_t msg_data, unsigned int num_vector_exponent)
指定された MSI レジスタを設定する
Definition at line 182 of file pci.cpp.
References Error::kNotImplemented, and MAKE_ERROR.
Referenced by pci::ConfigureMSI().
MakeAddress()
uint32_t anonymous_namespace{pci.cpp}::MakeAddress (uint8_t bus, uint8_t device, uint8_t function, uint8_t reg_addr)
Make a 32 bits address to set to CONFIG_ADDRESS register. [CONFIG_ADDRESS]
bit position description
31 Enable bit.
Set to 1 to enable writing and reading PCI Configuration Area.
30:24 Reservation
23:16 Bus number (0 - 255)
15:11 Device number (0 - 31)
10:8 Function number (0 - 7)
7:0 Register offset (0 - 255) per 4 byte
Definition at line 22 of file pci.cpp.
References bits.
Referenced by pci::ReadBusNumbers(), pci::ReadClassCode(), pci::ReadConfReg(), pci::ReadDeviceId(), pci::ReadHeaderType(), pci::ReadVendorId(), and pci::WriteConfReg().
ReadMSICapability()
MSICapability anonymous_namespace{pci.cpp}::ReadMSICapability (const Device & dev, uint8_t cap_addr)
指定された MSI ケーパビリティ構造を読み取る
Parameters
dev MSI ケーパビリティを読み込む PCI デバイス
cap_addr MSI ケーパビリティレジスタのコンフィグレーション空間アドレス
Definition at line 113 of file pci.cpp.
References pci::MSICapability::data, and pci::ReadConfReg().
Referenced by ConfigureMSIRegister().
ScanBus()
Error anonymous_namespace pci anonymous_namespace{pci.cpp}::cpp::ScanBus (uint8_t bus)
指定のバス番号の各デバイスをスキャンする． 有効なデバイスを見つけたら ScanDevice を実行する．
Definition at line 96 of file pci.cpp.
References Error::kSuccess, MAKE_ERROR, pci::ReadVendorId(), and ScanDevice().
Referenced by pci::ScanAllBus(), and ScanFunction().
ScanDevice()
Error anonymous_namespace{pci.cpp}::ScanDevice (uint8_t bus, uint8_t device)
指定のデバイス番号の各ファンクションをスキャンする． 有効なファンクションを見つけたら ScanFunction を実行する．
Definition at line 73 of file pci.cpp.
References pci::IsSingleFunctionDevice(), Error::kSuccess, MAKE_ERROR, pci::ReadHeaderType(), pci::ReadVendorId(), and ScanFunction().
Referenced by ScanBus().
ScanFunction()
Error anonymous_namespace{pci.cpp}::ScanFunction (uint8_t bus, uint8_t device, uint8_t function)
指定のファンクションを devices に追加する． もし PCI-PCI ブリッジなら，セカンダリバスに対し ScanBus を実行する
Definition at line 52 of file pci.cpp.
References AddDevice(), Error::kSuccess, MAKE_ERROR, pci::ReadBusNumbers(), pci::ReadClassCode(), pci::ReadHeaderType(), and ScanBus().
Referenced by ScanDevice().
WriteMSICapability()
void anonymous_namespace{pci.cpp}::WriteMSICapability (const Device & dev, uint8_t cap_addr, const MSICapability & msi_cap)
指定された MSI ケーパビリティ構造に書き込む
Parameters
dev MSI ケーパビリティを読み込む PCI デバイス
cap_addr MSI ケーパビリティレジスタのコンフィグレーション空間アドレス
msi_cap 書き込む値
Definition at line 141 of file pci.cpp.
References pci::MSICapability::addr_64_capable, pci::MSICapability::data, pci::MSICapability::mask_bits, pci::MSICapability::msg_addr, pci::MSICapability::msg_data, pci::MSICapability::msg_upper_addr, pci::MSICapability::pending_bits, pci::MSICapability::per_vector_mask_capable, and pci::WriteConfReg().
Referenced by ConfigureMSIRegister().