My Project: acpi Namespace Reference
acpi Namespace Reference
Classes
struct DescriptionHeader
struct FADT
struct RSDP
struct XSDT
Functions
void WaitMilliseconds (unsigned long msec)
void Initialize (const RSDP &rsdp)
struct acpi::RSDP __attribute__ ((packed))
Variables
const FADT * fadt
const int kPMTimerFreq = 3579545
Function Documentation
__attribute__()
struct acpi::FADT acpi::__attribute__ ((packed))
Initialize()
void acpi::Initialize (const RSDP & rsdp)
Definition at line 82 of file acpi.cpp.
References acpi::XSDT::Count(), fadt, acpi::XSDT::header, acpi::RSDP::IsValid(), acpi::DescriptionHeader::IsValid(), kError, Log(), and acpi::RSDP::xsdt_address.
Referenced by KernelMainNewStack().
WaitMilliseconds()
void acpi::WaitMilliseconds (unsigned long msec)
Definition at line 68 of file acpi.cpp.
References fadt, acpi::FADT::flags, IoIn32(), kPMTimerFreq, and acpi::FADT::pm_tmr_blk.
Referenced by InitializeLAPICTimer().
Variable Documentation
fadt
const FADT * acpi::fadt
Definition at line 66 of file acpi.cpp.
Referenced by Initialize(), and WaitMilliseconds().
kPMTimerFreq
const int acpi::kPMTimerFreq = 3579545
Definition at line 60 of file acpi.hpp.
Referenced by WaitMilliseconds().