My Project: pci Namespace Reference
pci Namespace Reference
Classes
union CapabilityHeader
struct ClassCode
struct Device
PCI デバイスを操作するための基礎データを格納する
struct MSICapability
Enumerations
enum MSITriggerMode { MSITriggerMode::kEdge = 0, MSITriggerMode::kLevel = 1 }
enum MSIDeliveryMode {
MSIDeliveryMode::kFixed = 0b000, MSIDeliveryMode::kLowestPriority = 0b001, MSIDeliveryMode::kSMI = 0b010, MSIDeliveryMode::kNMI = 0b100,
MSIDeliveryMode::kINIT = 0b101, MSIDeliveryMode::kExtINT = 0b111
}
Functions
void WriteAddress (uint32_t address)
CONFIG_ADDRESS に指定された整数を書き込む
void WriteData (uint32_t value)
CONFIG_DATA に指定された整数を書き込む
uint32_t ReadData ()
CONFIG_DATA から 32 ビット整数を読み込む
uint16_t ReadVendorId (uint8_t bus, uint8_t device, uint8_t function)
ベンダ ID レジスタを読み取る（全ヘッダタイプ共通）
uint16_t ReadDeviceId (uint8_t bus, uint8_t device, uint8_t function)
デバイス ID レジスタを読み取る（全ヘッダタイプ共通）
ClassCode ReadClassCode (uint8_t bus, uint8_t device, uint8_t function)
クラスコードレジスタを読み取る（全ヘッダタイプ共通）
uint32_t ReadConfReg (const Device &dev, uint8_t reg_addr)
void WriteConfReg (const Device &dev, uint8_t reg_addr, uint32_t value)
uint8_t ReadHeaderType (uint8_t bus, uint8_t device, uint8_t function)
ヘッダタイプレジスタを読み取る（全ヘッダタイプ共通）
uint32_t ReadBusNumbers (uint8_t bus, uint8_t device, uint8_t function)
バス番号レジスタを読み取る（ヘッダタイプ 1 用）
bool IsSingleFunctionDevice (uint8_t header_type)
単一ファンクションの場合に真を返す
Error ScanAllBus ()
PCI デバイスをすべて探索し devices に格納する
WithError< uint64_t > ReadBar (Device &device, unsigned int bar_index)
CapabilityHeader ReadCapabilityHeader (const Device &dev, uint8_t addr)
Error ConfigureMSI (const Device &dev, uint32_t msg_addr, uint32_t msg_data, unsigned int num_vector_exponent)
Error ConfigureMSIFixedDestination (const Device &dev, uint8_t apic_id, MSITriggerMode trigger_mode, MSIDeliveryMode delivery_mode, uint8_t vector, unsigned int num_vector_exponent)
uint16_t ReadVendorId (const Device &dev)
constexpr uint8_t CalcBarAddress (unsigned int bar_index)
union pci::CapabilityHeader __attribute__ ((packed))
Variables
const uint16_t kConfigAddress = 0x0cf8
CONFIG_ADDRESS レジスタの IO ポートアドレス
const uint16_t kConfigData = 0x0cfc
CONFIG_DATA レジスタの IO ポートアドレス
std::array< Device, 32 > devices
ScanAllBus() により発見された PCI デバイスの一覧
int num_device
devices の有効な要素の数
const uint8_t kCapabilityMSI = 0x05
const uint8_t kCapabilityMSIX = 0x11
enum pci::MSITriggerMode __attribute__
Enumeration Type Documentation
MSIDeliveryMode
enum pci::MSIDeliveryMode strong
Enumerator
kFixed
kLowestPriority
kSMI
kNMI
kINIT
kExtINT
Definition at line 138 of file pci.hpp.
MSITriggerMode
enum pci::MSITriggerMode strong
Enumerator
kEdge
kLevel
Definition at line 133 of file pci.hpp.
Function Documentation
__attribute__()
union pci::CapabilityHeader pci::__attribute__ ((packed))
CalcBarAddress()
constexpr uint8_t pci::CalcBarAddress (unsigned int bar_index) constexpr
Definition at line 89 of file pci.hpp.
Referenced by ReadBar().
ConfigureMSI()
Error pci::ConfigureMSI (const Device & dev, uint32_t msg_addr, uint32_t msg_data, unsigned int num_vector_exponent)
Definition at line 297 of file pci.cpp.
References anonymous_namespace{pci.cpp}::ConfigureMSIRegister(), anonymous_namespace{pci.cpp}::ConfigureMSIXRegister(), header, kCapabilityMSI, kCapabilityMSIX, Error::kNoPCIMSI, MAKE_ERROR, msg_addr, msg_data, ReadCapabilityHeader(), and ReadConfReg().
Referenced by ConfigureMSIFixedDestination().
ConfigureMSIFixedDestination()
Error pci::ConfigureMSIFixedDestination (const Device & dev, uint8_t apic_id, MSITriggerMode trigger_mode, MSIDeliveryMode delivery_mode, uint8_t vector, unsigned int num_vector_exponent)
Definition at line 319 of file pci.cpp.
References ConfigureMSI(), kLevel, msg_addr, and msg_data.
Referenced by usb::xhci::Initialize().
IsSingleFunctionDevice()
bool pci::IsSingleFunctionDevice (uint8_t header_type)
単一ファンクションの場合に真を返す
Definition at line 242 of file pci.cpp.
Referenced by ScanAllBus(), and anonymous_namespace{pci.cpp}::ScanDevice().
ReadBar()
WithError< uint64_t > pci::ReadBar (Device & device, unsigned int bar_index)
Definition at line 266 of file pci.cpp.
References CalcBarAddress(), Error::kIndexOutOfRange, Error::kSuccess, MAKE_ERROR, and ReadConfReg().
Referenced by usb::xhci::Initialize().
ReadBusNumbers()
uint32_t pci::ReadBusNumbers (uint8_t bus, uint8_t device, uint8_t function)
バス番号レジスタを読み取る（ヘッダタイプ 1 用）
返される 32 ビット整数の構造は次の通り
23:16 : サブオーディネイトバス番号
15:8 : セカンダリバス番号
7:0 : リビジョン番号
Definition at line 237 of file pci.cpp.
References anonymous_namespace{pci.cpp}::MakeAddress(), ReadData(), and WriteAddress().
Referenced by anonymous_namespace{pci.cpp}::ScanFunction().
ReadCapabilityHeader()
CapabilityHeader pci::ReadCapabilityHeader (const Device & dev, uint8_t addr)
Definition at line 291 of file pci.cpp.
References header, and ReadConfReg().
Referenced by ConfigureMSI().
ReadClassCode()
ClassCode pci::ReadClassCode (uint8_t bus, uint8_t device, uint8_t function)
クラスコードレジスタを読み取る（全ヘッダタイプ共通）
返される 32 ビット整数の構造は次の通り
31:24 : ベースクラス
23:16 : サブクラス
15:8 : インターフェース
7:0 : リビジョン
Definition at line 213 of file pci.cpp.
References pci::ClassCode::base, pci::ClassCode::interface, anonymous_namespace{pci.cpp}::MakeAddress(), ReadData(), pci::ClassCode::sub, and WriteAddress().
Referenced by InitializePCI(), and anonymous_namespace{pci.cpp}::ScanFunction().
ReadConfReg()
uint32_t pci::ReadConfReg (const Device & dev, uint8_t reg_addr)
Definition at line 223 of file pci.cpp.
References pci::Device::bus, pci::Device::device, pci::Device::function, anonymous_namespace{pci.cpp}::MakeAddress(), ReadData(), and WriteAddress().
Referenced by ConfigureMSI(), ReadBar(), ReadCapabilityHeader(), anonymous_namespace{pci.cpp}::ReadMSICapability(), and anonymous_namespace{xhci.cpp}::SwitchEhci2Xhci().
ReadData()
uint32_t pci::ReadData ()
CONFIG_DATA から 32 ビット整数を読み込む
Definition at line 199 of file pci.cpp.
References IoIn32(), and kConfigData.
Referenced by ReadBusNumbers(), ReadClassCode(), ReadConfReg(), ReadDeviceId(), ReadHeaderType(), and ReadVendorId().
ReadDeviceId()
uint16_t pci::ReadDeviceId (uint8_t bus, uint8_t device, uint8_t function)
デバイス ID レジスタを読み取る（全ヘッダタイプ共通）
Definition at line 208 of file pci.cpp.
References anonymous_namespace{pci.cpp}::MakeAddress(), ReadData(), and WriteAddress().
ReadHeaderType()
uint8_t pci::ReadHeaderType (uint8_t bus, uint8_t device, uint8_t function)
ヘッダタイプレジスタを読み取る（全ヘッダタイプ共通）
Definition at line 232 of file pci.cpp.
References anonymous_namespace{pci.cpp}::MakeAddress(), ReadData(), and WriteAddress().
Referenced by ScanAllBus(), anonymous_namespace{pci.cpp}::ScanDevice(), and anonymous_namespace{pci.cpp}::ScanFunction().
ReadVendorId() [1/2]
uint16_t pci::ReadVendorId (const Device & dev) inline
Definition at line 58 of file pci.hpp.
References pci::Device::bus, pci::Device::device, pci::Device::function, and ReadVendorId().
ReadVendorId() [2/2]
uint16_t pci::ReadVendorId (uint8_t bus, uint8_t device, uint8_t function)
ベンダ ID レジスタを読み取る（全ヘッダタイプ共通）
Definition at line 203 of file pci.cpp.
References anonymous_namespace{pci.cpp}::MakeAddress(), ReadData(), and WriteAddress().
Referenced by usb::xhci::Initialize(), InitializePCI(), ReadVendorId(), ScanAllBus(), anonymous_namespace{pci.cpp}::ScanBus(), anonymous_namespace{pci.cpp}::ScanDevice(), and anonymous_namespace{xhci.cpp}::SwitchEhci2Xhci().
ScanAllBus()
Error pci::ScanAllBus ()
PCI デバイスをすべて探索し devices に格納する
バス 0 から再帰的に PCI デバイスを探索し、 devices の先頭から詰めて書き込む 発見したデバイスの数を num_device に設定する
Definition at line 246 of file pci.cpp.
References IsSingleFunctionDevice(), Error::kSuccess, MAKE_ERROR, num_device, ReadHeaderType(), ReadVendorId(), and anonymous_namespace{pci.cpp}::ScanBus().
Referenced by InitializePCI().
WriteAddress()
void pci::WriteAddress (uint32_t address)
CONFIG_ADDRESS に指定された整数を書き込む
Definition at line 191 of file pci.cpp.
References IoOut32(), and kConfigAddress.
Referenced by ReadBusNumbers(), ReadClassCode(), ReadConfReg(), ReadDeviceId(), ReadHeaderType(), ReadVendorId(), and WriteConfReg().
WriteConfReg()
void pci::WriteConfReg (const Device & dev, uint8_t reg_addr, uint32_t value)
Definition at line 227 of file pci.cpp.
References pci::Device::bus, pci::Device::device, pci::Device::function, anonymous_namespace{pci.cpp}::MakeAddress(), value, WriteAddress(), and WriteData().
Referenced by anonymous_namespace{xhci.cpp}::SwitchEhci2Xhci(), and anonymous_namespace{pci.cpp}::WriteMSICapability().
WriteData()
void pci::WriteData (uint32_t value)
CONFIG_DATA に指定された整数を書き込む
Definition at line 195 of file pci.cpp.
References IoOut32(), kConfigData, and value.
Referenced by WriteConfReg().
Variable Documentation
__attribute__
struct pci::MSICapability pci::__attribute__
devices
std::array<Device, 32> pci::devices inline
ScanAllBus() により発見された PCI デバイスの一覧
Definition at line 78 of file pci.hpp.
Referenced by anonymous_namespace{pci.cpp}::AddDevice(), usb::xhci::Initialize(), InitializePCI(), and anonymous_namespace{xhci.cpp}::SwitchEhci2Xhci().
kCapabilityMSI
const uint8_t pci::kCapabilityMSI = 0x05
Definition at line 104 of file pci.hpp.
Referenced by ConfigureMSI().
kCapabilityMSIX
const uint8_t pci::kCapabilityMSIX = 0x11
Definition at line 105 of file pci.hpp.
Referenced by ConfigureMSI().
kConfigAddress
const uint16_t pci::kConfigAddress = 0x0cf8
CONFIG_ADDRESS レジスタの IO ポートアドレス
Definition at line 10 of file pci.hpp.
Referenced by WriteAddress().
kConfigData
const uint16_t pci::kConfigData = 0x0cfc
CONFIG_DATA レジスタの IO ポートアドレス
Definition at line 12 of file pci.hpp.
Referenced by ReadData(), and WriteData().
num_device
int pci::num_device inline
devices の有効な要素の数
Definition at line 80 of file pci.hpp.
Referenced by anonymous_namespace{pci.cpp}::AddDevice(), usb::xhci::Initialize(), InitializePCI(), ScanAllBus(), and anonymous_namespace{xhci.cpp}::SwitchEhci2Xhci().