My Project: anonymous_namespace{memory_manager.cpp} Namespace Reference
anonymous_namespace{memory_manager.cpp} Namespace Reference
Functions
Error InitializeHeap (BitmapMemoryManager &memory_manager)
Variables
char memory_manager_buf [sizeof(BitmapMemoryManager)]
BitmapMemoryManager * memory_manager
Function Documentation
InitializeHeap()
Error anonymous_namespace{memory_manager.cpp}::InitializeHeap (BitmapMemoryManager & memory_manager)
Definition at line 78 of file memory_manager.cpp.
References BitmapMemoryManager::Allocate(), kBytesPerFrame(), Error::kSuccess, MAKE_ERROR, memory_manager, program_break, and program_break_end.
Referenced by InitializeMemoryManager().
Variable Documentation
memory_manager
BitmapMemoryManager* anonymous_namespace{memory_manager.cpp}::memory_manager
Definition at line 76 of file memory_manager.cpp.
Referenced by InitializeHeap(), and InitializeMemoryManager().
memory_manager_buf
char anonymous_namespace{memory_manager.cpp}::memory_manager_buf[sizeof(BitmapMemoryManager)]
Definition at line 75 of file memory_manager.cpp.
Referenced by InitializeMemoryManager().