My Project: anonymous_namespace{xhci.cpp} Namespace Reference
anonymous_namespace{xhci.cpp} Namespace Reference
Enumerations
enum ConfigPhase {
ConfigPhase::kNotConnected, ConfigPhase::kWaitingAddressed, ConfigPhase::kResettingPort, ConfigPhase::kEnablingSlot,
ConfigPhase::kAddressingDevice, ConfigPhase::kInitializingDevice, ConfigPhase::kConfiguringEndpoints, ConfigPhase::kConfigured
}
Functions
Error RegisterCommandRing (Ring *ring, MemMapRegister< CRCR_Bitmap > *crcr)
void InitializeSlotContext (SlotContext &ctx, Port &port)
unsigned int DetermineMaxPacketSizeForControlPipe (unsigned int slot_speed)
int MostSignificantBit (uint32_t value)
void InitializeEP0Context (EndpointContext &ctx, Ring *transfer_ring, unsigned int max_packet_size)
Error ResetPort (Controller &xhc, Port &port)
Error EnableSlot (Controller &xhc, Port &port)
Error AddressDevice (Controller &xhc, uint8_t port_id, uint8_t slot_id)
Error InitializeDevice (Controller &xhc, uint8_t port_id, uint8_t slot_id)
Error CompleteConfiguration (Controller &xhc, uint8_t port_id, uint8_t slot_id)
Error OnEvent (Controller &xhc, PortStatusChangeEventTRB &trb)
Error OnEvent (Controller &xhc, TransferEventTRB &trb)
Error OnEvent (Controller &xhc, CommandCompletionEventTRB &trb)
void RequestHCOwnership (uintptr_t mmio_base, HCCPARAMS1_Bitmap hccp)
void SwitchEhci2Xhci (const pci::Device &xhc_dev)
Variables
enum anonymous_namespace{xhci.cpp}::ConfigPhase __attribute__
std::array< volatile ConfigPhase, 256 > port_config_phase {}
uint8_t addressing_port {0}
Enumeration Type Documentation
ConfigPhase
enum anonymous_namespace{xhci.cpp}::ConfigPhase strong
Enumerator
kNotConnected
kWaitingAddressed
kResettingPort
kEnablingSlot
kAddressingDevice
kInitializingDevice
kConfiguringEndpoints
kConfigured
Definition at line 25 of file xhci.cpp.
Function Documentation
AddressDevice()
Error anonymous_namespace{xhci.cpp}::AddressDevice (Controller & xhc, uint8_t port_id, uint8_t slot_id)
Definition at line 134 of file xhci.cpp.
References usb::xhci::DeviceManager::AllocDevice(), usb::xhci::Device::AllocTransferRing(), usb::xhci::Controller::CommandRing(), DetermineMaxPacketSizeForControlPipe(), usb::xhci::Controller::DeviceManager(), usb::xhci::Controller::DoorbellRegisterAt(), usb::xhci::InputContext::EnableEndpoint(), usb::xhci::InputContext::EnableSlotContext(), usb::xhci::DeviceManager::FindBySlot(), InitializeEP0Context(), InitializeSlotContext(), usb::xhci::InputContext::input_control_context, usb::xhci::Device::InputContext(), kDebug, Error::kInvalidSlotID, Error::kSuccess, usb::xhci::DeviceManager::LoadDCBAA(), Log(), MAKE_ERROR, port_config_phase, port_id, usb::xhci::Controller::PortAt(), usb::xhci::Ring::Push(), usb::xhci::DoorbellRegister::Ring(), and slot_id.
Referenced by OnEvent().
CompleteConfiguration()
Error anonymous_namespace{xhci.cpp}::CompleteConfiguration (Controller & xhc, uint8_t port_id, uint8_t slot_id)
Definition at line 183 of file xhci.cpp.
References usb::xhci::Controller::DeviceManager(), usb::xhci::DeviceManager::FindBySlot(), kDebug, Error::kInvalidSlotID, Error::kSuccess, Log(), MAKE_ERROR, port_config_phase, port_id, and slot_id.
Referenced by OnEvent().
DetermineMaxPacketSizeForControlPipe()
unsigned int anonymous_namespace{xhci.cpp}::DetermineMaxPacketSizeForControlPipe (unsigned int slot_speed)
Definition at line 55 of file xhci.cpp.
Referenced by AddressDevice().
EnableSlot()
Error anonymous_namespace{xhci.cpp}::EnableSlot (Controller & xhc, Port & port)
Definition at line 115 of file xhci.cpp.
References usb::xhci::Port::ClearPortResetChange(), usb::xhci::Controller::CommandRing(), usb::xhci::Controller::DoorbellRegisterAt(), usb::xhci::Port::IsEnabled(), usb::xhci::Port::IsPortResetChanged(), kDebug, Error::kSuccess, Log(), MAKE_ERROR, usb::xhci::Port::Number(), port_config_phase, usb::xhci::Ring::Push(), and usb::xhci::DoorbellRegister::Ring().
Referenced by OnEvent().
InitializeDevice()
Error anonymous_namespace{xhci.cpp}::InitializeDevice (Controller & xhc, uint8_t port_id, uint8_t slot_id)
Definition at line 169 of file xhci.cpp.
References usb::xhci::Controller::DeviceManager(), usb::xhci::DeviceManager::FindBySlot(), kDebug, Error::kInvalidSlotID, Error::kSuccess, Log(), MAKE_ERROR, port_config_phase, port_id, and slot_id.
Referenced by OnEvent().
InitializeEP0Context()
void anonymous_namespace{xhci.cpp}::InitializeEP0Context (EndpointContext & ctx, Ring * transfer_ring, unsigned int max_packet_size)
Definition at line 77 of file xhci.cpp.
References usb::xhci::Ring::Buffer(), usb::xhci::EndpointContext::dequeue_cycle_state, usb::xhci::EndpointContext::ep_type, usb::xhci::EndpointContext::error_count, usb::xhci::EndpointContext::interval, usb::xhci::EndpointContext::max_burst_size, max_packet_size, usb::xhci::EndpointContext::max_packet_size, usb::xhci::EndpointContext::max_primary_streams, usb::xhci::EndpointContext::mult, and usb::xhci::EndpointContext::SetTransferRingBuffer().
Referenced by AddressDevice().
InitializeSlotContext()
void anonymous_namespace{xhci.cpp}::InitializeSlotContext (SlotContext & ctx, Port & port)
Definition at line 48 of file xhci.cpp.
References usb::xhci::SlotContext::context_entries, usb::xhci::Port::Number(), usb::xhci::SlotContext::root_hub_port_num, usb::xhci::SlotContext::route_string, usb::xhci::SlotContext::speed, and usb::xhci::Port::Speed().
Referenced by AddressDevice().
MostSignificantBit()
int anonymous_namespace{xhci.cpp}::MostSignificantBit (uint32_t value)
Definition at line 66 of file xhci.cpp.
References value.
Referenced by usb::xhci::ConfigureEndpoints().
OnEvent() [1/3]
Error anonymous_namespace{xhci.cpp}::OnEvent (Controller & xhc, CommandCompletionEventTRB & trb)
Definition at line 230 of file xhci.cpp.
References AddressDevice(), addressing_port, CompleteConfiguration(), usb::xhci::Controller::DeviceManager(), usb::xhci::DeviceManager::FindBySlot(), InitializeDevice(), kDebug, Error::kInvalidPhase, Error::kInvalidSlotID, usb::xhci::kTRBTypeToName, Log(), MAKE_ERROR, usb::xhci::CommandCompletionEventTRB::Pointer(), port_config_phase, port_id, usb::xhci::Controller::PortAt(), ResetPort(), slot_id, usb::xhci::CommandCompletionEventTRB::slot_id, usb::xhci::TRB::trb_type, usb::xhci::EnableSlotCommandTRB::Type, usb::xhci::AddressDeviceCommandTRB::Type, and usb::xhci::ConfigureEndpointCommandTRB::Type.
Referenced by usb::xhci::ProcessEvent().
OnEvent() [2/3]
Error anonymous_namespace{xhci.cpp}::OnEvent (Controller & xhc, PortStatusChangeEventTRB & trb)
Definition at line 197 of file xhci.cpp.
References EnableSlot(), kDebug, Error::kInvalidPhase, Log(), MAKE_ERROR, port_config_phase, port_id, usb::xhci::PortStatusChangeEventTRB::port_id, usb::xhci::Controller::PortAt(), and ResetPort().
OnEvent() [3/3]
Error anonymous_namespace{xhci.cpp}::OnEvent (Controller & xhc, TransferEventTRB & trb)
Definition at line 212 of file xhci.cpp.
References usb::xhci::ConfigureEndpoints(), usb::xhci::Controller::DeviceManager(), usb::xhci::DeviceManager::FindBySlot(), Error::kInvalidSlotID, Error::kSuccess, MAKE_ERROR, port_config_phase, port_id, slot_id, and usb::xhci::TransferEventTRB::slot_id.
RegisterCommandRing()
Error anonymous_namespace{xhci.cpp}::RegisterCommandRing (Ring * ring, MemMapRegister< CRCR_Bitmap > * crcr)
Definition at line 15 of file xhci.cpp.
References usb::xhci::Ring::Buffer(), Error::kSuccess, MAKE_ERROR, MemMapRegister< T >::Read(), value, and MemMapRegister< T >::Write().
Referenced by usb::xhci::Controller::Initialize().
RequestHCOwnership()
void anonymous_namespace{xhci.cpp}::RequestHCOwnership (uintptr_t mmio_base, HCCPARAMS1_Bitmap hccp)
Definition at line 286 of file xhci.cpp.
References kDebug, Log(), and MemMapRegister< T >::Read().
Referenced by usb::xhci::Controller::Initialize().
ResetPort()
Error anonymous_namespace{xhci.cpp}::ResetPort (Controller & xhc, Port & port)
Definition at line 91 of file xhci.cpp.
References addressing_port, usb::xhci::Port::IsConnected(), kDebug, Error::kInvalidPhase, Error::kSuccess, Log(), MAKE_ERROR, usb::xhci::Port::Number(), port_config_phase, and usb::xhci::Port::Reset().
Referenced by usb::xhci::ConfigurePort(), and OnEvent().
SwitchEhci2Xhci()
void anonymous_namespace{xhci.cpp}::SwitchEhci2Xhci (const pci::Device & xhc_dev)
Definition at line 315 of file xhci.cpp.
References pci::devices, kDebug, Log(), pci::num_device, pci::ReadConfReg(), pci::ReadVendorId(), and pci::WriteConfReg().
Referenced by usb::xhci::Initialize().
Variable Documentation
__attribute__
enum anonymous_namespace{xhci.cpp}::ConfigPhase anonymous_namespace{xhci.cpp}::__attribute__
addressing_port
uint8_t anonymous_namespace{xhci.cpp}::addressing_port {0}
kResettingPort から kAddressingDevice までの処理を実行中のポート番号． 0 ならその状態のポートがないことを示す．
Definition at line 46 of file xhci.cpp.
Referenced by OnEvent(), and ResetPort().
port_config_phase
std::array<volatile ConfigPhase, 256> anonymous_namespace{xhci.cpp}::port_config_phase {}
Definition at line 41 of file xhci.cpp.
Referenced by AddressDevice(), CompleteConfiguration(), usb::xhci::ConfigureEndpoints(), usb::xhci::ConfigurePort(), EnableSlot(), InitializeDevice(), OnEvent(), and ResetPort().