My Project: kernel/paging.cpp File Reference
paging.cpp File Reference
#include "paging.hpp"
#include <array>
#include "asmfunc.h"
Namespaces
anonymous_namespace{paging.cpp}
Functions
void SetupIdentityPageTable ()
仮想アドレス=物理アドレスとなるようにページテーブルを設定する． 最終的に CR3 レジスタが正しく設定されたページテーブルを指すようになる．
void InitializePaging ()
Variables
const uint64_t anonymous_namespace{paging.cpp}::kPageSize4K = 4096
const uint64_t anonymous_namespace{paging.cpp}::kPageSize2M = 512 * kPageSize4K
const uint64_t anonymous_namespace{paging.cpp}::kPageSize1G = 512 * kPageSize2M
std::array< uint64_t, 512 > anonymous_namespace{paging.cpp}::pml4_table
std::array< uint64_t, 512 > anonymous_namespace{paging.cpp}::pdp_table
std::array< std::array< uint64_t, 512 >, kPageDirectoryCount > anonymous_namespace{paging.cpp}::page_directory
Function Documentation
InitializePaging()
void InitializePaging ()
Definition at line 30 of file paging.cpp.
References SetupIdentityPageTable().
Referenced by KernelMainNewStack().
SetupIdentityPageTable()
void SetupIdentityPageTable ()
仮想アドレス=物理アドレスとなるようにページテーブルを設定する． 最終的に CR3 レジスタが正しく設定されたページテーブルを指すようになる．
Definition at line 18 of file paging.cpp.
References anonymous_namespace{paging.cpp}::kPageSize1G, anonymous_namespace{paging.cpp}::kPageSize2M, anonymous_namespace{paging.cpp}::page_directory, anonymous_namespace{paging.cpp}::pdp_table, anonymous_namespace{paging.cpp}::pml4_table, and SetCR3().
Referenced by InitializePaging().