My Project: kernel/paging.hpp File Reference
paging.hpp File Reference
#include <cstddef>
Functions
void SetupIdentityPageTable ()
仮想アドレス=物理アドレスとなるようにページテーブルを設定する． 最終的に CR3 レジスタが正しく設定されたページテーブルを指すようになる．
void InitializePaging ()
Variables
const size_t kPageDirectoryCount = 64
静的に確保するページディレクトリの個数
Function Documentation
InitializePaging()
void InitializePaging ()
Definition at line 30 of file paging.cpp.
References SetupIdentityPageTable().
Referenced by KernelMainNewStack().
SetupIdentityPageTable()
void SetupIdentityPageTable ()
仮想アドレス=物理アドレスとなるようにページテーブルを設定する． 最終的に CR3 レジスタが正しく設定されたページテーブルを指すようになる．
Definition at line 18 of file paging.cpp.
References anonymous_namespace{paging.cpp}::kPageSize1G, anonymous_namespace{paging.cpp}::kPageSize2M, anonymous_namespace{paging.cpp}::page_directory, anonymous_namespace{paging.cpp}::pdp_table, anonymous_namespace{paging.cpp}::pml4_table, and SetCR3().
Referenced by InitializePaging().
Variable Documentation
kPageDirectoryCount
const size_t kPageDirectoryCount = 64
静的に確保するページディレクトリの個数
この定数は SetupIdentityPageMap で使用される． 1 つのページディレクトリには 512 個の 2MiB ページを設定できるので， kPageDirectoryCount x 1GiB の仮想アドレスがマッピングされることになる．
Definition at line 11 of file paging.hpp.