My Project: kernel/pci.hpp File Reference
pci.hpp File Reference
#include <cstdint>
#include <array>
#include "error.hpp"
Classes
struct pci::ClassCode
struct pci::Device
PCI デバイスを操作するための基礎データを格納する
union pci::CapabilityHeader
struct pci::MSICapability
Namespaces
pci
Enumerations
enum pci::MSITriggerMode { pci::MSITriggerMode::kEdge = 0, pci::MSITriggerMode::kLevel = 1 }
enum pci::MSIDeliveryMode {
pci::MSIDeliveryMode::kFixed = 0b000, pci::MSIDeliveryMode::kLowestPriority = 0b001, pci::MSIDeliveryMode::kSMI = 0b010, pci::MSIDeliveryMode::kNMI = 0b100,
pci::MSIDeliveryMode::kINIT = 0b101, pci::MSIDeliveryMode::kExtINT = 0b111
}
Functions
void pci::WriteAddress (uint32_t address)
CONFIG_ADDRESS に指定された整数を書き込む
void pci::WriteData (uint32_t value)
CONFIG_DATA に指定された整数を書き込む
uint32_t pci::ReadData ()
CONFIG_DATA から 32 ビット整数を読み込む
uint16_t pci::ReadVendorId (uint8_t bus, uint8_t device, uint8_t function)
ベンダ ID レジスタを読み取る（全ヘッダタイプ共通）
uint16_t pci::ReadDeviceId (uint8_t bus, uint8_t device, uint8_t function)
デバイス ID レジスタを読み取る（全ヘッダタイプ共通）
uint8_t pci::ReadHeaderType (uint8_t bus, uint8_t device, uint8_t function)
ヘッダタイプレジスタを読み取る（全ヘッダタイプ共通）
ClassCode pci::ReadClassCode (uint8_t bus, uint8_t device, uint8_t function)
クラスコードレジスタを読み取る（全ヘッダタイプ共通）
uint16_t pci::ReadVendorId (const Device &dev)
uint32_t pci::ReadConfReg (const Device &dev, uint8_t reg_addr)
void pci::WriteConfReg (const Device &dev, uint8_t reg_addr, uint32_t value)
uint32_t pci::ReadBusNumbers (uint8_t bus, uint8_t device, uint8_t function)
バス番号レジスタを読み取る（ヘッダタイプ 1 用）
bool pci::IsSingleFunctionDevice (uint8_t header_type)
単一ファンクションの場合に真を返す
Error pci::ScanAllBus ()
PCI デバイスをすべて探索し devices に格納する
constexpr uint8_t pci::CalcBarAddress (unsigned int bar_index)
WithError< uint64_t > pci::ReadBar (Device &device, unsigned int bar_index)
union pci::CapabilityHeader pci::__attribute__ ((packed))
struct {
uint32_t cap_id: 8
uint32_t next_ptr: 8
uint32_t cap: 16
} __attribute__ ((packed)) bits
CapabilityHeader pci::ReadCapabilityHeader (const Device &dev, uint8_t addr)
Error pci::ConfigureMSI (const Device &dev, uint32_t msg_addr, uint32_t msg_data, unsigned int num_vector_exponent)
Error pci::ConfigureMSIFixedDestination (const Device &dev, uint8_t apic_id, MSITriggerMode trigger_mode, MSIDeliveryMode delivery_mode, uint8_t vector, unsigned int num_vector_exponent)
void InitializePCI ()
Variables
const uint16_t pci::kConfigAddress = 0x0cf8
CONFIG_ADDRESS レジスタの IO ポートアドレス
const uint16_t pci::kConfigData = 0x0cfc
CONFIG_DATA レジスタの IO ポートアドレス
std::array< Device, 32 > pci::devices
ScanAllBus() により発見された PCI デバイスの一覧
int pci::num_device
devices の有効な要素の数
uint32_t cap_id
uint32_t next_ptr
uint32_t cap
uint32_t data
const uint8_t pci::kCapabilityMSI = 0x05
const uint8_t pci::kCapabilityMSIX = 0x11
uint32_t msi_enable
uint32_t multi_msg_capable
uint32_t multi_msg_enable
uint32_t addr_64_capable
uint32_t per_vector_mask_capable
uint32_t __pad0__
uint32_t msg_addr
uint32_t msg_upper_addr
uint32_t msg_data
uint32_t mask_bits
uint32_t pending_bits
enum pci::MSITriggerMode pci::__attribute__
Function Documentation
__attribute__()
struct @7 __attribute__::__attribute__ ((packed))
InitializePCI()
void InitializePCI ()
Definition at line 332 of file pci.cpp.
References pci::devices, kDebug, kError, Log(), pci::num_device, pci::ReadClassCode(), pci::ReadVendorId(), pci::ScanAllBus(), and vendor_id.
Referenced by KernelMainNewStack().
Variable Documentation
__pad0__
uint32_t __pad0__
Definition at line 119 of file pci.hpp.
addr_64_capable
uint32_t addr_64_capable
Definition at line 117 of file pci.hpp.
cap
uint32_t cap
Definition at line 99 of file pci.hpp.
cap_id
uint32_t cap_id
Definition at line 97 of file pci.hpp.
data
uint32_t data
Definition at line 94 of file pci.hpp.
mask_bits
uint32_t mask_bits
Definition at line 125 of file pci.hpp.
msg_addr
uint32_t msg_addr
Definition at line 122 of file pci.hpp.
Referenced by pci::ConfigureMSI(), pci::ConfigureMSIFixedDestination(), and anonymous_namespace{pci.cpp}::ConfigureMSIRegister().
msg_data
uint32_t msg_data
Definition at line 124 of file pci.hpp.
Referenced by pci::ConfigureMSI(), pci::ConfigureMSIFixedDestination(), and anonymous_namespace{pci.cpp}::ConfigureMSIRegister().
msg_upper_addr
uint32_t msg_upper_addr
Definition at line 123 of file pci.hpp.
msi_enable
uint32_t msi_enable
Definition at line 114 of file pci.hpp.
multi_msg_capable
uint32_t multi_msg_capable
Definition at line 115 of file pci.hpp.
multi_msg_enable
uint32_t multi_msg_enable
Definition at line 116 of file pci.hpp.
next_ptr
uint32_t next_ptr
Definition at line 98 of file pci.hpp.
pending_bits
uint32_t pending_bits
Definition at line 126 of file pci.hpp.
per_vector_mask_capable
uint32_t per_vector_mask_capable
Definition at line 118 of file pci.hpp.