My Project: kernel/pci.cpp File Reference
pci.cpp File Reference
#include "pci.hpp"
#include "asmfunc.h"
#include "logger.hpp"
Namespaces
anonymous_namespace{pci.cpp}
pci
Functions
uint32_t anonymous_namespace{pci.cpp}::MakeAddress (uint8_t bus, uint8_t device, uint8_t function, uint8_t reg_addr)
Error anonymous_namespace{pci.cpp}::AddDevice (const Device &device)
devices[num_device] に情報を書き込み num_device をインクリメントする．
Error anonymous_namespace{pci.cpp}::ScanBus (uint8_t bus)
指定のバス番号の各デバイスをスキャンする． 有効なデバイスを見つけたら ScanDevice を実行する．
Error anonymous_namespace{pci.cpp}::ScanFunction (uint8_t bus, uint8_t device, uint8_t function)
指定のファンクションを devices に追加する． もし PCI-PCI ブリッジなら，セカンダリバスに対し ScanBus を実行する
Error anonymous_namespace{pci.cpp}::ScanDevice (uint8_t bus, uint8_t device)
指定のデバイス番号の各ファンクションをスキャンする． 有効なファンクションを見つけたら ScanFunction を実行する．
MSICapability anonymous_namespace{pci.cpp}::ReadMSICapability (const Device &dev, uint8_t cap_addr)
指定された MSI ケーパビリティ構造を読み取る
void anonymous_namespace{pci.cpp}::WriteMSICapability (const Device &dev, uint8_t cap_addr, const MSICapability &msi_cap)
指定された MSI ケーパビリティ構造に書き込む
Error anonymous_namespace{pci.cpp}::ConfigureMSIRegister (const Device &dev, uint8_t cap_addr, uint32_t msg_addr, uint32_t msg_data, unsigned int num_vector_exponent)
指定された MSI レジスタを設定する
Error anonymous_namespace{pci.cpp}::ConfigureMSIXRegister (const Device &dev, uint8_t cap_addr, uint32_t msg_addr, uint32_t msg_data, unsigned int num_vector_exponent)
指定された MSI レジスタを設定する
void pci::WriteAddress (uint32_t address)
CONFIG_ADDRESS に指定された整数を書き込む
void pci::WriteData (uint32_t value)
CONFIG_DATA に指定された整数を書き込む
uint32_t pci::ReadData ()
CONFIG_DATA から 32 ビット整数を読み込む
uint16_t pci::ReadVendorId (uint8_t bus, uint8_t device, uint8_t function)
ベンダ ID レジスタを読み取る（全ヘッダタイプ共通）
uint16_t pci::ReadDeviceId (uint8_t bus, uint8_t device, uint8_t function)
デバイス ID レジスタを読み取る（全ヘッダタイプ共通）
ClassCode pci::ReadClassCode (uint8_t bus, uint8_t device, uint8_t function)
クラスコードレジスタを読み取る（全ヘッダタイプ共通）
uint32_t pci::ReadConfReg (const Device &dev, uint8_t reg_addr)
void pci::WriteConfReg (const Device &dev, uint8_t reg_addr, uint32_t value)
uint8_t pci::ReadHeaderType (uint8_t bus, uint8_t device, uint8_t function)
ヘッダタイプレジスタを読み取る（全ヘッダタイプ共通）
uint32_t pci::ReadBusNumbers (uint8_t bus, uint8_t device, uint8_t function)
バス番号レジスタを読み取る（ヘッダタイプ 1 用）
bool pci::IsSingleFunctionDevice (uint8_t header_type)
単一ファンクションの場合に真を返す
Error pci::ScanAllBus ()
PCI デバイスをすべて探索し devices に格納する
WithError< uint64_t > pci::ReadBar (Device &device, unsigned int bar_index)
CapabilityHeader pci::ReadCapabilityHeader (const Device &dev, uint8_t addr)
Error pci::ConfigureMSI (const Device &dev, uint32_t msg_addr, uint32_t msg_data, unsigned int num_vector_exponent)
Error pci::ConfigureMSIFixedDestination (const Device &dev, uint8_t apic_id, MSITriggerMode trigger_mode, MSIDeliveryMode delivery_mode, uint8_t vector, unsigned int num_vector_exponent)
void InitializePCI ()
Function Documentation
InitializePCI()
void InitializePCI ()
Definition at line 332 of file pci.cpp.
References pci::devices, kDebug, kError, Log(), pci::num_device, pci::ReadClassCode(), pci::ReadVendorId(), pci::ScanAllBus(), and vendor_id.
Referenced by KernelMainNewStack().