My Project: kernel/segment.hpp File Reference
segment.hpp File Reference
#include <array>
#include <cstdint>
#include "x86_descriptor.hpp"
Classes
union SegmentDescriptor
Functions
union SegmentDescriptor __attribute__ ((packed))
void SetCodeSegment (SegmentDescriptor &desc, DescriptorType type, unsigned int descriptor_privilege_level, uint32_t base, uint32_t limit)
void SetDataSegment (SegmentDescriptor &desc, DescriptorType type, unsigned int descriptor_privilege_level, uint32_t base, uint32_t limit)
void SetupSegment ()
void InitializeSegmentation ()
Variables
uint64_t limit_low
uint64_t base_low
uint64_t base_middle
DescriptorType type
uint64_t system_segment
uint64_t descriptor_privilege_level
uint64_t present
uint64_t limit_high
uint64_t available
uint64_t long_mode
uint64_t default_operation_size
uint64_t granularity
uint64_t base_high
uint64_t data
const uint16_t kKernelCS = 1 << 3
const uint16_t kKernelSS = 2 << 3
const uint16_t kKernelDS = 0
Function Documentation
__attribute__()
union SegmentDescriptor __attribute__ ((packed))
InitializeSegmentation()
void InitializeSegmentation ()
Definition at line 52 of file segment.cpp.
References kKernelCS, kKernelDS, kKernelSS, SetCSSS(), SetDSAll(), and SetupSegments().
Referenced by KernelMainNewStack().
SetCodeSegment()
void SetCodeSegment (SegmentDescriptor & desc, DescriptorType type, unsigned int descriptor_privilege_level, uint32_t base, uint32_t limit)
Definition at line 9 of file segment.cpp.
References SegmentDescriptor::available, SegmentDescriptor::base_high, SegmentDescriptor::base_low, SegmentDescriptor::base_middle, SegmentDescriptor::data, SegmentDescriptor::default_operation_size, SegmentDescriptor::descriptor_privilege_level, descriptor_privilege_level, SegmentDescriptor::granularity, SegmentDescriptor::limit_high, SegmentDescriptor::limit_low, SegmentDescriptor::long_mode, SegmentDescriptor::present, SegmentDescriptor::system_segment, type, and SegmentDescriptor::type.
Referenced by SetDataSegment(), and SetupSegments().
SetDataSegment()
void SetDataSegment (SegmentDescriptor & desc, DescriptorType type, unsigned int descriptor_privilege_level, uint32_t base, uint32_t limit)
Definition at line 35 of file segment.cpp.
References SegmentDescriptor::default_operation_size, descriptor_privilege_level, SegmentDescriptor::long_mode, SetCodeSegment(), and type.
Referenced by SetupSegments().
SetupSegment()
void SetupSegment ()
Variable Documentation
available
uint64_t available
Definition at line 18 of file segment.hpp.
base_high
uint64_t base_high
Definition at line 22 of file segment.hpp.
base_low
uint64_t base_low
Definition at line 11 of file segment.hpp.
base_middle
uint64_t base_middle
Definition at line 12 of file segment.hpp.
data
uint64_t data
Definition at line 2 of file segment.hpp.
default_operation_size
uint64_t default_operation_size
Definition at line 20 of file segment.hpp.
descriptor_privilege_level
uint64_t descriptor_privilege_level
Definition at line 15 of file segment.hpp.
granularity
uint64_t granularity
Definition at line 21 of file segment.hpp.
kKernelCS
const uint16_t kKernelCS = 1 << 3
Definition at line 38 of file segment.hpp.
Referenced by Task::InitContext(), InitializeInterrupt(), and InitializeSegmentation().
kKernelDS
const uint16_t kKernelDS = 0
Definition at line 40 of file segment.hpp.
Referenced by InitializeSegmentation().
kKernelSS
const uint16_t kKernelSS = 2 << 3
Definition at line 39 of file segment.hpp.
Referenced by Task::InitContext(), and InitializeSegmentation().
limit_high
uint64_t limit_high
Definition at line 17 of file segment.hpp.
limit_low
uint64_t limit_low
Definition at line 10 of file segment.hpp.
long_mode
uint64_t long_mode
Definition at line 19 of file segment.hpp.
present
uint64_t present
Definition at line 16 of file segment.hpp.
system_segment
uint64_t system_segment
Definition at line 14 of file segment.hpp.
type
DescriptorType type
Definition at line 13 of file segment.hpp.