My Project: kernel/segment.cpp File Reference
segment.cpp File Reference
#include "segment.hpp"
#include "asmfunc.h"
Namespaces
anonymous_namespace{segment.cpp}
Functions
void SetCodeSegment (SegmentDescriptor &desc, DescriptorType type, unsigned int descriptor_privilege_level, uint32_t base, uint32_t limit)
void SetDataSegment (SegmentDescriptor &desc, DescriptorType type, unsigned int descriptor_privilege_level, uint32_t base, uint32_t limit)
void SetupSegments ()
void InitializeSegmentation ()
Variables
std::array< SegmentDescriptor, 3 > anonymous_namespace{segment.cpp}::gdt
Function Documentation
InitializeSegmentation()
void InitializeSegmentation ()
Definition at line 52 of file segment.cpp.
References kKernelCS, kKernelDS, kKernelSS, SetCSSS(), SetDSAll(), and SetupSegments().
Referenced by KernelMainNewStack().
SetCodeSegment()
void SetCodeSegment (SegmentDescriptor & desc, DescriptorType type, unsigned int descriptor_privilege_level, uint32_t base, uint32_t limit)
Definition at line 9 of file segment.cpp.
References SegmentDescriptor::available, SegmentDescriptor::base_high, SegmentDescriptor::base_low, SegmentDescriptor::base_middle, SegmentDescriptor::data, SegmentDescriptor::default_operation_size, SegmentDescriptor::descriptor_privilege_level, descriptor_privilege_level, SegmentDescriptor::granularity, SegmentDescriptor::limit_high, SegmentDescriptor::limit_low, SegmentDescriptor::long_mode, SegmentDescriptor::present, SegmentDescriptor::system_segment, type, and SegmentDescriptor::type.
Referenced by SetDataSegment(), and SetupSegments().
SetDataSegment()
void SetDataSegment (SegmentDescriptor & desc, DescriptorType type, unsigned int descriptor_privilege_level, uint32_t base, uint32_t limit)
Definition at line 35 of file segment.cpp.
References SegmentDescriptor::default_operation_size, descriptor_privilege_level, SegmentDescriptor::long_mode, SetCodeSegment(), and type.
Referenced by SetupSegments().
SetupSegments()
void SetupSegments ()
Definition at line 45 of file segment.cpp.
References anonymous_namespace{segment.cpp}::gdt, kExecuteRead, kReadWrite, LoadGDT(), SetCodeSegment(), and SetDataSegment().
Referenced by InitializeSegmentation().