My Project: acpi::RSDP Struct Reference
acpi::RSDP Struct Reference
#include <acpi.hpp>
Public Member Functions
bool IsValid () const
Public Attributes
char signature [8]
uint8_t checksum
char oem_id [6]
uint8_t revision
uint32_t rsdt_address
uint32_t length
uint64_t xsdt_address
uint8_t extended_checksum
char reserved [3]
Detailed Description
Definition at line 14 of file acpi.hpp.
Member Function Documentation
IsValid()
bool acpi::RSDP::IsValid () const
Definition at line 25 of file acpi.cpp.
References kDebug, Log(), revision, signature, and anonymous_namespace{acpi.cpp}::SumBytes().
Referenced by acpi::Initialize().
Member Data Documentation
checksum
uint8_t acpi::RSDP::checksum
Definition at line 16 of file acpi.hpp.
extended_checksum
uint8_t acpi::RSDP::extended_checksum
Definition at line 22 of file acpi.hpp.
length
uint32_t acpi::RSDP::length
Definition at line 20 of file acpi.hpp.
oem_id
char acpi::RSDP::oem_id[6]
Definition at line 17 of file acpi.hpp.
reserved
char acpi::RSDP::reserved[3]
Definition at line 23 of file acpi.hpp.
revision
uint8_t acpi::RSDP::revision
Definition at line 18 of file acpi.hpp.
Referenced by IsValid().
rsdt_address
uint32_t acpi::RSDP::rsdt_address
Definition at line 19 of file acpi.hpp.
signature
char acpi::RSDP::signature[8]
Definition at line 15 of file acpi.hpp.
Referenced by IsValid().
xsdt_address
uint64_t acpi::RSDP::xsdt_address
Definition at line 21 of file acpi.hpp.
Referenced by acpi::Initialize().
The documentation for this struct was generated from the following files:
kernel/acpi.hpp
kernel/acpi.cpp