My Project: acpi::DescriptionHeader Struct Reference
acpi::DescriptionHeader Struct Reference
#include <acpi.hpp>
Public Member Functions
bool IsValid (const char *expected_signature) const
Public Attributes
char signature [4]
uint32_t length
uint8_t revision
uint8_t checksum
char oem_id [6]
char oem_table_id [8]
uint32_t oem_revision
uint32_t creator_id
uint32_t creator_revision
Detailed Description
Definition at line 28 of file acpi.hpp.
Member Function Documentation
IsValid()
bool acpi::DescriptionHeader::IsValid (const char * expected_signature) const
Definition at line 45 of file acpi.cpp.
References kDebug, length, Log(), signature, and anonymous_namespace{acpi.cpp}::SumBytes().
Referenced by acpi::Initialize().
Member Data Documentation
checksum
uint8_t acpi::DescriptionHeader::checksum
Definition at line 32 of file acpi.hpp.
creator_id
uint32_t acpi::DescriptionHeader::creator_id
Definition at line 36 of file acpi.hpp.
creator_revision
uint32_t acpi::DescriptionHeader::creator_revision
Definition at line 37 of file acpi.hpp.
length
uint32_t acpi::DescriptionHeader::length
Definition at line 30 of file acpi.hpp.
Referenced by acpi::XSDT::Count(), and IsValid().
oem_id
char acpi::DescriptionHeader::oem_id[6]
Definition at line 33 of file acpi.hpp.
oem_revision
uint32_t acpi::DescriptionHeader::oem_revision
Definition at line 35 of file acpi.hpp.
oem_table_id
char acpi::DescriptionHeader::oem_table_id[8]
Definition at line 34 of file acpi.hpp.
revision
uint8_t acpi::DescriptionHeader::revision
Definition at line 31 of file acpi.hpp.
signature
char acpi::DescriptionHeader::signature[4]
Definition at line 29 of file acpi.hpp.
Referenced by IsValid().
The documentation for this struct was generated from the following files:
kernel/acpi.hpp
kernel/acpi.cpp