My Project: usb::xhci::InputContext Struct Reference
usb::xhci::InputContext Struct Reference
#include <context.hpp>
Public Member Functions
SlotContext * EnableSlotContext ()
Enable the slot context.
EndpointContext * EnableEndpoint (DeviceContextIndex dci)
Enable an endpoint.
Public Attributes
InputControlContext input_control_context
SlotContext slot_context
EndpointContext ep_contexts [31]
Detailed Description
Definition at line 100 of file context.hpp.
Member Function Documentation
EnableEndpoint()
EndpointContext* usb::xhci::InputContext::EnableEndpoint (DeviceContextIndex dci) inline
Enable an endpoint.
Parameters
dci Device Context Index (1 .. 31)
Returns
Pointer to the endpoint context enabled.
Definition at line 119 of file context.hpp.
References usb::xhci::InputControlContext::add_context_flags, ep_contexts, input_control_context, and usb::xhci::DeviceContextIndex::value.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), and usb::xhci::ConfigureEndpoints().
EnableSlotContext()
SlotContext* usb::xhci::InputContext::EnableSlotContext () inline
Enable the slot context.
Returns
Pointer to the slot context enabled.
Definition at line 109 of file context.hpp.
References usb::xhci::InputControlContext::add_context_flags, input_control_context, and slot_context.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), and usb::xhci::ConfigureEndpoints().
Member Data Documentation
ep_contexts
EndpointContext usb::xhci::InputContext::ep_contexts[31]
Definition at line 103 of file context.hpp.
Referenced by EnableEndpoint().
input_control_context
InputControlContext usb::xhci::InputContext::input_control_context
Definition at line 101 of file context.hpp.
Referenced by anonymous_namespace{xhci.cpp}::AddressDevice(), usb::xhci::ConfigureEndpoints(), EnableEndpoint(), and EnableSlotContext().
slot_context
SlotContext usb::xhci::InputContext::slot_context
Definition at line 102 of file context.hpp.
Referenced by usb::xhci::ConfigureEndpoints(), and EnableSlotContext().
The documentation for this struct was generated from the following file:
kernel/usb/xhci/context.hpp