My Project: kernel/timer.hpp File Reference
timer.hpp File Reference
#include <cstdint>
#include <queue>
#include <vector>
#include <limits>
#include "message.hpp"
Classes
class Timer
class TimerManager
Functions
void InitializeLAPICTimer ()
void StartLAPICTimer ()
uint32_t LAPICTimerElapsed ()
void StopLAPICTimer ()
bool operator< (const Timer &lhs, const Timer &rhs)
タイマー優先度を比較する。タイムアウトが遠いほど優先度低。
void LAPICTimerOnInterrupt ()
Variables
TimerManager * timer_manager
unsigned long lapic_timer_freq
const int kTimerFreq = 100
const int kTaskTimerPeriod = static_cast<int>(kTimerFreq * 0.02)
const int kTaskTimerValue = std::numeric_limits<int>::min()
Function Documentation
InitializeLAPICTimer()
void InitializeLAPICTimer ()
Definition at line 15 of file timer.cpp.
References anonymous_namespace{timer.cpp}::divide_config, anonymous_namespace{timer.cpp}::initial_count, InterruptVector::kLAPICTimer, kTimerFreq, lapic_timer_freq, LAPICTimerElapsed(), anonymous_namespace{timer.cpp}::lvt_timer, StartLAPICTimer(), StopLAPICTimer(), timer_manager, and acpi::WaitMilliseconds().
Referenced by KernelMainNewStack().
LAPICTimerElapsed()
uint32_t LAPICTimerElapsed ()
Definition at line 37 of file timer.cpp.
References anonymous_namespace{timer.cpp}::current_count, and anonymous_namespace{timer.cpp}::kCountMax.
Referenced by InitializeLAPICTimer().
LAPICTimerOnInterrupt()
void LAPICTimerOnInterrupt ()
Definition at line 88 of file timer.cpp.
References NotifyEndOfInterrupt(), TaskManager::SwitchTask(), task_manager, TimerManager::Tick(), and timer_manager.
operator<()
bool operator< (const Timer & lhs, const Timer & rhs) inline
タイマー優先度を比較する。タイムアウトが遠いほど優先度低。
Definition at line 26 of file timer.hpp.
References Timer::Timeout().
StartLAPICTimer()
void StartLAPICTimer ()
Definition at line 33 of file timer.cpp.
References anonymous_namespace{timer.cpp}::initial_count, and anonymous_namespace{timer.cpp}::kCountMax.
Referenced by InitializeLAPICTimer().
StopLAPICTimer()
void StopLAPICTimer ()
Definition at line 41 of file timer.cpp.
References anonymous_namespace{timer.cpp}::initial_count.
Referenced by InitializeLAPICTimer().
Variable Documentation
kTaskTimerPeriod
const int kTaskTimerPeriod = static_cast<int>(kTimerFreq * 0.02)
Definition at line 46 of file timer.hpp.
Referenced by InitializeTask(), and TimerManager::Tick().
kTaskTimerValue
const int kTaskTimerValue = std::numeric_limits<int>::min()
Definition at line 47 of file timer.hpp.
Referenced by InitializeTask(), and TimerManager::Tick().
kTimerFreq
const int kTimerFreq = 100
Definition at line 44 of file timer.hpp.
Referenced by InitializeLAPICTimer(), and KernelMainNewStack().
lapic_timer_freq
unsigned long lapic_timer_freq
Definition at line 86 of file timer.cpp.
Referenced by InitializeLAPICTimer().
timer_manager
TimerManager* timer_manager
Definition at line 85 of file timer.cpp.
Referenced by InitializeLAPICTimer(), InitializeTask(), KernelMainNewStack(), and LAPICTimerOnInterrupt().