My Project: kernel/timer.cpp File Reference
timer.cpp File Reference
#include "timer.hpp"
#include "acpi.hpp"
#include "interrupt.hpp"
#include "task.hpp"
Namespaces
anonymous_namespace{timer.cpp}
Functions
void InitializeLAPICTimer ()
void StartLAPICTimer ()
uint32_t LAPICTimerElapsed ()
void StopLAPICTimer ()
void LAPICTimerOnInterrupt ()
Variables
const uint32_t anonymous_namespace{timer.cpp}::kCountMax = 0xffffffffu
volatile uint32_t & anonymous_namespace{timer.cpp}::lvt_timer = *reinterpret_cast<uint32_t*>(0xfee00320)
volatile uint32_t & anonymous_namespace{timer.cpp}::initial_count = *reinterpret_cast<uint32_t*>(0xfee00380)
volatile uint32_t & anonymous_namespace{timer.cpp}::current_count = *reinterpret_cast<uint32_t*>(0xfee00390)
volatile uint32_t & anonymous_namespace{timer.cpp}::divide_config = *reinterpret_cast<uint32_t*>(0xfee003e0)
TimerManager * timer_manager
unsigned long lapic_timer_freq
Function Documentation
InitializeLAPICTimer()
void InitializeLAPICTimer ()
Definition at line 15 of file timer.cpp.
References anonymous_namespace{timer.cpp}::divide_config, anonymous_namespace{timer.cpp}::initial_count, InterruptVector::kLAPICTimer, kTimerFreq, lapic_timer_freq, LAPICTimerElapsed(), anonymous_namespace{timer.cpp}::lvt_timer, StartLAPICTimer(), StopLAPICTimer(), timer_manager, and acpi::WaitMilliseconds().
Referenced by KernelMainNewStack().
LAPICTimerElapsed()
uint32_t LAPICTimerElapsed ()
Definition at line 37 of file timer.cpp.
References anonymous_namespace{timer.cpp}::current_count, and anonymous_namespace{timer.cpp}::kCountMax.
Referenced by InitializeLAPICTimer().
LAPICTimerOnInterrupt()
void LAPICTimerOnInterrupt ()
Definition at line 88 of file timer.cpp.
References NotifyEndOfInterrupt(), TaskManager::SwitchTask(), task_manager, TimerManager::Tick(), and timer_manager.
StartLAPICTimer()
void StartLAPICTimer ()
Definition at line 33 of file timer.cpp.
References anonymous_namespace{timer.cpp}::initial_count, and anonymous_namespace{timer.cpp}::kCountMax.
Referenced by InitializeLAPICTimer().
StopLAPICTimer()
void StopLAPICTimer ()
Definition at line 41 of file timer.cpp.
References anonymous_namespace{timer.cpp}::initial_count.
Referenced by InitializeLAPICTimer().
Variable Documentation
lapic_timer_freq
unsigned long lapic_timer_freq
Definition at line 86 of file timer.cpp.
Referenced by InitializeLAPICTimer().
timer_manager
TimerManager* timer_manager
Definition at line 85 of file timer.cpp.
Referenced by InitializeLAPICTimer(), InitializeTask(), KernelMainNewStack(), and LAPICTimerOnInterrupt().