My Project: usb::xhci::TransferEventTRB Union Reference
usb::xhci::TransferEventTRB Union Reference
#include <trb.hpp>
Public Member Functions
struct {
uint64_t trb_pointer: 64
uint32_t trb_transfer_length: 24
uint32_t completion_code: 8
uint32_t cycle_bit: 1
uint32_t __pad0__: 1
uint32_t event_data: 1
uint32_t __pad1__: 7
uint32_t trb_type: 6
uint32_t endpoint_id: 5
uint32_t __pad2__: 3
uint32_t slot_id: 8
} __attribute__ ((packed)) bits
TransferEventTRB ()
TRB * Pointer () const
void SetPointer (const TRB *p)
EndpointID EndpointID () const
Public Attributes
std::array< uint32_t, 4 > data {}
Static Public Attributes
static const unsigned int Type = 32
Detailed Description
Definition at line 358 of file trb.hpp.
Constructor & Destructor Documentation
TransferEventTRB()
usb::xhci::TransferEventTRB::TransferEventTRB () inline
Definition at line 377 of file trb.hpp.
References bits, and Type.
Member Function Documentation
__attribute__()
struct usb::xhci::TransferEventTRB::@93 usb::xhci::TransferEventTRB::__attribute__ ((packed))
EndpointID()
EndpointID usb::xhci::TransferEventTRB::EndpointID () const inline
Definition at line 389 of file trb.hpp.
References bits.
Referenced by anonymous_namespace{device.cpp}::Log(), and usb::xhci::Device::OnTransferEventReceived().
Pointer()
TRB* usb::xhci::TransferEventTRB::Pointer () const inline
Definition at line 381 of file trb.hpp.
References bits.
Referenced by anonymous_namespace{device.cpp}::Log(), and usb::xhci::Device::OnTransferEventReceived().
SetPointer()
void usb::xhci::TransferEventTRB::SetPointer (const TRB * p) inline
Definition at line 385 of file trb.hpp.
References bits.
Member Data Documentation
__pad0__
uint32_t usb::xhci::TransferEventTRB::__pad0__
Definition at line 368 of file trb.hpp.
__pad1__
uint32_t usb::xhci::TransferEventTRB::__pad1__
Definition at line 370 of file trb.hpp.
__pad2__
uint32_t usb::xhci::TransferEventTRB::__pad2__
Definition at line 373 of file trb.hpp.
completion_code
uint32_t usb::xhci::TransferEventTRB::completion_code
Definition at line 365 of file trb.hpp.
Referenced by anonymous_namespace{device.cpp}::Log(), and usb::xhci::Device::OnTransferEventReceived().
cycle_bit
uint32_t usb::xhci::TransferEventTRB::cycle_bit
Definition at line 367 of file trb.hpp.
data
std::array<uint32_t, 4> usb::xhci::TransferEventTRB::data {}
Definition at line 360 of file trb.hpp.
endpoint_id
uint32_t usb::xhci::TransferEventTRB::endpoint_id
Definition at line 372 of file trb.hpp.
event_data
uint32_t usb::xhci::TransferEventTRB::event_data
Definition at line 369 of file trb.hpp.
Referenced by anonymous_namespace{device.cpp}::Log().
slot_id
uint32_t usb::xhci::TransferEventTRB::slot_id
Definition at line 374 of file trb.hpp.
Referenced by anonymous_namespace{device.cpp}::Log(), and anonymous_namespace{xhci.cpp}::OnEvent().
trb_pointer
uint64_t usb::xhci::TransferEventTRB::trb_pointer
Definition at line 362 of file trb.hpp.
trb_transfer_length
uint32_t usb::xhci::TransferEventTRB::trb_transfer_length
Definition at line 364 of file trb.hpp.
Referenced by anonymous_namespace{device.cpp}::Log(), and usb::xhci::Device::OnTransferEventReceived().
trb_type
uint32_t usb::xhci::TransferEventTRB::trb_type
Definition at line 371 of file trb.hpp.
Type
const unsigned int usb::xhci::TransferEventTRB::Type = 32 static
Definition at line 359 of file trb.hpp.
Referenced by TransferEventTRB().
The documentation for this union was generated from the following file:
kernel/usb/xhci/trb.hpp