My Project: kernel/window.cpp File Reference
window.cpp File Reference
#include "window.hpp"
#include "logger.hpp"
#include "font.hpp"
#include "graphics.hpp"
Namespaces
anonymous_namespace{window.cpp}
Functions
void DrawWindow (PixelWriter &writer, const char *title)
void DrawTextbox (PixelWriter &writer, Vector2D< int > pos, Vector2D< int > size)
Variables
const int anonymous_namespace{window.cpp}::kCloseButtonWidth = 16
const int anonymous_namespace{window.cpp}::kCloseButtonHeight = 14
const char anonymous_namespace{window.cpp}::close_button [kCloseButtonHeight][kCloseButtonWidth+1]
Function Documentation
DrawTextbox()
void DrawTextbox (PixelWriter & writer, Vector2D< int > pos, Vector2D< int > size)
Definition at line 140 of file window.cpp.
References FillRectangle(), ToColor(), Vector2D< T >::x, and Vector2D< T >::y.
Referenced by InitializeTextWindow().
DrawWindow()
void DrawWindow (PixelWriter & writer, const char * title)
Definition at line 105 of file window.cpp.
References anonymous_namespace{window.cpp}::close_button, FillRectangle(), PixelWriter::Height(), anonymous_namespace{window.cpp}::kCloseButtonHeight, anonymous_namespace{window.cpp}::kCloseButtonWidth, ToColor(), PixelWriter::Width(), PixelWriter::Write(), and WriteString().
Referenced by InitializeMainWindow(), InitializeTaskBWindow(), and InitializeTextWindow().