My Project: kernel/window.hpp File Reference
window.hpp File Reference
#include <vector>
#include <optional>
#include "graphics.hpp"
#include "frame_buffer.hpp"
Classes
class Window
Windowクラスはグラフィックの表示領域を表す。
class Window::WindowWriter
WindowWriterはWindowと関連付けられたPixelWriterを提供する。
Functions
void DrawWindow (PixelWriter &writer, const char *title)
void DrawTextbox (PixelWriter &writer, Vector2D< int > pos, Vector2D< int > size)
Detailed Description
表示領域を表すWindowクラスを提供する。
Definition in file window.hpp.
Function Documentation
DrawTextbox()
void DrawTextbox (PixelWriter & writer, Vector2D< int > pos, Vector2D< int > size)
Definition at line 140 of file window.cpp.
References FillRectangle(), ToColor(), Vector2D< T >::x, and Vector2D< T >::y.
Referenced by InitializeTextWindow().
DrawWindow()
void DrawWindow (PixelWriter & writer, const char * title)
Definition at line 105 of file window.cpp.
References anonymous_namespace{window.cpp}::close_button, FillRectangle(), PixelWriter::Height(), anonymous_namespace{window.cpp}::kCloseButtonHeight, anonymous_namespace{window.cpp}::kCloseButtonWidth, ToColor(), PixelWriter::Width(), PixelWriter::Write(), and WriteString().
Referenced by InitializeMainWindow(), InitializeTaskBWindow(), and InitializeTextWindow().